### ISSUE TITLE
CouchDB 1.6 service

### ISSUE THREAD

**Issue by ro-ka** [drone/drone#1040]
The most recent CouchDB version that is available as a service is `1.5`. The actual release is `1.6.1`.

**Comment by bradrydzewski** [comment]
hey there, the Drone images are being deprecated in favor of the official Docker library images and language packs. If an official CouchDB image does not exist, you can use one of the un-official images in the index:
https://registry.hub.docker.com/search?q=couchdb&searchfield=

and specify in your `.drone.yml` like so:

```
services:
  - klaemo/couchdb

**Comment by ro-ka** [comment]
I tried to use a service like this. How do I access the CouchDB from within my app? `localhost`, `0.0.0.0` and `127.0.0.1` are not working.

**Comment by bradrydzewski** [comment]
the Dockerfile that creates the couchdb image should expose the relevant port(s), for example `EXPOSE 5984`. Drone will detect exposed ports and automatically setup a proxy between containers over localhost using `socat`

**Comment by ro-ka** [comment]
Tried that with exactly that image but a simple curl against the port fails. Any ideas?

**Comment by bradrydzewski** [comment]
can you share your `.drone.yml` with any sensitive data removed?

**Comment by ro-ka** [comment]
Here it is:

```yml
image: node:0.12

services:
  - klaemo/couchdb

script:
  # workaround for cache, see https://github.com/drone/drone/issues/147
  - mkdir -p /tmp/npm
  - npm config set cache /tmp/npm --global

  # actual tests
  - npm install --silent
  - npm -g install bower --silent
  - bower install --allow-root --silent
  - npm test

notify:
  email:
    recipients:
      - ***
      - ***

  slack:
    team: ***
    channel: '#***'
    username: drone
    webhook_url: https://hooks.slack.com/services/***
    on_started: false
    on_success: false
    on_failure: true

cache:
  - /tmp/npm
```
