### ISSUE TITLE
before_script and after_success steps

### ISSUE THREAD

**Issue by fommil** [drone/drone#1045]
as in travis, very useful for slow stages that shouldn't affect the build status.

**Comment by bradrydzewski** [comment]
I think the `0.4` yaml and plugins should definitely help with emulating the behavior of `after_success`, since certain plugins can already run in "forked mode" which means they run async and don't impact the build result. An example of this are the notification plugins.

How does `before_script` work? Does the build block until `before_script` has started? If `before_script` fails does it fail the build? It would be helpful to understand a bit more about `before_script` and its intended use case

**Comment by fommil** [comment]
I actually don't know what the semantic difference is between before_script and script. Yes, it would fail the build. I guess it's more about code cleanliness. So I only really care about after_success but it was more a general query about phases.

**Comment by bradrydzewski** [comment]
cool, thanks for the clarification. Let's see how far we can get with `0.4` once it is available, and then we can augment at needed. The use case definitely makes sense

**Comment by hd-deman** [comment]
@bradrydzewski this can be reopened, since 0.4 is nearly ready and this issue is still actual.

**Comment by nderjung** [comment]
Is there any update on this?

**Comment by bradrydzewski** [comment]
no, this change was no longer required since the .drone.yml file supports multiple steps in a pipeline.

**Comment by nderjung** [comment]
Ah ok.  The reason i asked was that I have multiple steps where I need to login to a private registry and I don't want to be write the following for every step:

```YAML
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: personal/repo
      auto_tag: true
      registry: index.example.com
      target: imagebuilder
```

I have seen, however, a neat trick with YAML labels with GitLab CI that works like this:

```YAML
.docker-login: &docker-login
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD index.example.com

...

step:
  <<: *docker-login
  script:
    - docker pull index.example.com/personal/repo:latest
    - # etc
```

Which is a succinct way to use YAML and be able to extend individual pipeline elements' set of commands/scripts.  is there a succinct way to accomplish something like this with Drone? Or a way to globally log in to a private docker registry?
