### ISSUE TITLE
UI should handle long commit messages

### ISSUE THREAD

**Issue by benjumanji** [drone/drone#1057]
Can we just have the one line shortlog? Example:

![2015-06-13-105702_268x670_scrot](https://cloud.githubusercontent.com/assets/290429/8143890/fb4bd9e0-11ba-11e5-874e-7175ac19cee1.png)

**Comment by bradrydzewski** [comment]
this bug exists in 0.4 as well and needs resolved

cc @nodesocket

**Comment by nodesocket** [comment]
Here is a solution, though it is not cross-browser, though seems to work in Chrome:

````css
.build-summary h3 {
   overflow: hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-box-orient: vertical;
   -webkit-line-clamp: 2; /* number of lines to show */
}
````
