### ISSUE TITLE
no logs when docker.tty = true

### ISSUE THREAD

**Issue by fommil** [drone/drone#1081]
requested in #1048 unfortunately the feature to enable a tty will hide all log output.

I set up a test project for this: https://github.com/fommil/drone-tests

with

``` yaml
image: ensime/ensime:latest
docker:
  tty: false
script:
  - echo hello
```

and then

``` yaml
image: ensime/ensime:latest
docker:
  tty: true
script:
  - echo hello
```

confirming that this is the minimal change needed to trigger the problem.
