### ISSUE TITLE
Unable to fetch submodule

### ISSUE THREAD

**Issue by mtanzi** [drone/drone#1092]
Hi,

I am trying to test a repository that require to pull a submodule repo in order to be deployed, when the deploy starts, the main repository look to have the right key but when it try to fetch the git submodules it throws an error saying that the repository was not found:

here is the error on the stacktrace
```
$ git clone --depth=50 --recursive --branch=my-branch git@github.com:xxx/main_repo.git /var/cache/drone/src/github.com/xxx/main_repo
Cloning into '/var/cache/drone/src/github.com/xxx/main_repo'...
Warning: Permanently added 'github.com,x.x.x.x' (RSA) to the list of known hosts.
Submodule 'submodule_repo' (git@github.com:xxx/submodule_repo.git) registered for path 'submodule_repo'
Cloning into 'submodule_repo'...
ERROR: Repository not found.
fatal: The remote end hung up unexpectedly
Clone of 'git@github.com:xxx/submodule_repo.git' into submodule path 'submodule_repo' failed
```

I checked the public key and they look correct for both the main repo and the submodule repo

here is my `.drone.yml` file
```yml
image: bradrydzewski/ruby:1.9.3
env:
 - RAILS_ENV=test
script:
  - cp config/drone.database.yml config/database.yml
  - bundle install
  - psql -c 'create database test;' -U postgres -h 127.0.0.1
  - bundle exec rake db:schema:load
  - bundle exec rspec spec
services:
  - postgres
```

Any idea why it cannot find the repo?

**Comment by benschumacher** [comment]
Drone only associates the keypair it generates for a build with a single repository. You can see this by viewing the "Deploy keys" in "Settings" for the parent repository. When you're pulling in something as a submodule that is in another private repo, that keypair doesn't have access to that content.

The easiest way to resolve this is to remove the public key from "Deploy keys" from the parent project, and instead associated with a user or organization that has access to all necessary repositories. See also drone/drone#1040.

**Comment by mtanzi** [comment]
@benschumacher I am fairly new with drone so I might have missed something, I haven't found any configuration option where I can set the github user to drone - How can I do that?

**Comment by benschumacher** [comment]
@mtanzi Drone exposes the public part of the keypair if you go to "Settings" for a build. You'll need to copy that content, then go to GitHub user/organization and add a new "SSH keys" in the section of "Settings". One note, as I intimated earlier, GitHub won't let you have the same public key in two different locations within their system -- you'll have to remove the key from "Deploy keys" for the specific repo.

Hope this helps.

**Comment by bradrydzewski** [comment]
@benschumacher is correct. The ssh key that Drone uploads to your repository only has permission to clone that repository (submodules not included). The key needs to be moved from the repo-level to the user-level, granting it access to clone multiple repos. Ben has described the steps to make that work (thanks Ben)

Hopefully that helps. Please feel free to use gitter.im/drone/drone for further questions

**Comment by mtanzi** [comment]
Thanks a lot @benschumacher @bradrydzewski  I'll set the ssh key at the user level.

**Comment by sdbondi** [comment]
I have the same problem using 0.5 - submodules using ssh cannot be pulled. Is there a way to add a public key for the drone server as a deployment key or what is the recommended way to solve this in 0.5? Thanks

**Comment by bradrydzewski** [comment]
@sdbondi drone supports mapping ssh submodules to https. Please see the following section of the documentation:
http://readme.drone.io/0.5/usage/cloning/#private-submodules:694aaf6bb8eef58529ced737905d0d1a

**Comment by sdbondi** [comment]
@bradrydzewski Thanks for the quick response :+1: A little confused, does the `clone` key in `pipeline` have a special meaning? I get an `Image not found` error because I'm not specifying an image.

From the docs:
```yaml
pipeline:
  clone:
    # Seems to be looking for an image?
    recursive: true
    submodule_override:
      hello-world: https://github.com/octocat/hello-world.git
```
