### ISSUE TITLE
Implement aliases for services

### ISSUE THREAD

**Issue by dennybaa** [drone/drone#1113]
There is no clear understanding of how it must be implemented in drone YAML schema, but the background is that we need somehow to handle images with different tags but from the same repository:

```yaml
image: worker-unit
script:
  - ./.drone/build.sh
services:
  - buildpack-deps:jessie
  - buildpack-deps:trusty
  # - buildpack-deps:trusty:stage-ubuntu this of course doesn't look well, should be a cleaner way to represent an alias.
```

However the clue might be be taken from docker-compose, let's have a look here:

```yaml
worker:
  image: ubuntu
  command: bash -c 'cat /etc/hosts'
  links:
    - trusty:stage-ubuntu
    - jessie:stage-debian 

trusty:
  image: buildpack-deps:trusty
  command: bash -c 'sleep infinity'

jessie:
  image: buildpack-deps:trusty
  command: bash -c 'sleep infinity'
```

First docker-compose names specific images, so they come with another name other than its image repository. However a more important feature it's how compose handles links (which are technically the same to *drone __services__*). These links support **aliases**, and exactly this feature would be useful in drone.

Btw here are the details for what we can see in the hosts file.

```
172.17.0.40	trusty_1 9be73b7257a9 tmp_trusty_1
172.17.0.39	jessie_1 10db588f9d9a tmp_jessie_1
172.17.0.39	stage-debian 10db588f9d9a tmp_jessie_1
172.17.0.40	stage-ubuntu 9be73b7257a9 tmp_trusty_1
172.17.0.39	tmp_jessie_1 10db588f9d9a
172.17.0.40	tmp_trusty_1 9be73b7257a9
```
