### ISSUE TITLE
Improve conditional step logic in Yaml

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1157]
We currently have a `Condition` structure that let's us conditionally execute steps in the `.drone.yml` file represented by the `where` attribute.

```Go
type Condition struct {
	Owner  string // Indicates the step should run only for this repo (useful for forks)
	Branch string // Indicates the step should run only for this branch

	// Indicates the step should only run when the following
	// matrix values are present for the sub-build.
	Matrix map[string]string
}
```

The above is represented in the yaml as:

```yaml
publish:
  heroku:
    when:
      branch: master
```

### When Repo

Probably less confusing to specify `repo` instead of `owner` to prevent steps from running for forks. For example, specify `repo: drone/drone` to prevent `bradrydzewski/drone` fork from executing a build step:

```diff
type Condition struct {
-	Owner string
+	Repo  string
}
```

### When Success, Failure, Change

The ability to filter steps by status exists in 0.3, however, has not been implemented in 0.4. This is one proposal to do so:

```diff
type Condition struct {
+	Success bool
+	Failure bool
}
```

which could be represented in the yaml as:

```yaml
publish:
  heroku:
    when:
      success: on|off|on_change
      failure: on|off|on_change
```

or an alternative:

```yaml
publish:
  heroku:
    when:
      success: false
      failure: false
      change: true
```

In order to facilitate `on_change` we need to fetch and send the last build as part of the current build's payload. This filtering should happen external to the plugin, in the `drone-build` controller, so that each plugin doesn't have to duplicate the same filtering logic.

### When Event Is...

We should give the ability to limit steps based on the hook event type. For example, we may want to execute some steps only for `pull_request` events, and others only for `tag` events. This will also help us support the GitHub `deployment` API flow:

```yaml
publish:
  heroku:
    when:
      push: on|off
      pull_request: on|off
      tag: on|off
      deploy: on|off
```

or an alternative:

```yaml
publish:
  heroku:
    when:
      event: push|pull_request|tag|deployment
```

**Comment by donny-dont** [comment]
Is there any good way to determine when its a glob and when its a regular expression? The former is easier to understand and use, aka release/*, but the later is definitely more powerful.

**Comment by bradrydzewski** [comment]
hmm, good point. I'm removing the `glob` changes for now, since it has worked well previously and nobody has asked for anything more powerful to date.

**Comment by bradrydzewski** [comment]
first pass at https://github.com/drone/drone-exec/commit/3a17434112540c15fac60307a7595b1b7380b251

```yaml
when:
  success: on|off
  failure: on|off
  event: push|pull_request|tag
```

This is a basic implementation that omits `change` conditions. We don't currently pass the prior build down with the other build meta data, which is required to implement this feature. The event filter implementation is a bit of a hack until I add an actual `Build.Event` field. We also don't support tags or deployments yet.
