### ISSUE TITLE
Add extra hosts to drone services

### ISSUE THREAD

**Issue by khirakawa** [drone/drone#1218]
We currently have a use case where we need to update the `/etc/hosts` file of a drone service.

If we could so something along the lines of the following code block in our `.drone.yaml`, that would be awesome:

```
extra_hosts:
 - "somehost:162.242.195.82"
 - "otherhost:50.31.209.229"
```

(taken directly from @bradrydzewski on gitter)

**Comment by bradrydzewski** [comment]
added `extra_hosts` capabilities: https://github.com/drone/drone-exec/commit/6b5e5a1118c8edab59a9aca8efc035bad80ca2cc

still needs documentation, but works like this:

```
build:
  image: golang
  commands:
    - go build
    - go test
  extra_hosts:
   - "somehost:162.242.195.82"
   - "otherhost:50.31.209.229"
```

the `extra_hosts` can be added to any section of the yaml, including `build`, `publish`, `deploy`, `compose` and `notify` sections

**Comment by bradrydzewski** [comment]
added reference in docs @ https://github.com/drone/drone/commit/5cc99514c87d788199afa0d5e6c35d7bb6420e08

**Comment by khirakawa** [comment]
Awesome, thanks!

**Comment by khirakawa** [comment]
@bradrydzewski From gitter: https://gitter.im/drone/drone?at=564680126296df7f6efea261

So I modified our docker.yml to have this:

```
build:
  image: company/mainimage
  pull: true
  commands:
    - sh build.sh
  extra_hosts:
   - "some_host:127.0.0.1"
```

Then in the `build.sh`, ran `ping -c 1 some_host`. Got back `ping: unknown host`

Our drone server should be updated to the latest as well.  Any clue why this might be happening?  

cc @donny-dont

**Comment by tfukaya** [comment]
I think it is docker side issue.
In 1.6.2, it seems that the container network mode does not support ExtraHost capability.
( hosts and bridge network modes call buildHostnameAndHostsFiles which makes /etc/hosts.
but the container does not.
https://github.com/docker/docker/blob/v1.6.2/daemon/container.go#L1225-L1237 )
The behavior is same in docker 1.9.0 which I am using.

A container using the container network mode shares /etc/hosts used by an ambassador container.

I make a quick patch that set ExtraHosts in an ambassador, then test cat /etc/hosts in .drone.yml, get a result as a below.

```
$ cat /etc/hosts
172.17.0.4	70bb0301922d
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
127.0.0.1	test
```

diff

```
diff --git a/docker/docker.go b/docker/docker.go
index 09c8181..8434f29 100644
--- a/docker/docker.go
+++ b/docker/docker.go
@@ -17,6 +17,7 @@ func NewClient(docker dockerclient.Client) (*Client, error) {
        conf := &dockerclient.ContainerConfig{}
        conf.HostConfig = dockerclient.HostConfig{
                MemorySwappiness: -1,
+               ExtraHosts:       []string{"test:127.0.0.1"},
        }
        conf.Entrypoint = []string{"/bin/sleep"}
        conf.Cmd = []string{"86400"}
```

**Comment by cdaguerre** [comment]
The `extra_hosts` key doesn't seem to work.
The hosts are not appended to the container's `/etc/hosts`.
I understand @tfukaya made it work but not sure how to do it...
Could you point in the right direction? I'd be glad to update the docs ;)

**Comment by appleboy** [comment]
Confirmed this issue on v0.5.0. 

```
pipeline:
  build:
    image: laradock/workspace:1.0
    pull: true
    environment:
      - INSTALL_XDEBUG=true
      - INSTALL_NODE=true
    commands:
      - php -v
      - node -v
    extra_hosts:
      - "xxxxx:172.21.90.118"
```

It is not working on Docker `v1.11.2`.
