### ISSUE TITLE
base64 not found in container

### ISSUE THREAD

**Issue by antonikonovalov** [drone/drone#1220]
![2015-10-06 17 16 55](https://cloud.githubusercontent.com/assets/1614346/10311592/170aba62-6c50-11e5-8edf-50fca525749b.png)
You using base64 for decode variable?
it's need add to container? I am used 
```
build:
  image: antonikonovalov/drone-image-go:latest
  insecure: true
  environment:
    - PATH=$GOPATH/bin:/usr/local/bin:$PATH
    - MP_DOCKER_CHANNEL=TEST-DRONE
  commands:
    - go get -u github.com/antonikonovalov/money
    - make local_deps
    - make test
    - make build
    
compose:
  elastic:
    image: elasticsearch
  mongodb:
    image: mongo
  nsq:
    image: antonikonovalov/dockerfile-nsq
```
