### ISSUE TITLE
Can't load custom plugin

### ISSUE THREAD

**Issue by jmccann** [drone/drone#1271]
We are using `drone/drone:0.4` and when I try to use a custom plugin I created it does not load.

I edited `/etc/drone/dronerc` to have

```
PLUGIN_FILTER=plugins/* jmccann/*
```

And I added a deploy block similar to below to my `.drone.yml`:

```yaml
deploy:
  chef:
    when:
      branch: test_deploys
    user: myuser
    key: mykey
    server: "https://chefserver.com"
    org: myorg
```

And what I get in the logs are:

```
[info] Pulling image plugins/drone-chef:latest
[info] Pulling image plugins/drone-chef:latest
[error] Error pulling plugins/drone-chef:latest. Error: image plugins/drone-chef:latest not found
```

I'm following instructions @ http://readme.drone.io/setup/plugins.html to try and do this.  Am I missing something?  Or is this a bug?

I wasn't familiar with the docker env files so I also tried (which I think isn't supposed to work):

```
PLUGIN_FILTER="plugins/* jmccann/*"
```

But that resulted in builds not working at all with:

```
[fatal] Error parsing the .drone.yml
```

**Comment by bradrydzewski** [comment]
@jmccann you'll need to specify your image in the `.drone.yml`:

```
deploy:
  chef:
    image: jmccann/chef
    when:
      branch: test_deploys
```

using `chef` in your original example is a shorthand for an official Drone plugins. Drone interprets `chef` as `plugins/drone-chef`
