### ISSUE TITLE
create arbitrary build, deployment events for repos

### ISSUE THREAD

**Issue by macb** [drone/drone#1303]
https://github.com/drone/drone/commit/0e5ee4470038ac75b3b2bb9b39f460a24cb3b19e added the ability to fork previous builds so that history was maintained for the old build.

I think it would be a step further to allow a user to create a build via a similar API endpoint but instead of forking the commit, branch, etc from previous build history, we could instead specify them as part of the API call.
### Deployment Builds

The use case that sparked this request is an internal build/deploy pipeline. There might be parts of the build that are expensive (maybe they take a long time or generate a lot of artifacts) which you only want to perform when required (such as when generating a docker container for deployment). It would be nice to perform these actions via Drone but only when needed.

The flow might be something like:
- User decides to promote commit abc123 to production.
- User submits a build request to drone for commit `abc123` with additional information so the build can include different steps.
  - Could tie into the `deploy`, `publish` using `when` semantics to match if its a build pushed via the API as opposed to github hook.
### Periodic Integration Tests

Another use case might be nightly integration tests or on-deploy integration tests of multiple services. Making use of the `service` block and environment variables, it would be possible to generate a dynamic build periodically that could compose multiple pieces of an infrastructure.

Imagine an application made up of:
- Web App
- Service App
- Database

Web app talks to service app which talks to the database. It might be relatively expensive to have all three elements present for every build but it could be very helpful for there to be some verification for them as a unit in some integration suite periodically.

Maybe a sample drone file

``` yaml
compose:
  web:
    image: webapp:$$WEBAPP_VERSION
  service:
    image: service:$$SERVICE_VERSION
    environment:
      - DB_USER=root
      - DB_PASSWORD=password
  database:
    image: mysql
build:
  image: integration
  commands:
    - integration.sh
```

Where `WEBAPP_VERSION` and `SERVICE_VERSION` are examples of arbitrary metadata submitted as part of the build creation.

This could be done currently by submitting a new commit to an `integration` repo periodically but that seems like a less straightforward interface than via the drone API.
