### ISSUE TITLE
Parser that safely injects secrets can remove a plugin used multiple times

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1326]
global variables are safely injected into the yaml. This means we parse the yaml and ensure we inject into every section except the build section. This also applies to pull requests.

This safe parsing and injection process unmarshals the yaml into temporary `map[string]interface` values. This process causes the below yaml:

```
deploy:
  docker:
    repo: foo/bar
  docker:
    repo: foo/baz
```

to get unmarshaled and re-marshaled as the following:

```
deploy:
  docker:
    repo: foo/baz
```

notice that the two docker plugin deployments were collapesed into a single. This is because the `map[string]interface` is a map, and we cannot have two `docker` keys in a map (they just overwrite one another)

until we have a permanent fix, you can avoid this edge case by giving your docker steps unique names:

```
deploy:
  docker_1:
    image: drone-docker
    repo: foo/bar
  docker_2:
    image: drone-docker
    repo: foo/baz
```
This bug impacts publish / deploy / notify sections when an installation has global plugin parameters. It also impacts pull requests that have the same Notification plugin defined multiple times (notifications only).
