### ISSUE TITLE
Drone 0.4 does not expand environment variables in publish section. 

### ISSUE THREAD

**Issue by tooda02** [drone/drone#1339]
If a publish section contains an environment variable reference, such as the `target` line below:

    publish:
      bintray:
        image: shippedrepos-docker-drone.bintray.io/drone-bintray
        username: $$bintray_user
        api_key: $$bintray_api_key
        artifacts:
          - file: dist/shipped-cli-linux
            owner: shippedrepos
            repository: shipped-cli
            package: executables
            version: 0.1
            target: ${testFolder}linux/shipped
            publish: true
            override: true

Drone 0.4 does not expand the environment variable.  Instead, the value is passed to the plugin, dollar sign and all.  This used to work in Drone 0.3

**Comment by bradrydzewski** [comment]
The 0.4 plugin model was overhauled to run plugins in dedicated containers. Now that plugins can run in dedicated containers they are no longer simple shell scripts (they are written in Go). Since plugins run in isolated containers they cannot share the bash context, combined with the fact that they are no longer written in bash, we have no way to expand the environment variable.

This is a design limitation of the 0.4 plugin system and will not be possible

**Comment by tooda02** [comment]
Is it not possible to expand the environment variable in .drone.yml before passing it to the dedicated container?  This would be a matter of pre-processing .drone.yml, similar to what Drone does now for $$ variables filled from .drone.sec

**Comment by bradrydzewski** [comment]
the `.drone.yml` is parsed before the build executes. The parsed yaml is converted to an AST representation at which point we can no longer perform the Yaml pre-processing steps, such as parameter injection.

so that I can better understand what you are trying to achieve, can you provide more of your yaml? Where is the `testFolder` being set?

**Comment by tooda02** [comment]
The testFolder variable is set in the last line of the build section:

> test "$DRONE_BRANCH" != "master" && testFolder="test/$DRONE_BRANCH/" && echo && echo "==> Placing artifacts in folder $testFolder"

The objective is to put build artifacts in a different place if they're generated by a checkin on a branch.  I can also do this if the standard environment variable DRONE_BRANCH was available to the plugin.   Is this currently available or could it be made available?

BTW, this is a part of a bintray plugin I've written that I'll be donating to the project.

**Comment by bradrydzewski** [comment]
if you have different configurations for push vs tags you can have multiple bintray sections in your `.drone.yml` file, for example:

```yaml
publish:
  bintray:
    image: shippedrepos-docker-drone.bintray.io/drone-bintray
    username: $$bintray_user
    api_key: $$bintray_api_key
    artifacts:
      - file: dist/shipped-cli-linux
        owner: shippedrepos
        repository: shipped-cli
        package: executables
        version: 0.1
        target: /path/when/branch/linux/shipped # fixed path for push events
        publish: true
        override: true
    when:
      event: push  # this only executes for push events

  bintray:
    image: shippedrepos-docker-drone.bintray.io/drone-bintray
    username: $$bintray_user
    api_key: $$bintray_api_key
    artifacts:
      - file: dist/shipped-cli-linux
        owner: shippedrepos
        repository: shipped-cli
        package: executables
        version: 0.1
        target: /path/to/tag/linux/shipped # fixed path for tag events
        publish: true
        override: true
    when:
      event: tag # this only executes for tag events
```

> The testFolder variable is set in the last line of the build section:

I'm not aware of any way to extract environment variables from a stopped container that were set during container execution.

> I can also do this if the standard environment variable DRONE_BRANCH was available to the plugin. Is this currently available or could it be made available?

yes, see the "Substitution" section of this document: http://readme.drone.io/build/env.html

Some variables, including branch are available for substitution in the yaml similar to secret variablesn using the `$$` notation. This includes both branch and tag.
