### ISSUE TITLE
Configure named data volumes in yaml

### ISSUE THREAD

**Issue by nils-werner** [drone/drone#1348]
Many applications like `apt-get` and `pip` place their cache in directories outside of the current workspace. It would be great if those applications could be cached as well.

**Comment by bradrydzewski** [comment]
changing title to support data volume configuration, which in turn would allow other paths to be mounted and persisted across builds.

```
version: "3"

services:
  db:
    image: db
    volumes:
      - data-volume:/var/lib/db
  backup:
    image: backup-service
    volumes:
      - data-volume:/var/lib/backup/data

volumes:
  data-volume:
```

per https://docs.docker.com/compose/compose-file/#/volume-configuration-reference
