### ISSUE TITLE
Compose with postgres could not connect to server: Connection refused

### ISSUE THREAD

**Issue by artworx** [drone/drone#1395]
`drone/drone:0.4` running the latest docker image.

```
build:
  image: phusion/passenger-ruby22
  commands:
    - bundle install
    - bundle exec rake db:create
  environment:
    BUNDLE_PATH: bundle
    DATABASE_URL: postgresql://postgres:postgres@localhost/blog_development?pool=5
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
cache:
  mount:
    - bundle
```

When the cache is available, postgres doesn't start fast enough and i get `Connection refused`. If i add `sleep 10` to the commands, postgres is started by the time its needed.

This doesn't seems to happen with drone 0.3, is there some way to way for the linked container to start?
