### ISSUE TITLE
Docker base image up for change?

### ISSUE THREAD

**Issue by cloudnautique** [drone/drone#1426]
Hi All, I wanted to ask if the community would be open to changing the base Docker image from "scratch" to alpine or busybox. I really like scratch, I do, but it limits extendability when the tools inside have an external dependency. For instance, if I need to wait for the existence of a configuration file that will contain all of my environment variables, I have no way to extend without making my own image because there is no shell.

 By creating a configuration container, that will generate the file with confd and share a new entrypoint script to source it, I could alter the behavior _WITHOUT_ modifying the upstream container and all of its goodness. By injecting configuration and alternate scripts, one does not need to worry about disturbing the core dependencies of the app.

something like:

```
drone:
  image: drone/drone:0.4
  entrypoint: /opt/scripts/entry
  volumes_from:
    - drone-config
...
drone-config:
  image: cloudnautique/drone-config:0.4
  volumes:
    - /opt/scripts
```

with a script in `/opt/scripts/` that looks like

```
#!/bin/bash
 while [ ! -e /etc/drone/dronerc ]; do
    sleep 1
 done

source /etc/drone/dronerc
exec /drone_static
```

Currently, something like this fails because there is no shell in drone:0.4. 

Alternatively, if the binary was placed in a folder instead of `/` the relationship could be flipped. So if /drone/bin/drone_static was where the binary lived, the container could be launched with `-v /drone` and picked up with volumes-from in the conf container. 

In general, I like the idea of having a shell for troubleshooting purposes, but I certainly see the benefits of `scratch`.

Thoughts? Alternate approaches? I will be happy to put in a PR one way or another.
