### ISSUE TITLE
Feature Request: ecr build image support

### ISSUE THREAD

**Issue by netbe** [drone/drone#1430]
Since we can build and push an image to Amazon ecr, I guess support to run from an image stored on ecr would not be too much work. Mainly porting the options from drone-ecr to image

```
    image: myImage
    access_key: ...
    secret_key: ...
    region: us-east-1
    repo: myRepo
```

And make it also available from compose.

In the meantime, is there a way to do it without this feature specifying a raw url of amazon ecr in image field?

**Comment by bradrydzewski** [comment]
My initial reaction is that we wouldn't build amazon-specific logic into the drone build process. Drone attempts to provider agnostic. Is there a way to pull an image from amazon using the standard username / password / email? Google Container Engine does this by letting you specify any dummy username and email, and then just providing a json token as the password

**Comment by netbe** [comment]
@bradrydzewski the way I've seen it you first ask Amazon for the credentials via `aws ecr get-login` which gives you a docker login command to execute (this will be valid for 12hours)

```
docker login -u AWS -p <crypted password> -e none https://<account_id>.dkr.ecr.us-east-1.amazonaws.com
```
and then you can pull normally.

The weird thing is I tried to just login via this command on the server, and then execute the job via drone but still get a `Authentication is required.` message. So I am wondering how drone pull the image, is it inside a docker container too?

PS: You mention username/ password is there already a way to pass those to pull and run the image?

**Comment by bradrydzewski** [comment]
see the example of `auth_config` in this section of the docs http://readme.drone.io/usage/build_test/#images:fb92aa3346185c57f15afda861d465a3

I'm just not sure we would alter drone core to support amazon's non-standard authentication process. This doesn't mean you can't use build images from amazon ecr, it just means drone can't automatically download them at the moment.

I would suggest using a tool like watchtower to auto-upgrade, but that would also be incompatible with amazon's custom authentication process.

**Comment by johnrengelman** [comment]
You could in theory write a small container that runs every 12 hours and updates the docker login credentials...just run that on the same servers that you are running the drone builds on. Something like this but without the Rancher piece. https://github.com/objectpartners/rancher-ecr-credentials

**Comment by bramswenson** [comment]
Is there a hook to run commands just before drone does things with images we have configured? Something like:

```
build:
  before_pull: aws ecr get-login
  image: XXXXXX.dkr.ecr.eu-west-1.amazonaws.com/myimage
  ...
```

**Comment by fixe** [comment]
@bradrydzewski I believe [this](https://github.com/drone/drone/blob/0bab3771bc4e60cdb934be0275080bd098ed6c7e/drone/agent/agent.go#L116) and [this](https://github.com/drone/drone/blob/b35adcd7397d64368f184c56bd7adbdf2900c07b/drone/exec.go) shouldn't be in the code as well. What about moving that logic to the docker plugin?

**Comment by bradrydzewski** [comment]
@fixe it is there intentionally. The ecr plugin has special authentication requirements and, to my understanding, therefore needs to be its own plugin https://github.com/drone-plugins/drone-ecr/blob/master/main.go#L58:L63

**Comment by fixe** [comment]
@bradrydzewski that's why I've created [this](https://github.com/drone-plugins/drone-ecr/issues/21) issue. I think it's better to add support for multiple providers in the docker plugin rather than having this hardcoded in the drone core.

**Comment by nunofgs** [comment]
> @johnrengelman You could in theory write a small container that runs every 12 hours and updates the docker login credentials...just run that on the same servers that you are running the drone builds on.

Even if you do this (which would be an acceptable solution for me), I don't believe drone 0.4.2 is passing the docker authentication config when pulling the plugin image. (see [here](http://github.com/drone/drone/blob/73f9c44d7fc8385319c35156b82a8fce8636a810/engine/worker.go#L64))

**Comment by bradrydzewski** [comment]
> that's why I've created this issue. I think it's better to add support for multiple providers in the docker plugin rather than having this hardcoded in the drone core.

this probably comes down to personal preference. I would prefer to have hard-coded values than have a single mega-plugin for all docker providers.

**Comment by bradrydzewski** [comment]
@nunofgs you could use watchtower which will poll for and download updated images https://github.com/CenturyLinkLabs/watchtower ... once the image is available in the local docker cache drone will be able to use it for your build image

**Comment by ashramsey** [comment]
I was able to login to ecr and have drone pull and use my image with the following:

```
build:
  app:
    image: 12345.dkr.ecr.ap-southeast-2.amazonaws.com/my-image:latest
    auth_config:
        username: AWS
        password: $$ECR_TOKEN
    commands:
      - npm install
      - npm test
      - sls deploy
...
```

where $$ECR_TOKEN is the -p value from running `aws ecr get-login` on my local machine, stored in my secrets.yml file to be passed in via `drone secure  --repo <repo> --in secrets.yml`, committed and pushed to github for drone to kick off.

Only sore point is each time I commit, i need to run a script that gets a new token and push that into the `drone secure ` call. Maybe it could be handled and injected on the agent's host via cron.

**Comment by exocode** [comment]
> Only sore point is each time I commit, i need to run a script that gets a new token and push that into the drone secure call. Maybe it could be handled and injected on the agent's host via cron.

this will be very helpful, it's annoying to do this EVERY time...

**Comment by bradrydzewski** [comment]
maybe consider adding a block to your yaml that downloads the image on the host machine as part of your build pipeline. Note below example is for 0.5, but should work on 0.4

```
pipeline:
  auth:
    image: some-image-with-ecr-client-and-drone-cli
    commands:
      - aws ecr get-login | bash -c
      - docker pull 12345.dkr.ecr.ap-southeast-2.amazonaws.com/my-image:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build:
    image: 12345.dkr.ecr.ap-southeast-2.amazonaws.com/my-image:latest
    commands:
     - npm intstall
     - npm test
```

**Comment by scottlackey** [comment]
In case anyone else needs a quick solution to this problem, I created an image for this purpose and it works well for enabling pulls from ECR from within drone. Since it needs to have AWS credentials saved in it I would only push the image to a private registry.
https://github.com/scottlackey/drone-auth-ecr

```bash
pipeline:
  auth:
    image: drone-auth-ecr
    auth_config:
      username: ${DOCKER_REGISTRY_USERNAME}
      password: ${DOCKER_REGISTRY_PASSWORD}
    commands:
      - aws ecr get-login | bash 
      - docker pull 12345.dkr.ecr.us-west-2.amazonaws.com/my-image:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  build:
    image: 12345.dkr.ecr.us-west-2.amazonaws.com/my-image:latest
    commands:
     - npm intstall
     - npm test
```

**Comment by gtaylor** [comment]
Is there no way to pull these using the IAM Role, rather than passing the creds in like this?

**Comment by scottlackey** [comment]
Good call, I updated the config to not include a credentials option and to just rely on IAM role automation. Tested working.

**Comment by ktruckenmiller** [comment]
I'd like to add that https://github.com/awslabs/amazon-ecr-credential-helper helped me with my agent instances. So the host has the ability to do a docker pull, but it wouldn't. 

My suggestion would be, recommend the aws cred helper, then when that is working - just give the agent the ability to try and pull it if it doesn't exist locally.

**Comment by ozbillwang** [comment]
I used `amazon-ecr-credential-helper`, so if manually run docker pull `12345.dkr.ecr.us-west-2.amazonaws.com/my-image:latest` from drone agents, I can directly pull the image without login. 

But when test in Drone pipeline, it always reports the error:

       Cannot override container command

My pipeline is

```
pipeline:
  assume-role:
    image: 12345.dkr.ecr.us-west-2.amazonaws.com/my-image:lates
    pull: true
    command:
      - bash -x assume-role.sh
```

**Comment by bradrydzewski** [comment]
@ozbillwang You have a typo. You need `commands` (with an s) and you have command (no s). Regarding the volume issue, please see the note in the volume docs regarding trusted mode.

Since these issues / questions are not related to this issue, please move the discussion to gitter.

**Comment by ozbillwang** [comment]
@bradrydzewski Thanks a lot, that's fix my issue.

**Comment by ozbillwang** [comment]
My update to deal with this issue by a lot of workarounds, which I really don't like the solution at all.  I hope Drone.io can fix it from core. Support docker pull, build and push to AWS ECR should be a basic requirement.

My requirement is different, in beginning of any pipeline, I need to `assume role` first, it is company customized and can't be push to public docker hub. 

I can't save the AWS API key to drone secure as well, because STS token only lasts for one hour, and keeps changing.  Then I got confirmed, Drone doesn't support to transfer the environment variables to next steps 

 **I prefer to have a feature that if environment variables start from `PLUGIN_`, it can be automatically transferred to next step.** 

So first step, I built an image `assume-role` with `assume-role.sh` script and push to AWS ECR. This is the problem beginning when using Drone. 

1) Assume role and generated a token file

```
pipeline:
  pull_image_assume_role:
    image: ozbillwang/drone-amazon-ecr-credential-helper:1.0
    pull: true
    commands:
      - docker pull 1234567890.dkr.ecr.ap-southeast-2.amazonaws.com/aws-cli:1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  assume-role-dev:
    image: 1234567890.dkr.ecr.ap-southeast-2.amazonaws.com/aws-cli:1.0
    commands:
      - assume-role.sh dev
```

with above pipelines, I can pull the ECR image via another public image. Similar solution as @scottlackey did ( https://github.com/drone/drone/issues/1430#issuecomment-283441564)

But I have to give the `Trusted` permission in Drone for this job.
