### ISSUE TITLE
Drone cannot unmarshal !!str `eyJhbGc...` into yaml.Plugin

### ISSUE THREAD

**Issue by valentinbud** [drone/drone#1444]
I don't know it this is the proper place to report this because I use the [Downstream Plugin](http://readme.drone.io/plugins/downstream/) and the error is somehow related. If I should post there please tell me and I will remove this one.

I have two repos, `init` and `downstream`. I would like `downstream` to be built after `init`. So I jumped in and make the configs.

init's .drone.yml
```
publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        repo: playground/init
        tag:
            - latest
notify:
    downstream:
        repositories:
            - playground/downstream
    token: "eyJhb....NiIsInR5cCI6IkpXVCJ9.....idHlwZSI6InVzZXIifQ.MoBiy-nbZJ......E_4rl24Dx8.....0JkU"
    when:
        event: push
        branch: master
        success: true
```
NOTE: the `token` has been modified before posting it, it doesn't have that much ... in it.

downstream's .drone.yml
```
publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        repo: playground/downstream
        tag:
            - latest
```

When I push to `playground/init` I see on the last build page the following:

<img width="1438" alt="screen shot 2016-01-28 at 14 48 20" src="https://cloud.githubusercontent.com/assets/3338528/12644809/4942295c-c5ce-11e5-81b5-cf1668f70c4d.png">

I have also tried to reference `$$DRONE_TOKEN` from .drone.yml in `playground/init` which is stored in `secrets.yaml` and running `drone secure ...` before pushing only to receive the same error. To be honest this is how I have tried the first time and switched to above suspecting this is the problem.

Can someone tell me please how can I fix it? Thanks.

**Comment by valentinbud** [comment]
I should mention that I have taken the token from my profile inside of drone.

**Comment by tboerger** [comment]
@valentinbud for us https://github.com/drone-plugins/drone-git-push/blob/master/.drone.yml#L32-L43 works pretty fine.

**Comment by valentinbud** [comment]
I apologise for the noise. It is an YAML indentation error :|.

```
notify:
    downstream:
        repositories:
            - playground/downstream
    token: "eyJhb....NiIsInR5cCI6IkpXVCJ9.....idHlwZSI6InVzZXIifQ.MoBiy-nbZJ......E_4rl24Dx8.....0JkU"
    when:
        event: push
        branch: master
        success: true
```
should be:
```
notify:
    downstream:
        repositories:
            - playground/downstream
        token: $$DRONE_TOKEN
        when:
            event: push
            branch: master
            success: true
```
