### ISSUE TITLE
Drone downstream plugin unable to get latest build

### ISSUE THREAD

**Issue by valentinbud** [drone/drone#1447]
I have two repositories `init` and `downstream`. They are (properly) configured so that when I push to `init`, `downstream` gets notified to build itself.

```
$ drone repo ls | grep play
playground/downstream
playground/init
```

`playground/init/.drone.yml`
```
publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        repo: playground/init
        tag:
            - latest
        registry: registry.XXX.YYY
notify:
    downstream:
        repositories:
            - playground/downstream
        token: "$$DRONE_TOKEN"
        when:
            event: push
            branch: master
```

`playground/downstream/.drone.yml`
```
publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        repo: playground/downstream
        tag:
            - latest
        insecure: true
        registry: registry.XXX.YYY
```

<img width="1440" alt="playground/init latest build" src="https://cloud.githubusercontent.com/assets/3338528/12698636/aabf92c2-c7aa-11e5-9bb6-0fa442b3125a.png">

I expected to see a new build number in `playground/downstream` but it didn't happen so I went and checked drone logs.

```
time="2016-01-29T12:51:37Z" level=info msg="Notification container drone_build_32_notify exited with 1"
time="2016-01-29T12:51:37Z" level=info msg="[info] Pulling image plugins/drone-downstream:latest\nDrone Downstream Plugin built at 2016-01-26 09:04:14 UTC\nError: unable to get latest build for playground/downstream.\n[info] build failed (exit code 1)\n"
time="2016-01-29T12:52:04Z" level=info msg="closed event stream"
```

Why would this happen? Drone is run inside a container and its public DNS hostname points to an NGINX daemon running on the host configured as reverse proxy for drone. Thanks :).

**Comment by bradrydzewski** [comment]
It fails to get the latest build from drone at this line of code:
https://github.com/drone-plugins/drone-downstream/blob/master/main.go#L58

This could fail for a number of reasons. No existing build for that repo for the default / master branch (remember drone can only restart or fork an existing build). If you run Drone and your build on the same machine their could be networking issues or restrictions with ICC.

There should be some indication in your Drone logs that shows the http request to get the latest build fails, and should provide some sort of error code. That is needed to troubleshoot. If there is nothing in your logs it means there is a networking issue on your host.

**Comment by valentinbud** [comment]
@bradrydzewski you are right. The logs I have posted above are too little. I will post the entire sequence from when I push to master `playground/init`. 

> No existing build for that repo for the default / master branch (remember drone can only restart or fork an existing build). If you run Drone and your build on the same machine their could be networking issues or restrictions with ICC.

Which build/repo are you referring to? `playground/init` or `playground/downstream`? I suspect the latter.

<img width="1440" alt="playground/downstream build" src="https://cloud.githubusercontent.com/assets/3338528/12700874/0fa2fefc-c7fd-11e5-9e50-e2e705094aaf.png">

Drone and the build are run on the same machine as well as the NGINX which is configured as a reverse proxy.

```
time="2016-01-31T07:30:55Z" level=error msg="error setting commit status for playground/init/14"
[GIN] 2016/01/31 - 07:30:55 | 200 |  159.890414ms | 144.76.174.40 |   POST    /hook
time="2016-01-31T07:30:55Z" level=info msg="preparing container drone_build_33_job_33"
time="2016-01-31T07:31:17Z" level=info msg="preparing container drone_build_33_notify"
time="2016-01-31T07:31:55Z" level=info msg="Notification container drone_build_33_notify exited with 1"
time="2016-01-31T07:31:55Z" level=info msg="[info] Pulling image plugins/drone-downstream:latest\nDrone Downstream Plugin built at 2016-01-26 09:04:14 UTC\nError: unable to get latest build for playground/downstream.\n[info] build failed (exit code 1)\n"
```

I have put NGINX on the host in debug mode and watched the logs. 
```
2016/01/31 08:37:16 [debug] 6799#0: *9 http upstream request: "/api/stream/playground/downstream?"
2016/01/31 08:37:16 [debug] 6799#0: *9 http upstream process non buffered upstream
2016/01/31 08:37:16 [error] 6799#0: *9 upstream timed out (110: Connection timed out) while reading upstream, client: 86.106.37.0, server: drone.XXX.YYY, request: "GET /api/stream/playground/downstream HTTP/1.1", upstream: "http://127.0.0.1:8090/api/stream/playground/downstream", host: "drone.XXX.YYY", referrer: "https://drone.XXX.YYY/playground/downstream"
2016/01/31 08:37:16 [debug] 6799#0: *9 finalize http upstream request: 504
2016/01/31 08:37:16 [debug] 6799#0: *9 finalize http proxy request
```

I have tried to `curl http://127.0.0.1:8090/api/stream/playground/downstream` only to receive `404`.

I have also pushed to `playground/downstream` to see if its build is still working. It is, now I have two builds, both successful.

```
$ drone build list playground/downstream
2
1
```

Thanks :).

**Comment by bradrydzewski** [comment]
> http://127.0.0.1:8090/api/stream/playground/downstream

This will receive a 404 if you don't include your auth token.

> I have put NGINX on the host in debug mode and watched the logs.

We should see something in the logs for an http POST to `/api/repos/:owner/:name/builds/:number`. If we don't see anything in the logs this means Drone isn't receiving the http request.

We use this plugin for some of our internal repositories. You can see an example here:
https://github.com/drone-plugins/drone-git-push/blob/master/.drone.yml#L36

The most recent push (5 days ago as of writing this) created this build:
http://beta.drone.io/drone-plugins/drone-git-push/28

This triggered the below builds. You will notice they all share the same timestamp after the above build, indicating the builds were successfully triggered by the plugin:
http://beta.drone.io/drone-plugins/drone-dotcloud/14
http://beta.drone.io/drone-plugins/drone-heroku/16
http://beta.drone.io/drone-plugins/drone-deis/17
http://beta.drone.io/drone-plugins/drone-cloudcontrol/14
http://beta.drone.io/drone-plugins/drone-azure-web-apps/17
http://beta.drone.io/drone-plugins/drone-scalingo/12

So let's assume there are no known issues with the downstream plugin. If we don't see anything in your logs can we be sure the network is setup correctly? I'm unable to reproduce so how should we proceed?

**Comment by valentinbud** [comment]
> Based on this error, and the fact that we don't seen anything in your nginx logs this has me wondering if there is a network configuration issue.

Indeed, NGINX wasn't receiving anything from the `drone_build_XX_notify` container. I don't remember where I've found the `server` configuration attribute for the downstream plugin. I have set up with the IP address of the drone container and exposed port 8000. 

`playground/init/.drone.yml`
```
publish:
    docker:
        username: $$DOCKER_USER
        password: $$DOCKER_PASSWORD
        email: $$DOCKER_EMAIL
        repo: playground/init
        tag:
            - latest
        insecure: true
        registry: registry.XXX.YYY

notify:
    downstream:
        repositories:
            - playground/downstream
        token: "$$DRONE_TOKEN"
        server: http://172.17.0.3:8000
        when:
            event: push
            branch: master
```

In order to avoid this kind of issues in the future would you recommend running the workers on other hosts separate from the host drone is installed in?

Can I customise the plugins and put them in a private repository so I can use them from there? I wouldn't want to do this but custom (CA) certificates and a couple of public ones that aren't included in ca-certificates force me to do this. 

Thank you very much for your patience and guidance :).
