### ISSUE TITLE
Different variable injection on conditions in build YAML stanza

### ISSUE THREAD

**Issue by desktophero** [drone/drone#1462]
First `n00b to Drone`. I'll jump into the code to see what I can see. I wanted to get an issue opened in parallel. Totally convinced it's something I'm doing! :smile: but perhaps this is an edge case.

Issue I am seeing is that when I have a build on `push`, environment variables inject correctly. When I apply a condition to add steps on a `pull_request`, the variable injection does not happen.

Note: the data below is mocked up based on the yml files I have

`.drone.yml`
```yaml
build:
  always_run:
    image: <image_name>
    commands:
      - export KEY_NAME="$$OS_KEY_NAME"
      - env | sort
  pull_requests:
    image: <image_name>
    when:
      event: pull_request
    commands:
       - export KEY_NAME="$$OS_KEY_NAME"
       - env | sort
```
`secrets.yaml`
```yaml
environment:
  - OS_KEY_NAME=BOOM_GOES_THE_DYNAMITE
```

Build log for `push` (`always_runs`):
```
$ env | sort
OS_KEY_NAME=BOOM_GOES_THE_DYNAMITE
```

Build log for `pull_request` (`pull_requests`):
```
$ env | sort
OS_KEY_NAME=7OS_KEY_NAME
```

In the `push` scenario (labeled `always_run`), all the environment variables are a-okay. In the `pull_request` condition (labeled `pull_requests`), the environment variables have that `7` (sometimes `8`, sometimes `9`) and then the name of the variable instead of the value.
