### ISSUE TITLE
Failed notification step for passing builds results in subsequent failure notifications

### ISSUE THREAD

**Issue by log0ymxm** [drone/drone#1474]
This is happening with the drone 0.4 docker image. The hipchat notifier sends updates to our hipchat room, but the build status is always posted as failed, regardless of the actual build status.

**Comment by log0ymxm** [comment]
![screen shot 2016-02-09 at 10 51 57 am](https://cloud.githubusercontent.com/assets/35297/12925375/3ba1b604-cf1b-11e5-8595-4166cb5a14bd.png)
![screen shot 2016-02-09 at 10 52 05 am](https://cloud.githubusercontent.com/assets/35297/12925376/3d9b515e-cf1b-11e5-958a-f34228a71aca.png)

**Comment by bradrydzewski** [comment]
cc @jackspirou

**Comment by bradrydzewski** [comment]
@log0ymxm also can you please post a full yaml with any sensitive data redacted?

**Comment by log0ymxm** [comment]
```yaml
cache:
  mount:
    - venv
    - .git
compose:
  database:
    image: mysql
    pull: true
    environment:
      - <env_vars...>
    volumes:
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
build:
  image: log0ymxm/django-docker
  commands:
    - <build-steps...>
notify:
  email:
    recipients:
      - <recipients>
    on_success: false
    on_failure: blame
  hipchat:
    auth_token: <token>
    room_id_or_name: Build
    notify: true
    when:
      success: true
      failure: true
      change: true
    template: >
      <strong>{{ uppercasefirst build.status }}</strong> <a href=\"{{ system.link_url }}/{{ repo.owner }}/{{ repo.name }}/{{ build.number }}\">{{ repo.owner }}/{{ repo.name }}#{{ truncate build.commit 8 }}</a> ({{ build.branch }}) by {{ build.author }} in {{ duration build.started_at build.finished_at }} </br> - {{ build.message }} {{#success build.status}} It works {{/success}}
```

I've got the template in there just so I could debug. The `build.status` is always failed.
