### ISSUE TITLE
Empty build.link_url when using slack notify plugin

### ISSUE THREAD

**Issue by PAStheLoD** [drone/drone#1493]
Hello!

We're using a pretty recent build (from the 0.4 docker image as of Febr 12, sha1sum of the binary is 28a17c00789731e469fc6715ad94b27f3972fda1), and even though I looked at the drone-plugins/drone-slack repository, but as far as I can tell, the link_url must be simply missing from or empty in the "build" structure, otherwise Template would do the right thing [there](https://github.com/drone-plugins/drone-slack/blob/9e64daf32da9d460d9b36204f0fefa331e21db96/main.go#L74), so it probably doesn't receive it from drone.

Could someone help me debug this?

**Comment by bradrydzewski** [comment]
can you please provide a re-producable example yaml?

**Comment by PAStheLoD** [comment]
.drone.yml:
```
...
notify:
  slack:
    webhook_url: 'http://hooks.slack.com/services/...'
    channel: '#frontend'
    username: drone
    on_started: true
    on_success: true
    on_failure: true
    template: |
      *{{ build.status }}* {{ repo.name }} {{ build.link_url }} ({{ build.branch }}) by {{ build.author }}
      {{{ build.message }}}
      Duration: {{ duration build.started_at build.finished_at }}
      {{ repo.link_url }}
      {{ repo.clone_url }}
      {{ system.link_url }}
      {{ system }}
      {{ repo }}
      {{ build }}
```

The caputed message:

```
*failure* admin-frontend  (master) by Some Guy


drone debug

Duration: 10s

https://git.some.where/someproject/admin-frontend
https://git.some.where/someproject/admin-frontend.git
http://ci.domain.tld

map[
    version:
    link_url: http://ci.domain.tld
    plugins: <nil>
    globals: <nil>
    privileged_plugins: <nil>
]
map[
    avatar_url:
    allow_pr: %!s(bool=true)
    allow_tags: %!s(bool=false)
    trusted: %!s(bool=false)
    allow_deploys: %!s(bool=false)
    owner: someproject
    name: admin-frontend
    link_url: https://git.some.where/someproject/admin-frontend
    clone_url: https://git.some.where/someproject/admin-frontend.git
    timeout: %!s(float64=60)
    allow_push: %!s(bool=true)
    id: %!s(float64=0)
    full_name: someproject/admin-frontend
    default_branch: master
    private: %!s(bool=true)
]
map[
  finished_at: %!s(float64=1.455676347e+09)
  deploy_to:
  refspec:
  timestamp: %!s(float64=0)
  author_avatar: https://www.gravatar.com/avatar/....jpg?s=128
  id: %!s(float64=0)
  number: %!s(float64=76)
  event: push
  link_url:
  enqueued_at: %!s(float64=1.455676337e+09)
  ref: refs/heads/master
  author_email: someguy@gmail.com
  created_at: %!s(float64=1.455676337e+09)
  commit:c8be058c267b2bca926ebb44dc04d6b53a65979c
  remote:
  title:
  message: drone debug
  author: Some Guy
  status: failure
  started_at: %!s(float64=1.455676337e+09)
  branch:master
]
  
"fallback": "failure someproject/admin-frontend#c8be058c (master) by Some Guy
```


Raw POST slack.com/service/... JSON (from tcpdump):

```
{"text":"","username":"drone","icon_url":"","icon_emoji":"","channel":"#frontend","unfurl_links":false,"attachments":[{"fallback":"failure someproject/admin-frontend#c8be058c (master) by XY ZW","text":"*failure* admin-frontend  (master) by XY ZW\ndrone debug\n\nDuration: 10s\n\nhttps://git.some.where/someproject/admin-frontend\nhttps://git.some.where/someproject/admin-frontend.git\nhttp://ci.domain.tld\nmap[version: link_url:http://ci.domain.tld plugins:\u0026lt;nil\u0026gt; globals:\u0026lt;nil\u0026gt; privileged_plugins:\u0026lt;nil\u0026gt;]\nmap[avatar_url: allow_pr:%!s(bool=true) allow_tags:%!s(bool=false) trusted:%!s(bool=false) allow_deploys:%!s(bool=false) owner:someproject name:admin-frontend link_url:https://git.some.where/someproject/admin-frontend clone_url:https://git.some.where/someproject/admin-frontend.git timeout:%!s(float64=60) allow_push:%!s(bool=true) id:%!s(float64=0) full_name:someproject/admin-frontend default_branch:master private:%!s(bool=true)]\nmap[finished_at:%!s(float64=1.455676347e+09) deploy_to: refspec: timestamp:%!s(float64=0) author_avatar:https://www.gravatar.com/avatar/....jpg?s=128 id:%!s(float64=0) number:%!s(float64=76) event:push link_url: enqueued_at:%!s(float64=1.455676337e+09) ref:refs/heads/master author_email: ....@gmail.com created_at:%!s(float64=1.455676337e+09) commit:c8be058c267b2bca926ebb44dc04d6b53a65979c remote: title: message:drone debug\n author:Some Guy status:failure started_at:%!s(float64=1.455676337e+09) branch:master]","pretext":"","color":"danger","fields":null,"mrkdwn_in":["text","fallback"]}]}
```
