### ISSUE TITLE
Builds hang in RUNNING state, TLS handshake error

### ISSUE THREAD

**Issue by ralfschimmel** [drone/drone#1506]
Hi,

Since a day or two we have a lot of builds which hang in the running state.
They complete, all steps of the build/deploy finish, but then it just hangs.

The logs show these as only error;

```
http: TLS handshake error from 10.104.1.60:52088: EOF
http: TLS handshake error from 10.104.1.60:52089: EOF
http: TLS handshake error from 10.104.1.60:54854: EOF
http: TLS handshake error from 10.104.1.60:54855: EOF
http: TLS handshake error from 10.104.1.60:57682: EOF
http: TLS handshake error from 10.104.1.60:57683: EOF
http: TLS handshake error from 10.104.1.60:60444: EOF
http: TLS handshake error from 10.104.1.60:60445: EOF
http: TLS handshake error from 10.104.1.60:34929: EOF
http: TLS handshake error from 10.104.1.60:34930: EOF
http: TLS handshake error from 10.104.1.60:37695: EOF
http: TLS handshake error from 10.104.1.60:37698: EOF
http: TLS handshake error from 10.104.1.60:40437: EOF
http: TLS handshake error from 10.104.1.60:40443: EOF
http: TLS handshake error from 10.104.1.60:43158: EOF
http: TLS handshake error from 10.104.1.60:43160: EOF
http: TLS handshake error from 10.104.1.60:45923: EOF
http: TLS handshake error from 10.104.1.60:45924: EOF
http: TLS handshake error from 10.104.1.60:48645: EOF
http: TLS handshake error from 10.104.1.60:48646: EOF
http: TLS handshake error from 10.104.1.60:51422: EOF
http: TLS handshake error from 10.104.1.60:51424: EOF
```

Drone runs in docker on Kubernetes (GKE).
All workers run on GCE and were added with docker-machine and the drone CLI.

Please advice.

Thanks, Ralf

```
build:
  image: quay.io/gynzy/docker-drone-node:test
  auth_config:
    username: $$QUAY_USER
    password: $$QUAY_PASS
    email: drone@gke.nl
  commands:
    - chmod 777 ./ci/*.sh
    - bash ./ci/modify-git-checkout.sh
    - bash ./ci/build.sh
    - bash ./ci/deploy.sh
```

<img width="1183" alt="screen shot 2016-02-25 at 18 06 04" src="https://cloud.githubusercontent.com/assets/414390/13327521/8b86ca5c-dbea-11e5-8d0c-dfc21d3877de.png">

**Comment by gtaylor** [comment]
How about a look at your k8s manifests, with the sensitive stuff masked out?

**Comment by ralfschimmel** [comment]
Sure, think I borrowed it from you ;-)

```
apiVersion: v1
kind: ReplicationController
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  replicas: 1
  selector:
    name: droneio
  template:
    metadata:
      labels:
        name: droneio
    spec:
      containers:
        - image: drone/drone:0.4
          name: droneio
          env:
            # HTTP Listen Address
            - name: SERVER_ADDR
              value: ":443"
            # HTTPS private key
            - name: SERVER_KEY
              value: /etc/secrets/key
            - name: SERVER_CERT
              value: /etc/secrets/cert
            # DB stuff
            - name: DATABASE_DRIVER
              value: sqlite3
            # This ends up being a mounted Google Cloud Disk.
            - name: DATABASE_CONFIG
              value: /var/lib/drone/drone.sqlite
            # RCS stuff
            - name: REMOTE_DRIVER
              value: github
            # TODO: Move these into secrets when supported.
            - name: REMOTE_CONFIG
              value: https://github.com?client_id=xxxx&client_secret=xxxx
          ports:
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            # Contains all config
            - mountPath: /etc/secrets
              name: droneio-secrets
              readOnly: true
            # Persist our configs in an SQLite DB in here
            - mountPath: /var/lib/drone
              name: droneio-sqlite-db
            # Enables Docker in Docker
            - mountPath: /var/run/docker.sock
              name: docker-socket
            - mountPath: /var/lib/docker
              name: docker-lib
      volumes:
        - name: droneio-secrets
          secret:
            secretName: droneio
        - name: droneio-sqlite-db
          gcePersistentDisk:
            pdName: drone-04-data
            fsType: ext4
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: docker-lib
          hostPath:
            path: /var/lib/docker
```

```
apiVersion: v1
kind: Service
metadata:
  name: droneio
  labels:
    name: droneio
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 443
  selector:
    name: droneio
  type: LoadBalancer
```

```
apiVersion: v1
kind: Secret
metadata:
  name: droneio
type: Opaque
data:
  key: BIGKEYBLOB
  cert: BIGKEYBLOB
```
