### ISSUE TITLE
wait / block plugin for others builds or jobs

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1512]
I've been kicking around the idea of a wait or block plugin. This would block the build until some sort of event happens related to other builds or jobs (matrix). These are some example use cases:
- wait until all other jobs in the matrix complete. This is useful when you have (let's say) a matrix build with 10 jobs and you want job 10 to deploy once the other 9 jobs are complete
- wait until all previously started builds complete before moving forward. This is useful when you have builds running concurrently and you don't want multiple deployments to execute concurrently

The initial implementation will need to be a plugin, which means it would be configured as a step in your pipeline just like any other Drone plugin. The plugin could use the Drone API to poll the server, blocking the pipeline until conditions are met.

This is an example of what the plugin could look like:

``` yaml
pipeline:
  build:
     ...
  test:
    ...
  wait:
    image: plugin/wait
    timeout: 10m
    for: [ 1.5, 1.6 ]
    where:
      environment:
        golang: 1.7

matrix:
  golang: [ 1.5, 1.6, 1.7 ]
```

The reason for building this as a plugin and not directly into Drone core is that teams will have different requirements for blocking and waiting. Our policy is pretty consistent that these sort of features need to be created as external plugins first, before we would consider adding the feature to Drone core.

I also want to set expectations that I have no plans to build this plugin myself. It is not a feature I personally need, and since anyone can build and publish their own plugin independently, there is no reason someone else can't build and publish to the [plugin index](http://plugins.drone.io). To learn more about creating plugins see http://readme.drone.io/plugins/creating-custom-plugins-bash/

**Comment by gtaylor** [comment]
I think something like this could be helpful, but the biggest thing I'll be looking to do in the coming era of the re-worked yaml is write a plugin that waits until service containers are fully started. So in a case like that, the most important thing for that usage case is:

* The ability to add an arbitrary container before the build step that can use my language/toolset of choice.

This is not really what you are talking about above, but I wanted to make sure that the other side of this was considered.

**Comment by bradrydzewski** [comment]
I updated the issue title and description to be a bit more specific. I'm not looking for a generic wait plugin, but instead looking for something that prevents this situation:

> How can I define that only a single deploy can run at a time. For example we merge multiple things into master quickly, this fires multiple deploys that run in parallel.

**Comment by thomasf** [comment]
I also want the pre build plugin stuff,  A couple of my builds needs to fetch some external resources before starting which would be great.

Maybe, just maybe it would be good to have a way to specify this as a graph via some sorts of tags?

```yaml
build:
  commands:
    - ./ci.sh runci
  wait:
    after: pgup  # wait until the pgup plugin finishes successfully

cache:
  mount:
    - node_modules

compose:
  database:
    image: postgres
    
  pgup:
    image: pg-up-watcher
    wait:
      name: pgup
      timeout: 10m

publish:
  drone-mvn:
    image: thomasf/drone-mvn
    
    when:
      branch: master

  drone-mvn:
    image: thomasf/drone-mvn

    when:
      event: tag

```

I don't know if this falls under the crazy flexible ultra-configurable queue system category or not :)

**Comment by constantm** [comment]
Any new thoughts on this? Things we could really use is limits per branch, and as you mentioned, limits for running deploys. Would love to help on the implementation but I'm going to have to learn Go first. :D

**Comment by bradrydzewski** [comment]
> Would love to help on the implementation but I'm going to have to learn Go first

Note that since this would be a plugin, there is no need to learn Go. Plugins can be written in any language, including bash. Check out http://readme.drone.io/plugins/creating-custom-plugins-bash/

**Comment by ozbillwang** [comment]
my user case is 

>I need to run `terraform plan` (dry-run, similar as ansible option --check) first, block/pause this pipeline, review the logs, if everything goes well, I'd like to click a confirm button or input y/n to run next step terraform apply to apply the change or give up. 

Another user case is, I'd like to block deployment if environment is production. So I can make sure the production changes are implemented in plan time.

**Comment by tonglil** [comment]
> wait until all previously started builds complete before moving forward. This is useful when you have builds running concurrently and you don't want multiple deployments to execute concurrently

This would be really useful. Currently we're planning to use/build an external system for locking.

**Comment by bradrydzewski** [comment]
I am going to close this for a few reasons ...

__First__ is this issues provides a design for a plugin (that anyone is welcome to build) to enable blocking and locking (below). I recommend using something like redis as the backend for such a plugin, since it has these semantics built-in.

```
pipeline:
  wait:
    image: plugin/wait
    timeout: 10m  # (or -1) wait forever
```

this is one solution to the second documented use case:

> wait until all previously started builds complete before moving forward.

as well as some comments above:

> Things we could really use is limits per branch, and as you mentioned, limits for running deploys

__Second__ we have an open issue for limiting the number of concurrent builds per-repository. This could be used an alternate to the above solution to throttle. See https://github.com/drone/drone/issues/758

this is another solution to the second documented use case:

> wait until all previously started builds complete before moving forward.

__Thrid__ matrix builds will likely change substantially once we have fan-in and fan-out enabled. It will effectively allow you to fan-out to multiple machines, test muliptle matrixes, and fan-in. This solves the first documented use case:

 > wait until all other jobs in the matrix complete

__Fourth__ we have an open issue for blocking the pipeline pending manual intervention at https://github.com/drone/drone/issues/2126. This solves the use case mentioned by @ozbillwang 

> I'd like to click a confirm button or input y/n to run next step terraform apply to apply the changes or give up.
