### ISSUE TITLE
Mail plugin not working?

### ISSUE THREAD

**Issue by cimm** [drone/drone#1516]
New to Drone here. I have Drone building my tests, the build fails (that has nothing to do with Drone :wink:) but there seems a problem with the notification mail. From the Drone Docker logs:

```
time="2016-03-05T22:14:17Z" level=info msg="Notification container drone_build_32_notify exited with 1" 
time="2016-03-05T22:14:17Z" level=info msg="[info] Pulling image plugins/drone-email:latest\nDrone Email Plugin built from 725e06f\ndial tcp 52.16.99.88:587: getsockopt: connection timed out\n[info] build failed (exit code 1)\n" 
time="2016-03-05T22:15:26Z" level=info msg="closed event stream" 
```

I never received a mail from my Drone instance. Using Mandrill as SMTP server on a Google Cloud instance.

```
notify:
  email:
    from: me@example.com
    host: smtp.mandrillapp.com
    port: 587
    username: me@example.com
    password: password
    recipients:
      - me@example.com
```

Is `52.16.99.88` where the plugins are hosted? Does Drone download the plugin when it sees a `notify` block in the YAML file? Or is the email plugin already present when I installed Drone?
