### ISSUE TITLE
Delegated secrets management

### ISSUE THREAD

**Issue by casualjim** [drone/drone#1538]
First off we're willing to do the work proposed, I wanted to share the approach and general idea first.
## Current state of affairs

Drone allows for encryption of secrets but it works locally and so the secrets yaml file needs to be shared amongst "blessed" team members who gate changes to .drone.yml.
## Expected behavior

Decouple and delegate managing secrets yaml content from the ability to encrypt drone.yml. Every maintainer should be able to encrypt the .drone.yml file. But the ability to add or change secrets should still be gated through a set of "blessed" individuals.
## Proposed approach

To achieve this we can introduce a secure secrets store like hashicorps vault, dockers notary, ... The backend might actually be pluggable, for a first pass I think hashicorps vault is most appropriate. 

The drone-cli will submit the .drone.yml file to the drone API server and gets the encryption string back. This then gets stored in .drone.sec. This can be a flag that allows people the choice but by default we stick to the current behavior of needing a local file.

The drone-api server needs to get a new endpoint to accommodate this new workflow. There will also be a config necessary so that the drone api server knows how to connect to the secure store backend.

The secrets are now provided through vault, so the people who can write or even read that are highly privileged accounts but this is decoupled from the build system.

**Comment by gtaylor** [comment]
I am a big supporter of pluggable secrets, but also feel like our default install story needs to stay single-container and as simple as humanly possible. This is a big part of Drone's success so far: You can set it up in no time.

You may have already accounted for this, but I think that it is especially important to preserve the current simple setup and operation, without requiring a separate Vault install.

**Comment by casualjim** [comment]
yep absolutely, the current way should continue to work as is. 

But when people need it they can change their deploy to use delegated secrets. Of course any ideas to make it simpler are more than welcome

**Comment by bradrydzewski** [comment]
@casualjim I definitely agree with an optional vault integration and I know @benschumacher is interested in this sort of functionality as well.

I have been writing a more detailed specification for improving secrets:
http://gogs.drone.io/libcd/specs/src/master/secrets.md

I was contemplating a slightly different approach that would include the vault credentials and paths inside the encrypted file. The secrets could be changed in vault without having to re-encrypt the file:

```
checksum:  688787d8ff144c502c7f5c

vault:
  host: foo.vault.com
  token: cf5b2a5c-a1bf-3a71-6d82-c162de34fb93

  docker:
    event: [ push, tag ]
    username: path/to/docker/username/in/vault
    password: path/to/docker/password/in/vault
```

I also considered using convention over configuration. Drone could look for secrets in vault using a defined path based on your repository name (ie /drone/octocat/hello-world/*). The path could then be used to recursively fetch all secrets that are children of that path. This means you could fully manage secrets without having to re-encrypt the file.

```
checksum:  688787d8ff144c502c7f5c

vault:
  host: foo.vault.com
  token: cf5b2a5c-a1bf-3a71-6d82-c162de34fb93
```

I just wanted to share some of the ideas I was kicking around as well. I'm not sure they solve some of the challenges you mentioned above, though
