### ISSUE TITLE
HELP: How to use variables in .drone.yaml

### ISSUE THREAD

**Issue by gembin** [drone/drone#1547]
I'm new to drone,  and I want to use variables documented in http://readme.drone.io/usage/variables,
I want to pass  `CI_BUILD_DIR` to docker build.  But the variable is not expanded.
What's the right way to use the variables ? Thanks!

.drone.yaml
```yaml
publish:
  docker:
    registry: my_private_registry
    repo: my_private_registry/test_image
    tag: $$BRANCH
    file: Dockerfile
    build_args:
     - CI_BUILD_DIR=$$CI_BUILD_DIR
```

Dockerfile
```Dockerfile
#...
ARG CI_BUILD_DIR
RUN mkdir /usr/share/app
COPY ${CI_BUILD_DIR}/target/app-1.0.0.jar /usr/share/app/
#...
```
