### ISSUE TITLE
Testing API (Golang) in Drone 

### ISSUE THREAD

**Issue by sh0umik** [drone/drone#1559]
I think is Docker inside Docker situation . I could not manage to find any solution . I need to test my RESTApi inside drone . So for this i have to run the server first then mock the endpoint . I have tried many way but could not seem to run the service and then run the test .. Just want to run the server as a service container for the api to appear then run test on this .

I have tried this . 

```
clone:
  path: github.com/app/auth-test-drone
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=auth
  redis:
    image: tutum/redis
    environment:
      - REDIS_PASS=pass
  api:
    image: golang
    environment:
      - EXPOSE_PORT=:6201
      - DB_1_PORT_5432_TCP_ADDR=localhost
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=auth
      - REDIS_PORT_6379_TCP_ADDR=localhost
      - REDIS_PORT_6379_TCP_PORT=6379
      - REDIS_PASS=pass
    commands:
      - go get ./...
      - go run server.go run
    privileged: true

build:
  image: golang
  environment:
    - EXPOSE_PORT=:6201
    - DB_1_PORT_5432_TCP_ADDR=localhost
    - POSTGRES_PASSWORD=pass
    - POSTGRES_USER=user
    - POSTGRES_DB=auth
    - REDIS_PORT_6379_TCP_ADDR=localhost
    - REDIS_PORT_6379_TCP_PORT=6379
    - REDIS_PASS=pass
  commands:
    - go get ./...
    - go test -v

```

I tried to run API as a service container because my test needs them . like database . So far service container database and redis works well but i think my api is not running in the background .

Api test failed because it could not find the api route .
