### ISSUE TITLE
GitHub tag hook is ignored

### ISSUE THREAD

**Issue by gabro** [drone/drone#1585]
Hi,
I'm trying to setup a tag hook on a GitHub repo, but it gets ignored.

My `.drone.yml` is

```yaml
build:
  mailo:
    image: hseeberger/scala-sbt
    commands:
      - openssl cast5-cbc -d -in src/test/resources/application.conf.cast5 -pass pass:$$TEST_CREDENTIALS_PASS -out src/test/resources/application.conf
      - sbt test -Dsbt.ivy.home=/drone/.ivy

  publish:
    image: hseeberger/scala-sbt
    environment:
      BINTRAY_CREDENTIALS_FILE: './.bintrayCredentials'
    commands:
      - echo 'realm = Bintray API Realm' >> .bintrayCredentials
      - echo 'host = api.bintray.com' >> .bintrayCredentials
      - echo 'user = $$BINTRAY_USERNAME' >> .bintrayCredentials
      - echo 'password = $$BINTRAY_PASSWORD' >> .bintrayCredentials
      - echo 'bintrayCredentialsFile := new File(".bintrayCredentials")' >> build.sbt
      - sbt publish -Dsbt.ivy.home=/drone/.ivy
    when:
      event: tag

cache:
  mount:
    - /drone/.ivy
```

The server logs

> "ignoring hook. yaml file excludes repo and branch buildo/mailo refs/tags/0.1.0"

which comes from

https://github.com/drone/drone/blob/v0.4.0/controller/hook.go#L163

However I've no branch filters in place, so this is odd.

Any idea?
