### ISSUE TITLE
Support pre-script stanza which caches to a docker image?

### ISSUE THREAD

**Issue by wrouesnel** [drone/drone#1609]
Given the heavy use of docker by drone, it might be an idea to support running a "pre-build" stanza similar to how travis-ci does, but take advantage of the docker nature of it by treating the pre-build section as a dockerfile which should be built and cached by drone (possibly pushed to a global repository?)

This would allow a tighter and easier specification of the build environment when it differs in only minor ways from the upstream image and would only need to be rebuilt when it changed.

**Comment by bradrydzewski** [comment]
I think there are quite a few options to achieve this today.

there are plugins for caching build artifacts:
http://readme.drone.io/usage/caching/

you can use caching plugins to cache the directory where docker stores its image layers. This is only available in the develop branch of the docker plugin:
https://github.com/drone-plugins/drone-docker/tree/develop

alternatively you could have a step that mounts the host machines docker daemon and builds the container as needed:

```
build:
  setup:
   image: docker
   commands:
     - docker build -t {some_image_name}
   volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  compile:
    image: {some_image_name}
    commands:
      - go build
      - go test
```

lastly the drone.yml is being revised and will be a superset of the docker compose yaml file. This will eventually lead to the ability to use the `build` directive to build an image which is then used throughout your build process. This could, depending on the implementation, take advantage of layer caching as well but it is a bit too premature to really even speculate. The techincal requirements are outlined at https://github.com/drone/drone/issues/1531

```
build:
  context: .
image: foo

script:
  build:
    image: foo
    commands:
      - go build
      - go test
  slack:
    image: slack
    channel: foo
```

**Comment by fooker** [comment]
I would like to have this feature, too. This would help in cases where the build task can be done using an image available in the registry but this image needs some small changes like installing one or two additional packages. It would be nice to have something like the following:

```
pipeline:
  build:
    image:
      base: golang:latest
      commands:
        - apt install libfoo-dev
    commands:
      - go get
...
```

The commands in `pipeline.image.commands` will be cached using the docker image cache.

Are patches for something like this welcome during the current state of development?

**Comment by bradrydzewski** [comment]
The proposed syntax for this feature is based on the docker-compose [build](https://docs.docker.com/compose/compose-file/compose-file-v2/#build) section. Note that since drone is a superset of docker-compose the bar for introducing new syntax is high. In this case the existing syntax should be sufficient.

```diff
+build:
+  context: .
+  image: foo

script:
  build:
    image: foo
    commands:
      - go build
      - go test
  slack:
    image: slack
    channel: foo
```

Note that we will have to take security into account to prevent a malicious author from overwriting trusted images cached on the host machine. This would need to be done by aliasing the image name at runtime.

**Comment by bradrydzewski** [comment]
Until we have an official solution, this comment documents a possible workaround.

This can be achieved by building the image in your pipeline on the host machine. Note that you will need to mount the host machine docker socket as a volume (see the [docs](http://docs.drone.io/docker-volumes/) for more details)

```yaml
pipeline:
  setup:
    image: docker
    commands:
      - docker build --rm -t foo/bar:baz .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  build:
    image: foo/bar:baz
    commands:
      # commands here
```
