### ISSUE TITLE
How to mount base container directory into service container

### ISSUE THREAD

**Issue by nodesocket** [drone/drone#1652]
Is there a way to mount the base build containers _(where we do git clone)_ directory into a service container?

I.E. we run NGINX in a service container, but it needs some static files that live in the base container.

**Comment by bradrydzewski** [comment]
Yep! the service containers share the `/drone` mount path and have access to your source. I use this capability in one of my [projects](https://github.com/drone/drone-node/blob/master/.drone.yml). If you look at the below sample I create a sqlite3 database and populate with data in the build section, and then start a service container that reads this database

```
build:
  image: node:5.0.0
  commands:
    - sqlite3 -init test/data.sql /drone/test.db
    - npm install
    - npm run test

compose:
  drone:
    environment:
      - DATABASE_CONFIG=/drone/test.db
```
