### ISSUE TITLE
Partial builds from a single branch

### ISSUE THREAD

**Issue by picrin** [drone/drone#1688]
I'll be using drone to build about 50 **different** docker images from one repository. Dockerfiles and other things are going to live in 50 separate directories. Understandably I'd prefer if drone didn't build all 50 Dockerfiles **every time** I push to master. Instead I could see two possible solutions: Drone detects which **paths** changed in the most recent commit and builds only relevant Dockerfiles, or Drone allows me to build on **tags** (rather than branches), so I can tag a commit with relevant component-specific tag, and build **only** that component. Is either scenario supported?

- [yes] I have searched for existing issues
- [yes] I have discussed the issue with the community at https://gitter.im/drone/drone
- [dna] I have provided a sample `.drone.yml` file to help the team reproduce
- [dna] I have provided details from the build logs
- [dna] I have provided details from the server logs by running `docker logs drone`
- [yes] I am not using the issue tracker to ask why my build failed

**Comment by bradrydzewski** [comment]
> Drone detects which paths changed in the most recent commit and builds only relevant Dockerfiles

the yaml file is parsed and evaluated prior to drone cloning the repository. This is unfortunately not possible the way drone is architected, and there are no intentions to re-architect at this time.

> Drone allows me to build on tags (rather than branches)

drone supports conditional steps based on tags so this is possible today. You can also disable builds for branches (in the UI) if you only want to build tags:

```
publish:
  docker:
    when:
      repo: foo
      file: bar/Dockerfile
      tag: foo
  docker:
    repo: bar
    file: bar/Dockerfile
    when:
      tag: bar
```

lastly drone converts your build commands to a simple shell script. So in essence, anything you can do with shell you can do with drone. You could easily create a shell script that is invoked in your build section:

```
build:
  image: docker
  commands:
    - ./build.sh
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

note that in the above example we mount the host machines docker daemon so that the build has access to docker. to mount a volume your repository must be run in trusted mode (enabled by a drone admin in the UI)

then you shell script could do something like this:

```
#!/bin/sh

# calculate dirs that changes
...

# loop through dirs and build
for ...; do
  docker build ...
  docker push ...
done
```
