### ISSUE TITLE
Eval script for excluding build steps

### ISSUE THREAD

**Issue by vespakoen** [drone/drone#1696]
Hi, as discussed on gitter, it would be nice to be able to customise what build steps to exclude / include.
For example, I am using "monorepo's", basically having all code in one big fat repository, and would like to be able to exclude build steps based on the code that has changed in a commit.

The syntax @bradrydzewski proposed was:

``` yaml
pipeline:
  build:
    commands: ...
    when: 
      eval:
        image: busybox
        script: ./build.sh
```

Unfortunately my golang knowledge is only a week old so I will not be able to implement this, hopefully somebody else will take a stab at this.
