### ISSUE TITLE
[Feature Request] Enforce builds to be run by specific agents

### ISSUE THREAD

**Issue by mccricardo** [drone/drone#1726]
On Drone 0.5, Agents connect to the the Server polling the queue for pending builds. There's currently no support for _enforcing_ which agent (or group of agents) should run the build.

This could be achieved by:
 - environment variable with some information (eg. **tags**) to be passed to the agent on start;
 - **.drone.yml** constraint that would match the above information and run build. For example:

```
pipeline:
  build:
    image: some_image
    commands:
      - do something
    when:
      - tag: some_tag
```
