### ISSUE TITLE
Expose pipeline steps and current step as env vars

### ISSUE THREAD

**Issue by devth** [drone/drone#1740]
Given a pipeline like:

``` yaml
pipeline:

  test:
    image: gcr.io/foo/cd:latest
    runner: sbt

  publish:
    image: gcr.io/foo/cd:latest
    username: ${REGISTRY_USERNAME}
    password: ${REGISTRY_PASSWORD}
    email: ${REGISTRY_EMAIL}

  deploy_dev:
    when:
      branch: master
    image: gcr.io/foo/cd:latest
    credentials: ${CREDENTIALS}
```

I'd like to be able to access the name of the pipeline step inside my custom plugin in addition to all the other [good stuff available](http://readme.drone.io/0.5/usage/environment/).

e.g. during the `test` step, there could be a `DRONE_STEP=test` env var (or `DRONE_STAGE` or `DRONE_PHASE` or whatever the correct term is).

Also useful would be a list of all steps that will be run, e.g. `DRONE_PIPELINE=test,publish,deploy_dev`
