### ISSUE TITLE
[Drone 0.5] images not found in docker main repository unless prefixed with library/~

### ISSUE THREAD

**Issue by dcerecedo** [drone/drone#1787]
This results in an `ERROR: Image not found`
  ```
pipeline:
  build:
    image: maven:3-jdkd-8
    mount:
      - repository
    commands:
     - mvnclean install

```
This only works if you use the fully qualified image name:
```
      image: library/maven:3-jdkd-8
```

**Comment by bradrydzewski** [comment]
the sample yaml has a typo which resulted in an image not found error when I tried to copy paste your example. I fixed the typo and then it worked fine

```diff
-image: maven:3-jdkd-8
+image: maven:3-jdk-8
```

Noe that drone does not require a `library` prefix. Drone uses the official `golang` images, for example, in its yaml file without issue:

```

pipeline:
  backend:
    image: golang:1.6
```

Based on my successful testing once the typo was resolved, I'm going to close this issue. Please note that in the github issue template we ask that all problems are triaged at https://gitter.im/drone/drone before opening an issue. Feel free to use the channel next time you have questions. Thanks!

**Comment by dcerecedo** [comment]
The typo is in the sample I provided not the actual image I used. How can I check that we are running the same Drone server? 
Images drone/drone:0.5 and drone/drone:latest are different. Which one should I use?

**Comment by bradrydzewski** [comment]
> So more than probable the differences we see in the two tickets I have opened may be because you are on drone:latest and I'm on drone:0.5?

I am running the latest `drone/drone:0.5` which is the latest version `0.5.0+704`

I'm not sure the version is relevant here because `latest`, `0.4.*`, and `0.5.*` are all able to use library images without the library prefix. I am certain about this because we have been using the library images for 50+ official drone repos for the past 18 months without using the prefix and without any problems.

I recommend checking your docker deamon logs to see what is happening. You can also use `docker events` to monitor all docker daemon system-level events, which could provide additional information to help you debug.

**Comment by dcerecedo** [comment]
I think that the problem comes from the yml.
This works
```
pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount: [repository]
    server: myserver
    username: mysuers
    password: mypassword
    path: /home/deployment/cache/repository
  build:
    image: maven:3-jdk-8
    commands:
     - if [ -d "/drone/repository" ]; then cp -a /drone/repository /usr/share/maven/ref ; fi
     - mvn -Ddocker.skip=true clean install
     - cp -a /usr/share/maven/ref/repository /drone
  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount: [repository]
    server: myserver
    username: myuser
    password: mypassword
    path: /home/deployment/cache/repository
```

Whereas this gives the Image not found error:

```
pipeline:
  sftp_cache:
    image: plugins/sftp-cache
    restore: true
    mount:
      - repository
    server: myserver
    username: mysuers
    password: mypassword
    path: /home/deployment/cache/repository
  build:
    image: maven:3-jdk-8
    mount:
      - repository
    commands:
     - if [ -d "/drone/repository" ]; then cp -a /drone/repository /usr/share/maven/ref ; fi
     - mvn -Ddocker.skip=true clean install
     - cp -a /usr/share/maven/ref/repository /drone
  sftp_cache:
    image: plugins/sftp-cache
    rebuild: true
    mount:
      - repository
    server: myserver
    username: myuser
    password: mypassword
    path: /home/deployment/cache/repository
```

I had to remove the mount command in the build step and change format in the caches.
