### ISSUE TITLE
Conditional steps with value ending on "0" aren't executed

### ISSUE THREAD

**Issue by MorrisJobke** [drone/drone#1792]
- having an environment variable with an value that ends on `0` - i.e. `7.0`
- using this env variable in a `when`statement for a step
- setup a failing command to check that the step is actually executed
- actual: the step is not executed
- expected: the step is executed

To verify that the drone.yml works as expected I did a second step with a different value - `7.1` in this case and placed the same failing command in there. Regarding to the example files below the first step (example) should cause a failure for the first matrix entry and the second (example2) one for the second matrix entry, but only the second one is actually failing.

I tested this with 0.4 and 0.5. 

Drone 0.4 example drone.yml:

``` yaml
build:
  example:
    image: php
    commands:
      - exit 1
    when:
      matrix:
        PHP: 7.0
  example2:
    image: php
    commands:
      - exit 1
    when:
      matrix:
        PHP: 7.1


matrix:
  PHP:
    - 7.0
    - 7.1
```

Test execution see failed build in https://github.com/MorrisJobke/test/pull/6

![bildschirmfoto 2016-09-12 um 01 21 29](https://cloud.githubusercontent.com/assets/245432/18421343/b41570dc-7888-11e6-912e-1727dc6f1672.png)

Drone 0.5 example drone.yml:

``` yaml
pipeline:
  example:
    image: php
    commands:
      - exit 1
    when:
      matrix:
        PHP: 7.0
  example2:
    image: php
    commands:
      - exit 1
    when:
      matrix:
        PHP: 7.1


matrix:
  PHP:
    - 7.0
    - 7.1
```

Test execution see failed build in https://github.com/MorrisJobke/test/pull/5

![bildschirmfoto 2016-09-12 um 01 21 43](https://cloud.githubusercontent.com/assets/245432/18421339/ac2367bc-7888-11e6-93d6-469a3a50326a.png)

I also tested if this is maybe caused by the matrix population (https://github.com/drone/drone/blob/master/yaml/matrix_test.go) or by the constraint logic (https://github.com/drone/drone/blob/master/yaml/constraint_test.go) and adjusted the tests accordingly, but sadly this was just fine and works very well with values ending on `0`. (Should I submit those working tests as additional tests or are they not needed?)

**Comment by bradrydzewski** [comment]
I'm not sure where (it could be in the yaml parser for all I know) but somewhere the `7.0` string is getting parsed as an integer which when converted to a string drops the decimal and returns `7`. You can quote the string to prevent this:

```
    when:
      matrix:
        PHP: "7.0"
```

**Comment by MorrisJobke** [comment]
This workaround works. 

I found out following:

- :x: doesn't work
```
pipeline:
  example:
    ...
    when:
      matrix:
        PHP: 7.0
matrix:
  include:
    PHP: "7.0"
```


- ✅  works
```
pipeline:
  example:
    ...
    when:
      matrix:
        PHP: "7.0"
matrix:
  include:
    PHP: 7.0
```

So this seems to be in parsing the `when` statement. How could I try to debug this further?
