### ISSUE TITLE
RFC add runtime or local=true condition to yaml

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1806]
Running plugin steps from the command line isn't very intuitive in 0.5. I've been kicking around the idea of adding a condition to the yaml to specify a step should be executed locally. It could look something like this:

```
pipeline:
  build:
    ...
  publish:
   ...
  notify:
    image: plugins/slack
    when:
      runtime: [ "local", "server" ]
```

or perhaps something more simple:

```
  notify:
    image: plugins/slack
    when:
      local: true
```

I guess it comes down to whether or not we think there will be multiple runtimes, or just command line and server runtimes. Open to suggestions or alternatives.

**Comment by tboerger** [comment]
IMHO local should be enough, but the runtime approach is more future oriented if we find another option

**Comment by bradrydzewski** [comment]
pull request to implement this feature https://github.com/drone/drone/pull/1910

```diff
pipeline:
  build:
    image: golang:1.6
    commands:
      - go build
      - go test
  notify:
    image: plugins/slack
    channel: dev
+   when:
+     local: false
```

Note that this change makes an important behavior adjustment to drone. It runs all steps locally unless you instruct it not to do so. I think this is more intuitive for new-comers.

For example, imagine this is the first time you see drone. You have no pre-conceived notion of how drone works. You run `drone exec` for the below Yaml file:

```
pipeline:
  build:
    image: golang:1.6
    commands:
      - go build
      - go test
  notify:
    image: plugins/slack
    channel: dev
```

What behavior would you assume, as a new drone user?

1. that `drone exec` will execute both commands locally
2. that `drone exec` will only execute the first command, because plugins aren't executed locally by default

I'm guessing you will assume the first, although maybe I'm wrong? The goal here is to take some of the remaining rough edges and magic (I consider this behavior magic) and remove from Drone so we can begin to start thinking about a stable, 1.0 release.

Note that you will still be able to prevent steps from running locally. You will just need to add the below constraint to the step in your yaml file:

```diff
notify:
  image: plugins/slack
  channel: dev
+ when:
+   local: false
```

Also note if you accidentally execute a plugin step locally it probably won't be a big deal. This is because most (all?) plugins require credentials to do anything useful. So accidentally running a plugin step will probably just fail the local build and exit right way, no hard done ...
