### ISSUE TITLE
Arbitrary Agent environment variables

### ISSUE THREAD

**Issue by gillesdemey** [drone/drone#1808]
We're using a Kubernetes setup to provision our agents with a couple of environment variables that  every agent needs (NPM registry credentials, Docker registry, etc.) with [Kubernetes secrets](http://kubernetes.io/docs/user-guide/secrets/).

`deployment.yml`

``` yaml
- name: NPM_CONFIG_REGISTRY
   value: https://my-registry.com/
- name: NPM_CONFIG_TOKEN
   valueFrom:
   secretKeyRef:
     name: npm-private-registry
     key: token
...
```

It'd be great if we could use these environment variables in the `.drone.yml` file to avoid having to use yet another secret store (in this case, drone's secrets database) by using the environment variable from the agent using regular YAML interpolation.

`.drone.yml`

``` yaml
environment:
  NPM_CONFIG_REGISTRY: https://my-registry.com/
  NPM_CONFIG_TOKEN: ${NPM_CONFIG_TOKEN}
...
```

**Comment by tboerger** [comment]
I think another approach should be much better. On long term the secrets store should be expandable so that it can be based on vault or even on Kubernetes secrets instead of a workaround via environment variables.

**Comment by bradrydzewski** [comment]
@gillesdemey the only (slight) problem with using the kubernetes secret store is it lacks some additional meta-data required by drone. Drone stores secrets with `--image` and `--event`. For example you can say `--image=plugins/slack` which tells drone only to provide secrets to the slack plugin, and `--event=push` to only enable secrets for push hooks (and to therefore disable for pull requests).

Without the `--image` and `--event` flags secrets would be injected into all containers for all events. This gives attackers the ability, for example, to send a malicious pull request that attempts to expose your secrets.

So I definitely understand the desire to put secrets in one place, but at the same time we need to ensure that we can do so in a way that prevents these sort of attack vectors.

**Comment by paultiplady** [comment]
You can store arbitrary metadata in any Kubernetes object (including Secrets), under the top level `metadata` key. If you want to be able to select the object based on the metadata, use `metadata.labels`. If you don't want to be able to select on it, use `metadata.annotations`.

https://kubernetes.io/docs/user-guide/annotations/

In this case `labels` seems like the right approach, so you'd want something like 


```
apiVersion: v1
kind: Secret
data:
  foo: LS0t
metadata:
  name: drone-secret
  labels:
    drone.io/image: plugins/slack
    drone.io/event: push
type: Opaque
```

And then the build pipeline can compile a list of secrets that apply to a build step based on those label selectors.
