### ISSUE TITLE
Terminal output cut off when using conditional tags

### ISSUE THREAD

**Issue by csinge** [drone/drone#1809]
The build log and example drone file are here
https://gist.github.com/csinge/80cc2c3800435fbdb58e02d7c29499ce

I have to put together a sample drone file that is not displaying all of command outputs.  In particular the command that is actually failing.  

It only appears to be an issue when the conditional tag is being used by a subsequent build step.  Removing this extra build step, the output is correct.  Furthermore running drone exec locally gives the expected output.

**Comment by csinge** [comment]
Hi All, is there anything else I need to do, to get the balls rolling

**Comment by bradrydzewski** [comment]
I'm unable to repeat. I created a similar yaml and the existence of tags do not impact the output. This is the sample yaml I used:

```
pipeline:
  example:
    image: golang:1.6
    commands:
      - echo hello
      - sleep 5
      - echo "This will fail but not been seen because of the when tag below" && exit 1
  run_node_build1:
    image: golang:1.6
    commands:
      - echo hello
      - sleep 5
    when:
      event: tag
```

and this is the output I received.

<img width="678" alt="screen shot 2016-10-28 at 12 14 12 am" src="https://cloud.githubusercontent.com/assets/817538/19788937/8642a2ee-9ca3-11e6-9c3f-016f499f3ccf.png">

having written the code, I can also say the `when` clause does not in any way impact the prior steps execution. This is because the yaml is "compiled" before being executed, and if your build is not a tag, that entire step is removed anyway, and is never encountered by the runtime
