### ISSUE TITLE
Setting repo timeout

### ISSUE THREAD

**Issue by timka** [drone/drone#1839]
I'm running 0.4.2 Docker image on SQLite.

When I update my repo's timeout I can see a PATCH request in browser console log. The response is 200 but its payload holds the old timeout value and the slider is still showing my new value.

Since the issue's not been reported before I suspect it has something to do w/ SQLite storage.

And here's how my docker-compose.yml looks like:

```
version: '2'
services:
  drone-server:
    image: drone/drone:0.4.2
    container_name: "drone"
    ports:
      - "8000:8000"
    volumes:
      - drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DATABASE_DRIVER: sqlite3
      DATABASE_CONFIG: /var/lib/drone/drone.sqlite
      REMOTE_DRIVER: github
      REMOTE_CONFIG: "https://github.com?client_id=…&client_secret=…&open=true&orgs=…"

volumes:
  drone:
```
