### ISSUE TITLE
Commit author email missing in environment with bitbucket provider

### ISSUE THREAD

**Issue by patrickjahns** [drone/drone#1860]
The environment variable `DRONE_COMMIT_AUTHOR_EMAIL` is not provided when using bitbucket as resource provider

Simple .drone.yml to reproduce / verify
```
pipeline:
  build:
    image: golang
    commands:
      - env
```

I will try to implement this and provide a PR then
