### ISSUE TITLE
Proposal: Pluginspecific secrets management

### ISSUE THREAD

**Issue by tboerger** [drone/drone#1888]
The current implementation of the secrets already works pretty well, but if you got more complex build pipelines it gets much more difficult because you want to publish to different environments or different docker registries depending on the environment.

## Scenario

If we take a docker image publishing as an example, you want to push a docker image for every pull request to a private registry, and all tags to the docker hub, today you end up with something like that:

```
pipeline:
  docker-tag:
    image: plugins/docker
    repo: foo/bar
    tags: [ '${TAG}' ]
    when:
      event: [ tag ]
      branch: [ refs/tags/* ]

  docker-pr:
    image: plugins/docker
    environment:
      DOCKER_USERNAME: $PRIVATE_DOCKER_USERNAME
      DOCKER_PASSWORD: $PRIVATE_DOCKER_PASSWORD
      DOCKER_EMAIL: $PRIVATE_DOCKER_EMAIL
    repo: foo/bar
    tags: [ 'pr-${DRONE_PULL_REQUEST}' ]
    when:
      event: [ pull_request ]
```

If you want to add more scenarios you always have to add more secrets with a different variable name that have to be mapped within the `environment:` block.

## Solution

I would suggest to add another flag to the secrets command like `--name` or `--plugin` which defines the name of the plugin step additionally to `--event` and `--image`, that way you can define multiple times environment variables like `DOCKER_PASSWORD` for the same `image` but for different pipeline steps.

## Problems

1) Currently we are building the identifier of the secret based on `repository` + `variable name`, this needs to be extended to `repository` + `variable name` + `pipeline step`
2) We need to differentiate between a secret added including `--name` attribute and excluding it, IMO a secret including the `--name` attribute would override the secret excluding this flag
3) Deleting a secret via `drone rm foo/bar DOCKER_PASSWORD` is potentially not precise enough to match a single secret record, there we can return a list of matches and the user of the cli can decide which one should be deleted or we just return a useful error that complains about too much matching records.
4) Keep backward compatibility, this is a pretty important part because it's handling secrets that never have to be exposed to the wrong people. To keep it backward compatible I would take a default of a wildcard for the `--name` flag.

## Suggestions

Do you have any further suggestions? Or maybe you got even a better idea how to handle that?

**Comment by bradrydzewski** [comment]
@tboerger thanks for taking the time to write the specification!

> Keep backward compatibility, this is a pretty important part because it's handling secrets that never have to be exposed to the wrong people. To keep it backward compatible I would take a default of a wildcard for the --name flag.

This is also important because most people won't require the functionality described in this proposal (myself included). So this feature should not add any additional burden or complexity to those that do not require it. I think the default wildcard should suffice here.

**Comment by bradrydzewski** [comment]
> return a useful error that complains about too much matching records.

I prefer the error message, since it is more simple

**Comment by bradrydzewski** [comment]
> We need to differentiate between a secret added including --name attribute and excluding it, IMO a secret including the --name attribute would override the secret excluding this flag

I would prefer to avoid secret selection and ranking. I believe this feature will be used by a minority of users, and this edge case described here will impact an even smaller subset. Creating ranking logic seems like overkill until we know it is a real problem. I would rather document that people should avoid using `--name=*` and `--name={step}` for the same secret.

**Comment by vaijab** [comment]
Doesn't this contradict the fact that we explicitly trust plugins with our secrets?

**Comment by bradrydzewski** [comment]
> Doesn't this contradict the fact that we explicitly trust plugins with our secrets?

This proposal shouldn't change that secrets are explicitly tied to plugin images. This would allow us to further refine our logic (optionally) to also restrict secrets by step name.

Consider the following Yaml:

```yaml
pipeline:

  development:
    image: plugins/heroku
    app: dev.foo.com
    when:
      branch: master
      event: push

  production:
    image: plugins/heroku
    app: prod.foo.com
    when:
      event: tag
```

This would use the same secret for both steps:

```
--image=plugins/heroku HEROKU_SECRET foo
```

This would allow us to further refine and limit the secret individual steps. This solves the issue where we potentially want to use different secret values for different steps, even though the plugin image is the same:

```
--image=plugins/heroku --name=production  HEROKU_SECRET foo
--image=plugins/heroku --name=development HEROKU_SECRET bar
```

**Comment by vaijab** [comment]
Understood. I believe this feature is a nice to have, but after using and supporting drone in a rather large scale environment, I have never seen anyone asking for this or something similar. Of course, that does not mean all users think the same way.

**Comment by tboerger** [comment]
I had this requirement already multiple times if the credentials are different. Currently I can only work around that with the mentioned environment block, but that's not really optimal.

**Comment by tboerger** [comment]
That should be another solution but requires touching of every plugin where somebody needs different credentials

**Comment by tboerger** [comment]
Beside that it gets pretty complicated to add dynamic environment variables to the cli lib

**Comment by bradrydzewski** [comment]
@tboerger yes, true

I've been thinking about maybe simplifying secrets, and combining aspects of the 0.4 and 0.5 implementation. I think we can keep the below commands for managing secrets from the command line:

```
drone secret add octocat/hello-world DOCKER_USERNAME foo
drone secret add octocat/hello-world DOCKER_PASSWORD bar
drone sign octocat/hello-world
```

We remove the --image flag

```diff
-drone secret add --image=plugins/docker octocat/hello-world DOCKER_USERNAME foo
+drone secret add octocat/hello-world DOCKER_USERNAME foo
```

We inject secrets into the Yaml similar to 0.4

```yaml
pipeline:
  build:
    image: golang
    commands: [ go build, go test ]
  docker:
    image: plugins/docker
    repo: foo/bar
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
```

I think we can do this is a way that supports backward compatibility to avoid breaking everyones build configurations with the change. We can address this in a more official proposal.

So why do I propose this change? I have been discussing with @donny-dont and we both agree that the new secret implementation is too complex and results in end-user confusion and frustration, in addition to support burden.

The existing implementation is also not flexible enough for using different secrets with the same name for different steps. The proposed fix makes complete sense, but also adds more complexity to something that is already complex. I don't think it is a problem with @tboerger's proposal, but with our underlying secrets implementation.

So this is why I'm thinking of simplifying a bit. We should also provide the ability to manage secrets in the user interface in order to improve the UX.

So what are the drawbacks to this combined approach?

* Lose the ability to only expose secrets to individual images
* We are making changes when we need stability (this can be mitigated by deprecating --image but still supporting it going forward)

This is just an idea. I'm open to other proposals for simplification based on real world feedback. I'm interested if @donny-dont and @jmccann have seen their co-workers experiencing issues with secrets and if they had any thoughts for simplification.

I'm not going to do anything rash here, and won't break the existing feature, so don't worry :)
