### ISSUE TITLE
Limit step execution from CLI

### ISSUE THREAD

**Issue by olymk2** [drone/drone#1894]
Not sure on how, but it would be nice to see a way of running a specific set of commands.

drone exec will run all tests, but my drone.yaml contains distinct sets ie.

unit and selenium tests so some kind of grouping and way to select a group of commands so i caould run just the unit tests. 

open to other ideas or anything that might already exist, currently I am running my drone tests from emacs but it runs unit and selenium tests and takes an age so a way to run just the unit tests would be ideal.

**Comment by tboerger** [comment]
The `drone exec` command got the `--plugin` flag which takes the pipeline step name as a parameter to define which steps are getting executed.

**Comment by olymk2** [comment]
@tboerger so for example I can do this example to have a second set of commands ?

```
pipeline:
  build:
    image: golang
    commands:
      - go build
      - go testselenium
  build2:
    image: golang
    commands:
      - go build
      - go testunit
```

```
drone exec --plugin build2
```

**Comment by jmccann** [comment]
I don't think you can do that.  I've seen use cases where we want to control specific `steps` to run instead of just having all of them run.  You get that control with `--plugins` for plugins but nothing I know of currently to control `steps`.

**Comment by olymk2** [comment]
yeah that's what i was hoping for / requesting as a feature.

ability to selectively run a set of steps as it takes a long time to run all my tests.

**Comment by tboerger** [comment]
> @tboerger so for example I can do this example to have a second set of commands ?

Nearby, the first step always gets executed, but with `--plugin` you can optionally also run additional steps.

**Comment by olymk2** [comment]
@tboerger cheers i will give it a try

**Comment by bradrydzewski** [comment]
I believe this can be achieved by splitting your tasks into separate pipeline steps:

```
pipeline:
  build:
    image: golang
    commands:
      - go build
  unit:
    image: golang
    commands:
        - go testunit
  selenium:
    image: golang
    commands:
      - go testselenium
```

 I recommend submitting a pull request that adds `--include` and `--exclude` flags. This would enable `drone exec --include=build,unit` and `drone exec --exclude=selenium` to limit which of the above steps are executed.

The bar for changing the yaml is very high. I do not believe syntax changes are required to support this use case, but am definitely open to the necessary improvements to the CLI.
