### ISSUE TITLE
Consider supporting virtual env_file in yaml

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#1909]
The docker-compose file supports the `env_file` attribute for loading configuration variables from file. It would be interesting if drone cloud support env_files. I'm not sure exactly what this would look like, but it would need to be a virtual file system, since we would not give the ability to load files from disk.

The reason I'm proposing this is because it could be a very interesting alternative to `${variable}` syntax for injecting environment variables into build environments.

**Comment by bradrydzewski** [comment]
Note that we could support multiple env_files to prevent secrets from being shared between build steps, or to separate production from staging.

```yaml
pipeline:
  build:
    image: golang:1.6
    env_file: secrets/build.env

  publish:
    image: plugins/docker
    repo: foo/bar
    tags: latest
    env_file: secrets/docker.stage.env
    when:
      event: push
      branch: master

  publish_to_prod:
    image: plugins/docker
    repo: foo/bar
    tags: prod
    env_file: secrets/docker.prod.env
    when:
      event: tag
```
