### ISSUE TITLE
commands not run in some cases

### ISSUE THREAD

**Issue by vtolstov** [drone/drone#1925]
drone 0.5 with sha commit id 928130d
Simple pipeline:
```
pipeline:
  clone:
    image: plugins/git
    depth: 1
    when:
      branch: master
  build:
    image: vtolstov/drone-packer
    devices:
      - "/dev/kvm:/dev/kvm"
    privileged: true
    pull: true
    commands:
      - date
      - CHECKPOINT_DISABLE=1 DESTDIR=/drone/images packer build ${TEMPLATE}.json
      - ls -alo /drone/images/
      - date
matrix:
  TEMPLATE:
    - centos-6-x86_32
```

packer something modify in current environment and then drone run commands only first date output date, after that packer command executed and container successful destroyed.
