### ISSUE TITLE
Slack Notification Drone 0.5

### ISSUE THREAD

**Issue by vinhmmkh** [drone/drone#1936]
Hello friends,

Im trying to configure a notification feature using slack. I googled a lot and even used many samples 
people wrote. But unfortunately none of them seems to work. 
Its documented for drone 0.5 here -> http://readme.drone.io/0.5/plugin-overview/ 
But it's not running on my drone-server. Any ideas? 

```yml
pipeline:
  build:
     [...] 

  notify:
    image: plugins/slack
    webhook_url: https://hooks.slack.com/services/[token]
    channel: drone
    when:
      event: [ push, tag, deployment, pull_request ]
      status: [ success, failure ]
      
```

The drone build gives me the following error-message: 

```sh
Post : unsupported protocol scheme ""
```

Im happy with any tips :))

**Comment by jmccann** [comment]
I think this is a topic better discussed at http://discourse.drone.io

**Comment by orlando** [comment]
@vinhmmkh here's the documentation of the Slack plugin https://github.com/drone-plugins/drone-slack/blob/master/DOCS.md

You should use `webhook` instead of webhook url.

This is how my Slack step looks

```yml
  slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/...
    channel: ci
    username: drone
    template: >
      *{{ build.status }}* <{{ build.link }}|{{ repo.owner }}/{{ repo.name }}#{{ build.commit }}> ({{ build.ref }}) by {{ build.author }}
    when:
      event: [ push, pull_request ]
      status: [ success, failure ]
```

Cheers
