### ISSUE TITLE
Output truncated after line too long

### ISSUE THREAD

**Issue by adrienverge** [drone/drone#1941]
This may be related to #1925.

If a line longer than ~60000 bytes is output by a test command (this is often the case with build tools that display "interactive progress with percentage done" using the `\b` character to reset the line), then future commands aren't shown by Drone.

Example:

```yaml
pipeline:
  build:
    image: python:slim
    commands:
      - echo BEFORE
      - python -c 'print(60000 * "a")'
      - echo IN THE MIDDLE
      - python -c 'print(70000 * "a")'
      - echo AFTER
      - exit 37
```

Output:

```
build

  + echo BEFORE
  BEFORE
  + python -c 'print(60000 * "a")'
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ...
  + echo IN THE MIDDLE
  IN THE MIDDLE
  + python -c 'print(70000 * "a")'

exit code 37
```

The `exit code 37` here suggests that all commands *are* executed, but the ones after the 70000-bytes-long line aren't printed.

Tested with:
* Docker 1.12
* Docker 1.13
* Drone 0.5 image 8525314e6314 (3 weeks old)
* Drone 0.5 image 71ae4f09f634 (3 days old)

I'd be happy to run more tests to help diagnose the problem.
