### ISSUE TITLE
${DRONE_TAG} includes refs/tags/ prefix when using with Gogs

### ISSUE THREAD

**Issue by Tebro** [drone/drone#1984]
Title says it all.

 I am using drone v0.5 with Gogs and when I am trying to build a Docker image on tag events with the git tag as the tag for the image, it fails because refs/tags/foobar is not an allowed Docker image tag.

**Comment by appleboy** [comment]
Try:

```
${DRONE_TAG##refs/tags/}
```

http://readme.drone.io/usage/environment-interpolation/

**Comment by bradrydzewski** [comment]
@appleboy note that `DRONE_TAG` has the `refs/tags` prefix stripped before interpolation
https://github.com/drone/drone/blob/v0.5.0/agent/agent.go#L307

The code linked above is also provider agnostic, meaning it doesn't matter if you are running gogs vs github vs bitbucket. We can see a working example here:
https://github.com/go-gitea/gitea/blob/master/.drone.yml#L69

Now that I'm back at my laptop I was able to run a few tests and was unable to repeat the issue with Gogs. This is the copy of the yaml I used:

```
pipeline:
  build:
    image: golang
    environment:
      - TEST_TAG=${DRONE_TAG}
      - TEST_TAG2=${DRONE_TAG##v}
    commands:
      - echo ${DRONE_TAG}
      - echo ${DRONE_TAG##v}
      - echo $TEST_TAG
      - echo $TEST_TAG2
```

This is the output which demonstrates it is working as expected

```
+ echo v0.0.5
v0.0.5
+ echo 0.0.5
0.0.5
+ echo $TEST_TAG
v0.0.5
+ echo $TEST_TAG2
0.0.5
```

I encourage anyone experiencing this issue to dig into the code and patch if they are confident there is an error, however, after a good amount of testing I cannot reproduce and am closing the issue accordingly.
