### ISSUE TITLE
Build Templating

### ISSUE THREAD

**Issue by steve-gray** [drone/drone#1990]
At a client site I've worked at, we've got a lot of builds that have basically the same YAML - but with very small/token changes to it. I'm considering sending in a PR that adds some features to simplify this workflow:

- Ability to fetch the 'pipeline' content from another URL / git repository.
- Ability to define environment variables that are common across all containers in a shared section.

The plan is that then these global environment variables are merged with the per-container environment (per-container taking precedence). For example a very typical docker flow

_Example Drone YAML_
````
environment:
  DOCKER_REPO: example-org/example-container
  
pipeline: https://github.com/steve-gray/drone-templates/docker
````

_Example Template_
````
pipeline:
  npm_tasks:
    image: node:latest
    commands:
      - npm install
      - npm test

  docker:
    image: plugins/docker
    repo: ${DOCKER_REPO}
    tags: latest
````

Considerations/extra requirements that spring to mind:

- Signing including upstream content - I'm thinking that it's both not needed (if you control the upstream source, it's game over anyway), but also defeats the point (to force re-sign). Signing is going away anyway by the looks.

- Repeatability of builds - Do we potentially need to capture the upstream template for repeatable builds? At a gut level I agree with this idea, but it complicates things. I'm thinking it's something can be rev 2.0 item?
