### ISSUE TITLE
Drone build gets triggered but nothing happens apart from clone

### ISSUE THREAD

**Issue by Alber70g** [drone/drone#2011]
I've setup Rancher with Drone. When I try to do a build it doesn't do anything except fetching the remote and checking out the commit. What can I be doing wrong? Possibly something stupid from my side but after a full day I can't seem to figure it out.

This is my yml.

```
image: ubuntu
script:
  - apt-get install hugo
  - hugo
  - hugo server
```
I've also tried
```
pipeline:
  build:
    image: ubuntu
    commands: 
      - /bin/bash -c hugo
      - /bin/bash -c hugo server
```
