### ISSUE TITLE
Feature request - support github deployment task as a constraint

### ISSUE THREAD

**Issue by firthh** [drone/drone#2013]
I'd like to be able to only deploy specific things based on the task parameter from a Github deployment.

> Task - Optional parameter to specify a task to execute, e.g. `deploy` or `deploy:migrations`. Default: `deploy`
https://developer.github.com/v3/repos/deployments/

An example of how that would look in `.drone.yml` configuration:
```
pipeline:
  deploy:
    when:
      event: deployment
      task: deploy
    image: some/image
    commands:
      - make deploy-web

  deploy-migrations:
    when:
      event: deployment
      task: deploy:migrations
    image: some/image
    commands:
      - make migrate
```
