### ISSUE TITLE
databases like rethink db can't be used as a service

### ISSUE THREAD

**Issue by josmo** [drone/drone#2020]
Drone version:
.6

Repro steps:
Add rethink db to the services like
services:
  database:
    image: rethinkdb:2.3.5
    command: [ rethinkdb, --bind, all ]
and try to connect to "database". It will error with ECONNREFUSED

from @bradrydzewski 
"the rethink issue could be a chicken and egg problem. If it binds to available interface IPs (via --all), but is created before all the pipeline containers, it will never be able to bind to their networks
this doesn't impact mysql / postgres/ etc because they don't try to bind to specific addresses
a fix could be to create all containers (pipeline and service) up front, and then start them sequentially. Today we start and run them sequentially."

**Comment by bradrydzewski** [comment]
This is fixed with `drone/drone:latest` thanks to https://github.com/drone/drone/commit/729d7599853ff54396beaf2035a620b56523885e

I tested the following yaml configuration:

```yaml
workspace:
    base: /go
    path: foo

pipeline:
  ping:
    image: node
    commands:
      - npm install -g recli
      - recli --host rethink 'r.tableCreate("bikes")'
      - recli --host rethink 'r.table("bikes")'

services:
  rethink:
    image: rethinkdb
    command: [ rethinkdb, --bind, all ]
```

Which returned the following results:

```text
+ recli --host rethink 'r.tableCreate("bikes")'
{ config_changes: 
   [ { new_val: 
        { db: 'test',
          durability: 'hard',
          id: '78ac96c4-4773-417f-8265-30de4a29a8ee',
          indexes: [],
          name: 'bikes',
          primary_key: 'id',
          shards: 
           [ { nonvoting_replicas: [],
               primary_replica: '6d58b31563c2_0be',
               replicas: [ '6d58b31563c2_0be' ] } ],
          write_acks: 'majority' },
       old_val: null } ],
  tables_created: 1 }
+ recli --host rethink 'r.table("bikes")'
[]
```
