### ISSUE TITLE
submodule_override option doesn't work to subdirectory more.

### ISSUE THREAD

**Issue by cicerocomp** [drone/drone#2044]
This setting worked in version `0.5` but no longer works in version `0.6`:
```yaml
pipeline:
  clone:
    image: plugins/git
    recursive: true
    submodule_override:
      "submodules/proto": https://github.com/cicerocomp/proto.git
```
I tried this too:
```yaml
pipeline:
  clone:
    image: plugins/git
    recursive: true
    submodule_override:
      submodules/proto: https://github.com/cicerocomp/proto.git
```

OUTPUT ERROR: 
```
+ git init
Initialized empty Git repository in /go2/src/github.com/cicerocomp/this/.git/
+ git remote add origin https://github.com/cicerocomp/this.git
+ git fetch --no-tags origin +refs/heads/development:
From https://github.com/cicerocomp/this
 * branch            development -> FETCH_HEAD
 * [new branch]      development -> origin/development
+ git reset --hard -q 566b2d3db6e9abdb66cff190bc5ce647d142b3e3
+ git submodule update --init --recursive
Submodule 'submodules/proto' (git@github.com:cicerocomp/proto.git) registered for path 'submodules/proto'
Cloning into '/go2/src/github.com/cicerocomp/this/submodules/proto'...
Host key verification failed.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights and the repository exists.
fatal: clone of 'git@github.com:cicerocomp/proto.git' into submodule path '/go2/src/github.com/cicerocomp/this/submodules/proto' failed
exit status 128
```
