### ISSUE TITLE
[Feature Request] Ability to run pipeline steps after all matrix builds finish successfully

### ISSUE THREAD

**Issue by calind** [drone/drone#2062]
Consider the following pipeline:
```
pipeline:
  test:
    image: python:${PYTHON_VERSION}
matrix:
  PYTHON_VERSION:
    - 2.7
    - 3.5
```

I'm trying to add a `publish` step which runs after all the matrix builds are successful but I don't seam to find a proper way to implement it.
