### ISSUE TITLE
BUG: Conditional "changed" not working 

### ISSUE THREAD

**Issue by patrickjahns** [drone/drone#2072]
With the upgrade past > 0.5 the conditional "changed" is not working / not working as expected anylonger.

Example
```
pipeline:
  step1:
    image: alpine
    commands: 
      - exit 1
  notify:
   image: alpine
   commands:
      - echo "failure or changed"
  when:
    status: [changed, failure] 
```

Expected behavior:
- when `step1` fails, execute `notify`
- when `step1` previously failed and currently the pipeline has not (failed until step notify) also execute `notify`

Actual behavior:
- `notify` will only be executed when previous steps failed - it will not be executed when the pipeline returns into a green state

problem most likely is somewhere in https://github.com/cncd/pipeline - but haven't found the correct spot to look at yet
