### ISSUE TITLE
Feature request - Ignore folder/file update

### ISSUE THREAD

**Issue by xataz** [drone/drone#2074]
Hello,

How to ignore pipeline step if (for example) I push only a new README.md.

Other example, your drone.yml with backend and frontend. If I push only backend, it's not necessary to build frontend.

I think this way : 
```yaml
pipeline:
  backend:
    group: build
    image: golang
    commands:
      - go build
      - go test
    when:
      file:
        include: ["backend/*"]
        exclude: ["backend/docs/*", "backend/README.md"]      

  frontend:
    group: build
    image: node
    commands:
      - npm install
      - npm run test
      - npm run build
    when:
      file: ["frontend/*"]
```

PS : Sorry for my bad english

**Comment by bradrydzewski** [comment]
please subscribe to https://github.com/drone/drone/issues/1021

**Comment by unfor19** [comment]
I solved it by using the `exit 78` command
You can change the `drone-diff.sh` script to match regex patterns. I'm using it to ignore `README.md`

`drone.yml`
```yaml
steps:
  - name: drone-diff
    image: xueshanf/awscli:alpine-3.11
    commands:
      - /bin/bash scripts/drone-diff.sh
```

`drone-diff.sh`
```bash
#!/bin/bash
_GIT_DIFF=$(git diff --numstat HEAD HEAD~1)
_NUM_LINES=$(echo "$_GIT_DIFF" | wc -l)

if [[ "$_NUM_LINES" -eq 1 ]]; then
    README_ONLY=$(echo "$_GIT_DIFF" | grep README\.md)
    if [[ -n "$README_ONLY" ]]; then
        echo "[LOG] Only README.md was changed, skipping pipeline"
        exit 78
    fi
fi
echo "[LOG] Files that were changed in this commit"
echo "$_GIT_DIFF" | awk '{print $3}'
```

https://cloud.drone.io/unfor19/terraform-multienv/127/1/2
![drone-skip](https://user-images.githubusercontent.com/15122452/92311010-dfbf4b00-efbb-11ea-8b13-bde712797077.png)

https://cloud.drone.io/unfor19/terraform-multienv/126/1/2
![drone-dont-skip](https://user-images.githubusercontent.com/15122452/92311013-e352d200-efbb-11ea-9f65-7736763dfeb8.png)
