### ISSUE TITLE
Commit author email is empty with gogs/gitea providers

### ISSUE THREAD

**Issue by favadi** [drone/drone#2078]
Gitea version: 1.1.2
Drone version: 0.7.1

Steps to reproduce:
* setup a Gitea 1.1.2 instance 
* setup drone server/agent with following docker-compose.yml

```
services:
  drone-server:
    image: drone/drone:0.7.1
    ports:
      - 80:8000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=false
      - DRONE_GITEA=true
      - DRONE_GITEA_URL=https://git.company.com/
      - DRONE_GITEA_PRIVATE_MODE:true
      - DRONE_SECRET=<something>

  drone-agent:
    image: drone/drone:0.7.1
    command: agent
    restart: always
    depends_on: [ drone-server ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=<something>
```
* create and active a repository with following .drone.yml

```
pipeline:
  debug:
    image: alpine:3.4
    commands:
      - env
```

Expected behavior: in the build output, see `DRONE_COMMIT_AUTHOR_EMAIL`.

Actual behavior: No `DRONE_COMMIT_AUTHOR_EMAIL` in build output, or any environment variable with email.

Extra information:
* I tried with Gogs provider, but same result.
* Post hook payload with removed sensitive information
```
{
  "secret": "<removed>",
  "ref": "refs/heads/master",
  "before": "9a6d4950fcd4b23593693b66281dc9737998f3c0",
  "after": "e1ce9a14a8c89a968de7511a389912661be93ac4",
  "compare_url": "https://git.company.com/ci/drone-test/compare/9a6d4950fcd4b23593693b66281dc9737998f3c0...e1ce9a14a8c89a968de7511a389912661be93ac4",
  "commits": [
    {
      "id": "e1ce9a14a8c89a968de7511a389912661be93ac4",
      "message": "do something\n",
      "url": "https://git.company.com/ci/drone-test/commit/e1ce9a14a8c89a968de7511a389912661be93ac4",
      "author": {
        "name": "My Real Name",
        "email": "me@myemail.com",
        "username": "my_username"
      },
      "committer": {
        "name": "My Real Name",
        "email": "me@myemail.com",
        "username": "my_username"
      },
      "timestamp": "2017-06-20T08:39:13Z"
    }
  ],
  "repository": {
    "id": 7,
    "owner": {
      "id": 3,
      "login": "ci",
      "full_name": "",
      "email": "ci@my_username.com",
      "avatar_url": "https://secure.gravatar.com/avatar/795cee0be515bbc377c8da227c0a0363",
      "username": "ci"
    },
    "name": "drone-test",
    "full_name": "ci/drone-test",
    "description": "",
    "private": true,
    "fork": false,
    "mirror": false,
    "html_url": "https://git.company.com/ci/drone-test",
    "ssh_url": "ssh://git@git.company.com:2222/ci/drone-test.git",
    "clone_url": "https://git.company.com/ci/drone-test.git",
    "website": "",
    "stars_count": 0,
    "forks_count": 0,
    "watchers_count": 1,
    "open_issues_count": 0,
    "default_branch": "master",
    "created_at": "2017-04-18T07:39:22Z",
    "updated_at": "2017-06-20T08:08:36Z",
    "permissions": {
      "admin": false,
      "push": false,
      "pull": false
    }
  },
  "pusher": {
    "id": 1,
    "login": "my_username",
    "full_name": "My Real Name",
    "email": "me@myemail.com",
    "avatar_url": "https://git.company.com/avatars/74170010fb38c17915d187346da8a985",
    "username": "my_username"
  },
  "sender": {
    "id": 1,
    "login": "my_username",
    "full_name": "My Real Name",
    "email": "me@myemail.com",
    "avatar_url": "https://git.company.com/avatars/74170010fb38c17915d187346da8a985",
    "username": "my_username"
  }
}
```
