### ISSUE TITLE
Cant start drone with docker-compose.yml

### ISSUE THREAD

**Issue by FlorianTaut** [drone/drone#2099]
Hey,

i want to integrate drone to my gogs instance.
This is my docker-compose.yml:

```
version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 80:8000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=https://[SECRET]
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://[SECRET]
      - DRONE_GOGS_GIT_USERNAME=[SECRET]
      - DRONE_GOGS_GIT_PASSWORD=[SECRET]
      - DRONE_SECRET=[SECRET]

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=[SECRET]
```

But im recieving the following error when i run `sudo docker-compose up`
![unbenannt](https://user-images.githubusercontent.com/18403881/27763789-a7842c58-5e8a-11e7-89a9-54f65e6f4660.PNG)

This repeats about 30 times

Is my docker-compose wrong in some ways? or is something missing?

Thank you guys
