### ISSUE TITLE
Ability to use pod network for pipeline network

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2133]
In older versions of drone we emulated pod networking which is a shitty hack that lets every container share the same network (with restrictions) so that everything is accessible via localhost (sometimes called pod networking). This was changed in 0.6 to use docker hostnames, in an effort to increase compliance with docker compose, of which the drone yaml is a superset.

There are still some scenarios where pod network may be needed, or where localhost may simply be easier to work with. We should therefore give the ability to override the default configuration and enable pod networking.

The syntax would conform to docker-compose. In the yaml file you would create a default network with custom drone-specific driver options enabling pod networking:

```
pipeline:
  ...

networks:
  default:
    driver: bridge
    driver_opts: io.drone.network.pod=true
```
