### ISSUE TITLE
Unable to use private Docker image for pipeline

### ISSUE THREAD

**Issue by tranquochuy** [drone/drone#2152]
I tried to use my private Docker image for testing follow this:

```
pipeline:
  test:
    image: myimage:1.0
    commands:
      - pip install -r requirements/all.txt
      - ./src/manage.py test
    auth_config:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      email: ${DOCKER_EMAIL}
```

At first, if I remove that tag name of out of the image, it can run successfully.

But when there is a tag name (like 1.0, develop, on-test) it can not pull my image. Here come this error: 

```
error_outlineERROR: Error: No such image: myimage:1.0
```
Does any one get this error?
