### ISSUE TITLE
Service linking not working

### ISSUE THREAD

**Issue by rochdev** [drone/drone#2153]
Configurations tried:

```yaml
services:
  hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
```

This results in a `Not linked with a running Hub container` error.

```yaml
services:
  hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
```

This work intermittently. Sometimes nodes will register properly and sometimes they fail with a `Couldn't register this node: Error sending the registration request: hub`. This is not a race condition between the services since the node retries every 5 seconds with the same message indefinitely. It may however be a race condition in the way linking is done by Drone.

```yaml
services:
  hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
```

Same result as above, but even worst by the fact that it causes the pipeline to never start. Using `deps` or `links` instead of `depends_on` leads to the same result.

**Comment by bradrydzewski** [comment]
I am unable to repeat any issues when using Selenium. Below are links to working examples of Selenium and Selenium hub

Selenium Standalone, Chrome only
https://github.com/drone-demos/drone-go-selenium

Selenium Hub, Chrome and Firefox
https://github.com/drone-demos/drone-go-selenium/tree/chrome-and-firefox

Successful build confirms the above configurations are working:
https://beta.drone.io/drone-demos/drone-go-selenium/20

> This work intermittently. Sometimes nodes will register properly and sometimes they fail with a Couldn't register this node: Error sending the registration request: hub. This is not a race condition between the services since the node retries every 5 seconds with the same message indefinitely. It may however be a race condition in the way linking is done by Drone.

I was unable to repeat (in 10 attempts) but acknowledge that startups times and initialization can vary based on a number of factors which could be preventing me from reproducing. If you continue to experience issues I would recommend adding a sleep command to the nodes, giving the hub enough time to startup and initialize.

> but even worst by the fact that it causes the pipeline to never start.

This is caused by the `depends_on` parameter which is not supported by drone. When you use an unsupported variable in the yaml, drone assumes you are defining a plugin step, and the unknown parameter is a plugin parameter. This causes the step to be started as blocking.

```diff
services:
  hub:
    image: selenium/hub

  chrome:
    image: selenium/node-chrome
-   depends_on:
-     - hub
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
```

Note that if you really need direct control over the order of initialization you can declare services inside the pipeline, using the `detach` command. The pipeline is executed serially.

```diff
pipeline:
  hub:
    image: selenium/hub
+   detach: true

  chrome:
    image: selenium/node-chrome
+   detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  build:
    ...

  test:
    ...
```

**Comment by rochdev** [comment]
I forgot to mention that I tried this using `drone exec` on OS X Sierra with Drone 0.7.0 and Docker 17.06.0-ce-mac19. I know sometimes Docker behaves slightly differently on OS X than on a real linux server so that may have affected my results.

We should have Drone running on GKE this week so I will try there and report back.

I am also not using 0.8.x because last time I tried the RC the UI was broken. I will try that also and see if it fixes the problem.

I will definitely try the detach method as it also solves the issue of starting the services before they are actually required. Thanks for the tip!

**Comment by rochdev** [comment]
I can reproduce about half of the time using this `.drone.yml`:

```yaml
pipeline:
  build:
    image: busybox
    commands:
      - sleep 2

  firefox:
    image: selenium/node-firefox
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  chrome:
    image: selenium/node-chrome
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  acceptance-tests:
    image: busybox
    commands:
      - sleep 5

services:
  hub:
    image: selenium/hub
```

This is running `drone exec` locally on the aforementioned environment. It seems the real acceptance tests (not shown here) also have trouble connecting to the hub about half of the time.

I have also tried for good measure:

```yaml
pipeline:
  hub:
    image: selenium/hub
    detach: true

  build:
    image: busybox
    commands:
      - sleep 2

  firefox:
    image: selenium/node-firefox
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  chrome:
    image: selenium/node-chrome
    detach: true
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444

  acceptance-tests:
    image: busybox
    commands:
      - sleep 5
```
