### ISSUE TITLE
Allow empty service image

### ISSUE THREAD

**Issue by cedk** [drone/drone#2165]
For example, when with different databases, you could have sqlite which does not require a service.
For now, I have created a fake sqlite docker image but I think drone could just skip if the image is empty.

**Comment by tboerger** [comment]
Why do you want to create a service for that at all? You can add conditions to services as well, even for matrix builds:

```
services:
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_USER=redacted
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=redacted
      - MYSQL_ROOT_PASSWORD=redacted
    when:
      matrix:
        DB_TYPE: mariadb

  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_USER=redacted
      - MYSQL_PASSWORD=redacted
      - MYSQL_DATABASE=redacted
      - MYSQL_ROOT_PASSWORD=redacted
    when:
      matrix:
        DB_TYPE: mysql

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=redacted
      - POSTGRES_PASSWORD=redacted
      - POSTGRES_DB=redacted
    when:
      matrix:
        DB_TYPE: postgres
```
