### ISSUE TITLE
[0.8.0-rc.3] DRONE_TAG and CI_TAG are no longer been passed to deployments of tag-builds

### ISSUE THREAD

**Issue by rwillians** [drone/drone#2186]
# Reproducing the bug

Create the following pipeline:

```yml
pipeline:
  tag:
    image: alpine
    commands:
      - env
    when:
      event: tag

  deployment:
    image: alpine
    commands:
      - env
    when:
      event: deployment
      environment: testing
```

Push a new tag to the repository and watch the logs for `tag` step: there **MUST** be present the environment variables **DRONE_TAG** and **CI_TAG**;

Deploy the build from the previous step and watch the logs for `deployment` step: there **MUST NOT** be present the environment variables **DRONE_TAG** and **CI_TAG**;

**Comment by bradrydzewski** [comment]
The DRONE_TAG environment variable is set if the `ref` field starts with `refs/tags`
https://github.com/cncd/pipeline/blob/master/pipeline/frontend/metadata.go#L214:L216

I was unable to reproduce any issues with gogs or github.

I used the following yaml:

```
pipeline:
  foo:
    image: golang
    commands:
      - env
```

I think tagged a commit:

```
git tag v1.0.0
git push origin v1.0.0
```

I then executed the deployment for the tag event


```
drone deploy bradrydzewski/some-private-repo 13 production
```

I saw this in my yaml output

```
DRONE_TAG=v1.0.0
DRONE_BUILD_EVENT=deployment
...
```

**Comment by rwillians** [comment]
That's weird, I've tried your pipeline and I've hit the bug
I'll try to narrow down the cause

**Comment by bradrydzewski** [comment]
did you run my exact yaml ?

**Comment by rwillians** [comment]
yes

**Comment by rwillians** [comment]
I have reproduced the bug locally using docker-compose:

https://github.com/rwillians/drone-tag/blob/master/.drone.yml

```yml
version: '2'
volumes:
  drone-1: {}
services:
  server:
    image: drone/drone:0.8.0-rc.3
    environment:
      DRONE_ADMIN: rwillians,bradrydzewski
      DRONE_DEBUG: 'true'
      DRONE_GITHUB: 'true'
      DRONE_GITHUB_CLIENT: redacted
      DRONE_GITHUB_CONTEXT: continuous-integration/drone
      DRONE_GITHUB_PRIVATE_MODE: 'true'
      DRONE_GITHUB_SCOPE: repo,repo:status,user:email,read:org
      DRONE_GITHUB_SECRET: redacted
      DRONE_HOST: http://28b892a8.ngrok.io
      DRONE_OPEN: 'false'
      DRONE_SECRET: redacted
      GIN_MODE: release
      NO_PROXY: drone
      no_proxy: drone
    volumes:
    - drone-1:/var/lib/drone/
    ports:
    - 8080:8000
    - 9000:9000
  agent:
    image: drone/agent:0.8.0-rc.3
    environment:
      DRONE_SECRET: zY%1oDz2_p6,vs-v
      DRONE_SERVER: drone:9000
      NO_PROXY: drone
      no_proxy: drone
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - server:drone
    command:
    - agent
```
