### ISSUE TITLE
Gogs skip_verify is not work!

### ISSUE THREAD

**Issue by lunny** [drone/drone#2206]
```yml
pipeline:
  clone:
    image: plugins/git
      depth: 50
      tags: true
      skip_verify: true
```

```
+ git init
0s
2
Initialized empty Git repository in /srv/app/src/bigdata/express/.git/
0s
3
+ git remote add origin https://192.168.20.248:3000/bigdata/express.git
0s
4
+ git fetch --no-tags origin +refs/heads/master:
0s
5
fatal: unable to access 'https://192.168.20.248:3000/bigdata/express.git/': SSL certificate problem: self signed certificate
0s
6
exit status 128
```

**Comment by bradrydzewski** [comment]
This is because the clone section was moved outside of the pipeline. So you need to adjust your configuration like this:

```
clone:
  image: plugins/git
    depth: 50
    tags: true
    skip_verify: true

pipeline:
  ...
```

If you have further questions feel free to start a topic at https://discourse.drone.io. We generally prefer this prior to creating an issue. Cheers!
