### ISSUE TITLE
Drone0.7 can get repo list from gitlab.But always 401 with active repo.

### ISSUE THREAD

**Issue by ZhenyangZhao** [drone/drone#2213]
I use drone:v0.7.Drone can login and get repo list success,but can not active repo,always 401.
Drone server log only one line `401 Unauthorize`.

```
Environment:
mysql:5.5
kubernetes:1.7
gitlab:9.0
```

```
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-03-30T21:14:38Z
  name: drone-config
  namespace: default
data:

  ################################
  # Drone Server (master) Config #
  ################################

  server.debug.is.enabled: "true"

  # You'll probably want to leave this alone, but you can point to external
  # DB instances if you'd like: http://readme.drone.io/0.7/manage/database/
  server.database.driver: mysql 
  server.database.config: drone:drone@tcp(10.2.16.8:30008)/drone?parseTime=true

  server.is.open: "false"
  # CHANGEME: If you want to restrict access to a particular org, put the
  # name here.
  server.orgs.list: ""
  # CHANGEME: Add your GitHub/Bitbucket/Gogs/etc username here. This is a
  # comma-separated list of usernames who will have admin privs.
  server.admin.list: donghb,zhaozy,fuqq
  server.admin.everyone.is.admin: "false"

  # See http://readme.drone.io/0.5/manage/server/ for possible values here.
  # For now, our demo is GitHub-only. Drone supports other remotes, we just
  # haven't set the others up in here yet.
  # CHANGEME: Substitute your Github OAuth application client ID and secret.
  server.remote.gitlab.is.enabled: "true"
  server.remote.gitlab.client.id: cc4ce2db3715abadd9cff88cd8df34140d9078a8a060d8140684ab32fc5c1529
  server.remote.gitlab.secret: 0ec1f4d7f46c50d9b236fc475b1881dbab8c523ab49433850a4f443b1619fe77 
  server.remote.gitlab.url: http://10.20.0.196
```
