### ISSUE TITLE
How make the tests run faster?

### ISSUE THREAD

**Issue by zulhfreelancer** [drone/drone#2214]
![screen shot 2017-09-14 at 12 15 01 pm](https://user-images.githubusercontent.com/3416976/30429336-9cf5186e-9946-11e7-9445-6603c342d20b.png)

I'm using Drone to run `rspec` and everything is okay so far. But, I think it's slow. On average, it took around 5 minutes, 20 seconds to finish.

My `.drone.yml`:

```
pipeline:
  build:
    image: zulhfreelancer/ruby_nodejs:latest
    commands:
      - gem update bundler
      - bundle install --path vendor/bundle
      - bundle exec rake db:create db:migrate
      - bundle exec rspec
    environment:
      - RAILS_ENV=test
      - SECRET_TOKEN=abc
      - DB_HOST=postgres
      - DB_USER=pg_user
      - DB_PASSWORD=pg_pass

services:
  postgres:
    image: postgres:9.4.5
    environment:
      POSTGRES_PASSWORD: pg_pass
      POSTGRES_USER: pg_user
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: useradmin_test
  redis:
    image: redis:2.8.22

cache:
  - vendor/bundle
  - .git

```

Any idea or suggestion how to make the tests finish faster?

FYI, I'm running DroneCI on 1GB VPS. I only have Drone service inside that VPS. No other processes running except Drone.
