### ISSUE TITLE
Missing "VOLUME /var/lib/drone" in the Docker image

### ISSUE THREAD

**Issue by twang2218** [drone/drone#2259]
The drone database driver is `sqlite3` by default in the `drone/drone` docker image, and the database file will be stored at `/var/lib/drone/drone.sqlite` as `DATABASE_CONFIG` say.

```dockerfile
ENV DATABASE_DRIVER=sqlite3
ENV DATABASE_CONFIG=/var/lib/drone/drone.sqlite
ENV GODEBUG=netdns=go
ENV XDG_CACHE_HOME /var/lib/drone
```

However, the directory is not available by default, that will lead to  database creation failure during the container boot up if not further `-v` instructions is given.

Here is a example setup without `volumes`:

```yaml
version: '2'

services:
  drone-server:
    image: drone/drone:0.7
    ports:
      - 80:8000
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=${DRONE_GOGS_URL}
      - DRONE_SECRET=${DRONE_SECRET}

  drone-agent:
    image: drone/drone:0.7
    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=ws://drone-server:8000/ws/broker
      - DRONE_SECRET=${DRONE_SECRET}
```

And the error for `drone-server` will be something like this:

```bash
drone-server_1  | time="2017-11-07T13:14:22Z" level=error msg="unable to open database file"
drone-server_1  | time="2017-11-07T13:14:22Z" level=fatal msg="database ping attempts failed"
```

To avoid such error, an anonymous volume can be setup at `/var/lib/drone` in the `Dockerfile`. 

```Dockerfile
VOLUME [ "/var/lib/drone" ]
```

Actually, there was a `VOLUME` instruction before, however it's been removed somehow.
