### ISSUE TITLE
[PROPOSAL] Pipeline Validation Plugin

### ISSUE THREAD

**Issue by tonglil** [drone/drone#2266]
I'd like to suggest a feature for drone that would probably help plugin developers/security.

# Issue

When using global secrets, you can lock down the images that the secret is exposed to, which is really helpful in preventing secrets from being "printenv" printed in a different step.

However, the user can still configure their pipeline to run like:

```yml
---
pipeline:
  docker:
    image: plugins/docker
    commands:
      - printenv
    secrets:
      - docker_password
```

Or:

```yml
pipeline:
  docker:
    image: plugins/docker
    entrypoint: [ /bin/sh ]
    command: [ -c, env ]
    secrets: [ docker_password ]
```

And potentially:

```yml
pipeline:
  hack:
    image: alpine
    commands:
      - echo "env" > /tmp/bin/terraform
      - chmod +x /tmp/bin/terraform
    volumes:
      - data-volume:/tmp/bin
  terraform:
    image: plugins/terraform
    volumes:
      - data-volume:/bin

volumes:
  data-volume:
```

Which will print the env, including the secret.

# Idea

Allow Drone Server to specify a list of images that can only be run in "plugin" mode.

This might be done by:
- Config file (like global secrets/registry)
- Env vars (though this can get unwieldy like DRONE_ADMIN)

# Considerations

- If a build step is privileged there will always be a workaround.
- Shared volumes
- [Mount a volume](http://docs.drone.io/docker-volumes/) in the container that overrides the entrypoint or the plugin's binary

# Alternatives

Somehow allow configuration to prevent secrets from being injected into a container being run in the "plugin syntax" vs non "plugin syntax".
