### ISSUE TITLE
Add instructions to deploy on docker swarm

### ISSUE THREAD

**Issue by sheerun** [drone/drone#2277]
Here's my try:

```
version: '3.3'
services:
  drone-proxy:
    image: dockercloud/haproxy
    ports:
      - "80:80"
    deploy:
      mode: global
    depends_on:
      - drone-server
    environment:
      - FORCE_DEFAULT_BACKEND=False
      - ADDITIONAL_BACKEND_FRONT=server srv drone-server:8000
      - EXTRA_FRONTEND_SETTINGS_80=default_backend FRONT

  drone-server:
    image: drone/drone:0.8
    ports:
      - "8000:8000"
      - 9000
    volumes:
      - type: volume
        source: drone
        target: /var/lib/drone
        volume:
          nocopy: true
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=drone.example.com
      - DRONE_SECRET=xxx
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=yyy
      - DRONE_GITLAB_SECRET=zzz

  drone-agent:
    image: drone/agent:0.8
    command: agent
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=xxx
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == worker

volumes:
  drone:
```

The deployment is as follows:

```
docker stack deploy --compose-file docker-compose.yml drone
```

btw. deploying on multiple hosts is currently crippled in functionality as there's no way to limit jobs running on single host: https://github.com/drone/drone/issues/758 Ideally drone would adapt resource-based approach known from nomad.

**Comment by chriscowley** [comment]
I'll add my stack for use with Gitea and Traefik and Glusterfs:

```
version: "3.4"
services:
    drone-server:
        image: drone/drone:latest
        volumes:
            - drone_data:/var/lib/drone
        ports:
            - 9000
        environment:
            - DRONE_OPEN=true
            - DRONE_HOST=https://drone.mycompany.com
            - DRONE_GITEA=true
            - DRONE_GITEA_URL=https://git.mycompany.com
            - DRONE_SECRET=hahalol
        deploy:
            mode: replicated
            replicas: 1
            labels:
                "traefik.port": "8000"
                "traefik.enable": "true"
                "traefik.docker.network": "traefik-net"
                "traefik.frontend.rule": "Host:drone.mycompany.com"
        networks:
            - drone                                                                                                                                                                                                                            
            - traefik-net

    drone-agent:
        image: drone/drone:latest
        command: agent
        depends_on:
            - drone-server
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - DRONE_SERVER=drone-server:9000                                                                                                                                                                                                   
            - DRONE_SECRET=hahalol
        networks:
            - drone
        deploy:
            mode: global
        

volumes:
    drone_data: 
        driver: hjdr4plugins/docker-volume-glusterfs

networks:
    drone:
        driver: overlay
        external: false
        attachable: true
    traefik-net:
        external: true
```
