### ISSUE TITLE
Pipeline steps unable to connect to host the agent is running on

### ISSUE THREAD

**Issue by shnhrrsn** [drone/drone#2293]
I'm running into a strange networking issue where pipeline steps are unable to connect to a domain that resolves to the same host the agent is running on.

As far as I've been able to isolate, this is specifically related to Drone as I've confirmed both the host itself and containers ran directly on the host can connect.

Here’s my pipline config:

```yaml
pipeline:

  test:
    image: byrnedo/alpine-curl
    commands:
      - ping -c 1 HOST
      - curl -s http://ifconfig.co
      - curl --connect-timeout 5 http://HOST
```

And the output when it’s ran:

```bash
+ ping -c 1 HOST
PING HOST (1.1.1.1): 56 data bytes
64 bytes from 1.1.1.1: seq=0 ttl=64 time=0.199 ms
--- HOST ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.199/0.199/0.199 ms
+ curl -s http://ifconfig.co
1.1.1.1
+ curl --connect-timeout 5 http://HOST
curl: (28) Connection timed out after 5001 milliseconds
```

When I run the same command on the host, they run fine:

```bash
root@host01:~# curl --connect-timeout 5 http://HOST
<html>
<head>…
```

To ensure this isn’t a Docker issue, I also tested running the image/command from the pipeline above directly in Docker:

```bash
root@host01:~# docker run byrnedo/alpine-curl --connect-timeout 5 http://HOST
<html>
<head>…
```

I believe this may also be related to drone-plugins/drone-docker#156
