### ISSUE TITLE
 In drone got an error “/bin/sh: 1: base64: not found ”. 

### ISSUE THREAD

**Issue by JermineHu** [drone/drone#2296]
**My .drone.yml file as follows code .**

```
branches:
  include: [ master, dev ]
  exclude: [ develop, feature/* ]
clone:
  git:
    image: plugins/git
    depth: 50
workspace:
  base: /go
  path: src/xink.com/metis
pipeline:
  build:
    when:
      branch: master
    image: golang:alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   # - /usr/bin/base64:/bin/base64
    environment:
      - CGO=0
      - GOOS=linux
      - GOARCH=amd64
      - PATH=$PATH:/go
      - GOPATH=/go
    commands:
      - go env
      - go build -v -o metis
```

![tim 20180110105337](https://user-images.githubusercontent.com/18027793/34759158-27e78530-f615-11e7-9d47-812de0b7a5c2.png)

**When push code the Drone start pipeline build step.  I try " /usr/bin/base64:/bin/base64 " by volumes but got " standard_init_linux.go:195: exec user process caused 'no such file or directory' " .** 

![tim 20180110144744](https://user-images.githubusercontent.com/18027793/34759175-3c58dcc6-f615-11e7-9e27-43244dd31a04.png)

_**I make file as follows code got successful status.**_

```
branches:
  include: [ master, dev ]
  exclude: [ develop, feature/* ]
clone:
  git:
    image: plugins/git
    depth: 50
workspace:
  base: /go
  path: src/xink.com/metis
pipeline:
  build:
    when:
      branch: master
    image: golang:alpine
    commands: go build -v -o metis
```

![tim 333](https://user-images.githubusercontent.com/18027793/34759231-6e9c23b4-f615-11e7-8146-d2d2f19586d8.png)

**So ， I think this should be a bug in resolve .drone.yml at "environment","commands","volumes" node with multiple parameters or my .drone.yml configuration file is wrong ？**
