### ISSUE TITLE
Vendor folder is fully populated on source repo

### ISSUE THREAD

**Issue by gboddin** [drone/drone#2298]
What about dropping the content of the vendor folder to lower the code in the repo and avoid vendoring issues ?

Suggestion, add in the workflow ( .drone.yml ) 
```
  get-deps:
    image: golang:1.8
    commands:
      - go get github.com/kardianos/govendor
      - govendor sync
```

and in .gitignore

```
vendor/*
!vendor/vendor.json
```
