### ISSUE TITLE
drone not build stage when i push code to gitlab

### ISSUE THREAD

**Issue by dragontree101** [drone/drone#2304]
i use drone 0.8 version and gitlab 8.x version

i want to ci use drone + gitlab 

but my project's `.drone.yml` file is 
```
pipeline:
  build:
    image: 10.10.30.38:5000/alpine-java-maven
    commands:
      - mvn -DskipTests=true clean package -U

branches: [ master ]
```
and i push to gitlab, but not found drone execute build stage

![image](https://user-images.githubusercontent.com/1763935/34970302-99830262-faae-11e7-8a9d-177cb4fa84d4.png)

what steps i miss? 

i need gitlab ci add hooks?  

![image](https://user-images.githubusercontent.com/1763935/34970331-c6d823aa-faae-11e7-9059-4b066b480983.png)

what is the url and Secret Token ?
