### ISSUE TITLE
Unable to authenticate with gogs

### ISSUE THREAD

**Issue by xero88** [drone/drone#2316]
I get this when I try to authenticate : 

`level=error msg="cannot authenticate user. Post https://gogs.mycompany.ch/api/v1/users/myusername/tokens: dial tcp: lookup gogs.mycompany.ch on 127.0.0.11:53: no such host"`

The host is up, i can ping it and connect to it from my host machine

Here my docker-compose.yml : 

```
version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 80:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=myuser
      - DRONE_HOST=https://gogs.mycompany.ch
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=https://gogs.mycompany.ch
      - DRONE_SECRET=6K6dBirtSf

  drone-agent:
    image: drone/agent:0.8

    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=6K6dBirtSf
```
