### ISSUE TITLE
Anchors doesn't work in yaml

### ISSUE THREAD

**Issue by laszlocph** [drone/drone#2323]
Yaml anchors used to work with earlier versions. With the 0.8 line it doesn't work anymore

Here is a snippet that would be nice to see working. More details are in this discourse thread: 
https://discourse.drone.io/t/solved-conditional-builds-multiple-when-clauses/316/4

```
run_tests: &run_tests
  image: node:7.6.0
  commands:
    - npm install --no-optional --silent > /dev/null
    - npm run ci

pipeline:
  pr:
    <<: *run_tests
    when:
      event: pull_request
      branch:
        excludes: master
  push:
    <<: *run_tests
    when:
      event: push
      branch: master
```

Running this snippet results in "Invalid or missing image"
