### ISSUE TITLE
Cannot login behind apache proxy

### ISSUE THREAD

**Issue by Angelinsky7** [drone/drone#2338]
I just installed drone from docker version 0.8.4
I configured it to work behind a reverse apache proxy : 

```
<IfModule mod_proxy.c>
  ProxyRequests off
  ProxyVia On

  ProxyPreserveHost On
  RequestHeader set X-Forwarded-Proto "https"

  ProxyPass / http://INTERNAL_URL:18090/
  ProxyPassReverse / http://INTERNAL_URL:18090/

  <Location />
    ProxyPassReverse /
  </Location> 
</IfModule>
```

Here's my docker-compose config : 
```
version: '2'
services:
  server:
    image: drone/drone
    environment:
      DRONE_ADMIN: admin
      DRONE_DATABASE_DATASOURCE: drone:drone@tcp(mysql:3306)/drone?parseTime=true
      DRONE_DATABASE_DRIVER: mysql
      DRONE_DEBUG: 'true'
      DRONE_GITLAB: 'true'
      DRONE_GITLAB_CLIENT: CLIENT
      DRONE_GITLAB_SECRET: SECRET
      DRONE_GITLAB_URL: GITLAB
      DRONE_HOST: DRONE_EXTERNAL_URL (REVERSE PROXY)
      DRONE_OPEN: 'true'
      DRONE_ORGS: ORG
      DRONE_SECRET: SECRET
      GIN_MODE: release
      NO_PROXY: drone
      no_proxy: drone
    links:
    - mysql:mysql
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  agent:
    image: drone/agent
    environment:
      DRONE_SECRET: SECRET
      DRONE_SERVER: drone:9000
      NO_PROXY: drone
      no_proxy: drone
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - server:drone
    command:
    - agent
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
      io.rancher.container.hostname_override: container_name
  lb:
    image: rancher/lb-service-haproxy:v0.7.15
    ports:
    - 18090:18090/tcp
    labels:
      io.rancher.container.agent.role: environmentAdmin,agent
      io.rancher.container.agent_service.drain_provider: 'true'
      io.rancher.container.create_agent: 'true'
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: PASS
      MYSQL_DATABASE: drone
      MYSQL_USER: drone
      MYSQL_PASSWORD: PASS
    volumes:
    - drone_mysql_data:/var/lib/mysql
    labels:
      io.rancher.container.pull_image: always
```

if i target the url of docker, i'm redirected to the gitlab auth page (and it's working)
using haproxy or not doesn't change anything... it seems an issue with using the apache reverse proxy
if i target the reverse external proxy, i've got an error page :

![image](https://user-images.githubusercontent.com/13157968/36035829-6b04027a-0db8-11e8-9a1b-5ce724b1ac1f.png)

without any more informations
the only log that i have :
```
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=info ip=9.138.222.1 latency=42.16µs method=GET path="/login" status=303 time="2018-02-09T15:44:26Z" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=info ip=9.138.222.1 latency=157.154µs method=GET path="/authorize" status=303 time="2018-02-09T15:44:26Z" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=info ip=9.138.222.1 latency=218.365µs method=GET path="/oauth/authorize" status=200 time="2018-02-09T15:44:26Z" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=info ip=9.138.222.1 latency=106.194µs method=GET path="/api/user/feed" status=401 time="2018-02-09T15:44:26Z" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=debug msg="Cannot find repository oauth/authorize. sql: no rows in result set"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=info ip=9.138.222.1 latency=1.108083ms method=GET path="/api/repos/oauth/authorize" status=401 time="2018-02-09T15:44:26Z" user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=debug msg="user feed: connection opened"
2/9/2018 4:44:26 PMtime="2018-02-09T15:44:26Z" level=debug msg="Cannot find repository oauth/authorize. sql: no rows in result set"
```

with this line only when is not working : 
`Cannot find repository oauth/authorize. sql: no rows in result set`

Here's my generate url (that is correct) :
`https://drone-ci.darkink.ch/oauth/authorize?client_id=CLIENT&redirect_uri=https%3A%2F%2FDRONE_URL%2Fauthorize&response_type=code&scope=api&state=drone`

Could you help me please !
Thanks a lot, i'm pretty excited to make this work, this seems very cool
