### ISSUE TITLE
Inaccessible Services

### ISSUE THREAD

**Issue by hickscorp** [drone/drone#2340]
Note: this bug doesn't appear when using a docker-compose based setup, only when using `drone exec`.

Here is a sample `.drone.yml` file:

```
pipeline:
  build:
    image: elixir:1.6
    commands:
      - ./scripts/ci/drone.sh
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=linky_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


services:
  database:
    image: postgres:9.5
    environment:
    - POSTGRES_DB=linky_test
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
```

The build works when using docker compose based setups. However, when running `drone exec`, the build fail when trying to contact postgres at host `database`, with a `domain not accessible` error (`nxdomain`). I have put a `sleep 1000` in the build script and manually connected to the build container: 
- `ping database` fails because of the host being unknown.
- `cat /etc/hosts` doesn't show any entry named `database`.

However, if I replace the `POSTGRES_HOST=database` by `POSTGRES_HOST=localhost` in my build definition, everything works when running `drone exec`, and starts failing on the other using the docker-compose based setup.
