### ISSUE TITLE
[Feature] Proposal: sub-directory projects

### ISSUE THREAD

**Issue by kminehart** [drone/drone#2372]
Hi there!

A lot of people lately have switched to using monolithic repositories, especially for microservice-based architectures.

I developed a build / script runner that is fairly similar to a drone-agent. I'd love to move the functionality into Drone, and this would definitely bring something unique for Drone to the table.

Here's what I propose:

Let's say I have a single repository with multiple projects:

```
.
├── admin
├── errors.go
├── identity.go
├── internal
├── multicheck.go
├── models.go
├── sites
├── users
└── vendor
```

Where `users` and  `admin` are totally separate projects. They are kept in the same repository, though, because changes to one will almost always include changes to the other. If they were separate, multiple PRs would be involved.

There's also some shared code in `.` and `internal`, which needs to be tested.

Example `.drone.yml`:

```yaml
workspace:
  base: /go
  path: src/github.com/kminehart/drone

services:
  database:
    image: cockroachdb/cockroach:v1.1.2
    commands:
      - /cockroach/cockroach start --insecure

pipeline:
  test:
    image: golang:1.10
    commands:
      - make test
  publish:
    image: plugins/docker

# These projects are individual directories in the source tree which will be tested by the pipeline
# Any information like "commands", "image", "environment", etc. overrides what's defined by the pipeline.
# If left blank, then it assumes whatever information was provided by the original pipeline definition.
projects:
  root:
    path: "."
    pipeline:
      test:
        commands:
          - go test .
  admin:
    path: "./admin"
    pipeline:
      test:
        image: node:9.8
        commands:
          - yarn install
          - yarn test
      publish:
        image: node:9.8
        secrets: [ ssh_key, deploy_target ]
        commands:
          - yarn deploy
  internal:
    path: "./internal"
  users:
    path: "./users"
```

What does everyone think of this?

Some potential issues I see:

* Artifacts
* Caching
