### ISSUE TITLE
not login to GitLab

### ISSUE THREAD

**Issue by andruwa13** [drone/drone#2405]
docker-compose.yml:

```
version: '2'
services:
  server:
    image: drone/drone:0.8
    environment:
      DRONE_DEBUG: 'true'
      DRONE_GITLAB: 'true'
      DRONE_GITLAB_CLIENT: $CLIENT
      DRONE_GITLAB_SECRET: $SECRET
      DRONE_GITLAB_URL: https://gitlab.com
      DRONE_HOST: https://drone.webakcent.pro
      DRONE_OPEN: 'false'
      DRONE_SECRET: $SECRET_DRONE
      GIN_MODE: debug
      NO_PROXY: drone
      no_proxy: drone
    volumes_from:
    - server-volume
  agent:
    image: drone/agent:0.8
    environment:
      DRONE_SECRET: $SECRET_DRONE
      DRONE_SERVER: drone:9000
      NO_PROXY: drone
      no_proxy: drone
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    links:
    - server:drone
    command:
    - agent
  server-volume:
    image: rawmind/alpine-volume:0.0.2-1
    environment:
      SERVICE_GID: '0'
      SERVICE_UID: '0'
      SERVICE_VOLUME: /var/lib/drone
    network_mode: none
    volumes:
    - /var/lib/drone
```
1.
![edit drone applications user settings gitlab 2018-04-25 00-09-03](https://user-images.githubusercontent.com/5846351/39214372-ed68a088-481c-11e8-8dee-7d14bec43387.png)

2.

![user settings gitlab 2018-04-25 00-09-44](https://user-images.githubusercontent.com/5846351/39214446-25242ab0-481d-11e8-9ce2-a57dd73ebb0a.png)

3.

![login drone 2018-04-25 00-10-32](https://user-images.githubusercontent.com/5846351/39214457-2b2f63ca-481d-11e8-8c25-78516f049a47.png)

logs:
`25.04.2018 0:05:08time="2018-04-24T21:05:08Z" level=info ip=46.219.238.211 latency=1.207566ms method=GET path="/" status=200 time="2018-04-24T21:05:08Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:09time="2018-04-24T21:05:09Z" level=info ip=46.219.238.211 latency=561.99µs method=GET path="/api/user/feed" status=401 time="2018-04-24T21:05:09Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:09time="2018-04-24T21:05:09Z" level=debug msg="user feed: connection opened"
25.04.2018 0:05:09time="2018-04-24T21:05:09Z" level=info ip=46.219.238.211 latency=592.516µs method=GET path="/login" status=303 time="2018-04-24T21:05:09Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:09time="2018-04-24T21:05:09Z" level=info ip=46.219.238.211 latency=686.759µs method=GET path="/authorize" status=303 time="2018-04-24T21:05:09Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:17time="2018-04-24T21:05:17Z" level=error msg="cannot register 3_1_3_u. registration closed"
25.04.2018 0:05:17time="2018-04-24T21:05:17Z" level=info ip=46.219.238.211 latency=1.070437029s method=GET path="/authorize" status=303 time="2018-04-24T21:05:17Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:17time="2018-04-24T21:05:17Z" level=info ip=46.219.238.211 latency=642.262µs method=GET path="/login" status=303 time="2018-04-24T21:05:17Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:17time="2018-04-24T21:05:17Z" level=info ip=46.219.238.211 latency=682.257µs method=GET path="/login/error" status=200 time="2018-04-24T21:05:17Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:18time="2018-04-24T21:05:18Z" level=info ip=46.219.238.211 latency=139.264µs method=GET path="/api/user/feed" status=401 time="2018-04-24T21:05:18Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:05:18time="2018-04-24T21:05:18Z" level=debug msg="user feed: connection opened"
25.04.2018 0:05:39time="2018-04-24T21:05:39Z" level=debug msg="user feed: connection closed"
25.04.2018 0:05:39time="2018-04-24T21:05:39Z" level=info ip=46.219.238.211 latency=30.001118133s method=GET path="/stream/events" status=200 time="2018-04-24T21:05:39Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=info ip=46.219.238.211 latency=787.507µs method=GET path="/" status=200 time="2018-04-24T21:09:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=info ip=46.219.238.211 latency=655.352µs method=GET path="/api/user/feed" status=401 time="2018-04-24T21:09:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=debug msg="user feed: connection opened"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=info ip=46.219.238.211 latency=511.622µs method=GET path="/api/user/feed" status=401 time="2018-04-24T21:09:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=info ip=46.219.238.211 latency=615.463µs method=GET path="/login" status=303 time="2018-04-24T21:09:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:09:37time="2018-04-24T21:09:37Z" level=info ip=46.219.238.211 latency=570.041µs method=GET path="/authorize" status=303 time="2018-04-24T21:09:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:10:13time="2018-04-24T21:10:13Z" level=error msg="cannot register 3_1_3_u. registration closed"
25.04.2018 0:10:13time="2018-04-24T21:10:13Z" level=info ip=46.219.238.211 latency=1.119904068s method=GET path="/authorize" status=303 time="2018-04-24T21:10:13Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:10:14time="2018-04-24T21:10:14Z" level=info ip=46.219.238.211 latency=194.63µs method=GET path="/login" status=303 time="2018-04-24T21:10:14Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:10:14time="2018-04-24T21:10:14Z" level=info ip=46.219.238.211 latency=176.031µs method=GET path="/login/error" status=200 time="2018-04-24T21:10:14Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:10:14time="2018-04-24T21:10:14Z" level=info ip=46.219.238.211 latency=593.995µs method=GET path="/api/user/feed" status=401 time="2018-04-24T21:10:14Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:10:14time="2018-04-24T21:10:14Z" level=debug msg="user feed: connection opened"
25.04.2018 0:10:37time="2018-04-24T21:10:37Z" level=debug msg="user feed: connection closed"
25.04.2018 0:10:37time="2018-04-24T21:10:37Z" level=info ip=46.219.238.211 latency=1m0.002335811s method=GET path="/stream/events" status=200 time="2018-04-24T21:10:37Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
25.04.2018 0:11:14time="2018-04-24T21:11:14Z" level=debug msg="user feed: connection closed"
25.04.2018 0:11:14time="2018-04-24T21:11:14Z" level=info ip=46.219.238.211 latency=1m0.002620437s method=GET path="/stream/events" status=200 time="2018-04-24T21:11:14Z" user-agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"`
