### ISSUE TITLE
coding, version control system not configured

### ISSUE THREAD

**Issue by bysir-zl** [drone/drone#2408]
i use coding, but not work.

```
drone-server:
    image: drone/drone:0.8.2

    ports:
      - 8082:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    command: --coding=true
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_CODING=true
      - DRONE_CODING_CLIENT=${DRONE_CODING_CLIENT}
      - DRONE_CODING_URL=https://zzz.coding.net
      - DRONE_CODING_SECRET=${DRONE_CODING_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_ADMIN=bysir
```

when i run drone-server :
```
drone-server_1  | time="2018-04-26T01:58:52Z" level=fatal msg="version control system not configured" 
```

if i use `DRONE_GITHUB=true`, or `DRONE_GITEA=true`, i's work good.

i need help . please.
