### ISSUE TITLE
Insufficient privileges to use volumes

### ISSUE THREAD

**Issue by yunTerry** [drone/drone#2426]
Anyone who can tell me why I got this error ?

![default](https://user-images.githubusercontent.com/15991012/40883117-886c320a-6728-11e8-802e-785c96c7c230.png)

my docker volumes just set as usual :

```yaml
version: '2'
  drone:
    image: drone/drone
    ports:
      - 8000:8000
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://10.0.2.15
      - DRONE_GOGS=true
      - DRONE_GOGS_URL=http://10.0.2.15:3000
      - DRONE_SECRET=9dsk9
      - DRONE_ADMIN=terry

  drone-agent:
    image: drone/agent
    depends_on:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone:9000
      - DRONE_SECRET=9dsk9
```
