### ISSUE TITLE
Feature: fast-fail on parallel builds

### ISSUE THREAD

**Issue by surminus** [drone/drone#2443]
I would like to be able to set a fast-fail against a group of parallel pipeline steps to enable quicker feedback to developers.

As an example, we have our parallel pipeline steps:

```
pipeline:
  long_running_rspec:
    group: test
    image: foo/bar
  short_running_lint:
    group: test
    image: foo/bar
...   
```

If the `short_running_lint` step fails after 20 seconds, I'd like all the grouped steps to fail immediately, even if the `long_running_rspec` has another 5 minutes to run.
