### ISSUE TITLE
Support array in .drone.yml config

### ISSUE THREAD

**Issue by fudini** [drone/drone#2446]
Currently map is used to specify steps and map doesn't guarantee order.

So it would be nice to support syntax with an array like this:

```yaml
pipeline:
  - name: backend
    image: golang
    commands:
      - go build
      - go test
  - name: frontend
    image: node
    commands:
      - npm install
      - npm run test
      - npm run build
```
