### ISSUE TITLE
Feature proposal : Shared steps

### ISSUE THREAD

**Issue by maximelebastard** [drone/drone#2450]
I'd like to discuss a way to share some common steps (like Slack or cache) between repositories. If we agree on the idea, I will submit a PR.

**Use case**

Between forks and main repositories, I have 30 projects in the CI. I notice that some build steps are present in all of them. They can be about:
- Slack notifications
- Yarn cache
- Downloading some required environment files before the build
- Uploading generated documentation

Having those steps in 30 repositories, multiply the number of branches make them hard to maintain. I'd like to have a way to write them somewhere, and being able to call them in all my repositories.

**Goals**

- Don't repeat our basic steps
- Being able to update a common step quickly and easily, without having to update all the repositories
- A start point for a common drone.yml configuration for all the repositories

**Proposal**

- Add global.drone.yml file. The content of this global.drone.yml file would be passed to drone through a volume
```yaml
# Host docker compose
services:
 drone-server:
    image: drone/drone:latest
    volumes:
      - ./drone-data:/var/lib/drone/
      - ./global.drone.yaml:/var/lib/drone/global.drone.yaml
    restart: always
    ports:
      - 9000:9000
    environment:
      - DRONE_ORGS=${DRONE_ORGS}
      - DRONE_SECRET=${DRONE_SECRET}
      - ...
```

- This drone.yml file would expose shared steps
```yaml
# global.drone.yml

sharedsteps:
  slack-failure:
    image: plugins/slack
    secrets: [slack_webhook]
    username: drone
    template: >
        build {{build.number}} failed. Fix me please.
    when:
      status: [failure]

  publish-doc:
    image: alpine
    volumes:
      - doc:/mnt/doc
    commands:
      - cp ./docs doc/${DRONE_REPO_NAME}/${DRONE_COMMIT_BRANCH}

  restore-yarn-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
      - /usr/local/share/.cache/yarn
    volumes:
      - cache:/cache

  rebuild-yarn-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
      - /usr/local/share/.cache/yarn
    volumes:
      - cache:/cache
    when:
      event: [push]
```

- Then, on our repositories drone.yml  files, we would be able to call our shared steps
```yaml
# myproject/drone.yaml
pipeline:
  restore-cache:
    sharedstep: restore-yarn-cache

  dependencies:
    image: node:latest
    environment:
      NODE_ENV: test
    commands:
      - yarn install
    when:
      event: [push]

  test:
    image: node:latest
    commands:
      - yarn test
    when:
      event: [push]

  notify:
    sharedstep: slack-failure
    when:
      event: push
```
