### ISSUE TITLE
Expose DRONE_PREV_BUILD_STATUS to conditionals

### ISSUE THREAD

**Issue by verbruggenalex** [drone/drone#2452]
I would like to propose to expose DRONE_PREV_BUILD_STATUS to the conditionals of the pipeline. This would allow us to skip certain steps for a repeat successful build. The use case for this is ephemeral demo environments.

If you complete a build successfully. When requesting a rebuild through the REST api you can skip all build steps and just set up the cached build. Then exposed it trough a tunnel. And voila. You have super fast demo environments that people can use in sprint reviews.

@bradrydzewski is this something you would be open to? Maybe we could even expose all available environment variables and allow people to do string comparisons on them.

**Comment by verbruggenalex** [comment]
Sorry, just noticed they are available throug the matrix:
```
     image: fpfis/drone-frpc-plugin:latest
     when:
      matrix:
         - DRONE_PREV_BUILD_STATUS=success
     secrets: [ frpc_token, frpc_server ]
     environment:
```
Closing support issue.

**Comment by verbruggenalex** [comment]
Sorry, I was mistaken. Even on matrix I can not use ENV vars as conditionals.

**Comment by bradrydzewski** [comment]
We are not planning on adding any new conditional fields, however, I am planning to add an eval field that lets you construct a boolean statement to determine if the step should be executed. Such an eval statement would have access to all 20+ fields.

Example:

```
pipeline:
  build:
    image: golang
    commands:
    - go build
    - go test
    when:
      eval: |
        event == 'push' and branch == 'master'
```
