### ISSUE TITLE
Execute a step if the build event is a tag created from the specified branch

### ISSUE THREAD

**Issue by suconghou** [drone/drone#2453]
According the document http://docs.drone.io/step-conditions/

```
pipeline:
  build_release:
    image: suconghou/node:dev
    commands:
      - yarn run release
    volumes:
      - /var/lib/node:/var/lib/node
    when:
      event: tag
      branch: release
  build_dev:
    image: suconghou/node:dev
    commands:
      - yarn run build
    volumes:
      - /var/lib/node:/var/lib/node
    when:
      branch: develop

branches: [ release, develop ]
```

in branch release

```
git add .
git commit -m "words"
git tag -a v1.1 -m "hi"
```

`git push origin release --tags` doest not trigger build_release 

`Repository Hooks` I have already checked the push and tag checkbox

is it correct ?
