### ISSUE TITLE
drone always suddenly in pending state

### ISSUE THREAD

**Issue by AaronFSJ** [drone/drone#2458]
As shown in the question,at first it was normal,after a few times,it alway suddenly in pending state,just like that
![image](https://user-images.githubusercontent.com/23305845/43196007-38290540-9039-11e8-9ea3-eff9baba010a.png)

Deploy with Docker Stack
```yml
version: "3"

services:
  drone-server:
    image: drone/drone

    ports:
      - 8999:8000
      - 9000
    volumes:
      - drone:/var/lib/drone
    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST=http://localhost:8999
      - DRONE_GITLAB=true
      - DRONE_GITLAB_CLIENT=24fbdfd9978f6XXXXXX49f55b51316d3d7684d0b00b195884c08781
      - DRONE_GITLAB_SECRET=59XXXXXe28cd8f0c858fb3afecf52342
      - DRONE_GITLAB_URL=http://localhost
      - DRONE_SECRET=mytest2018

  drone-agent:
    image: drone/agent

    deploy:
      replicas: 1
      restart_policy: 
        condition: on-failure
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=mytest2018

volumes:
  drone:
    driver: local
```
Who has met such a problem, and how do you solve  it? 

Best wishes to you!
