### ISSUE TITLE
Blank page after installation

### ISSUE THREAD

**Issue by welljsjs** [drone/drone#2469]
Docker version: 18.06.0-ce
Drone version: drone-server version 0.8.6+build.

I installed drone on my RPI the following way: 
1. `go get github.com/drone/drone/cmd/...`
2. `go build -ldflags '-extldflags "-static" -X github.com/drone/drone/version.VersionDev=build.'${DRONE_BUILD_NUMBER} -o release/drone-server github.com/drone/drone/cmd/drone-server`
3. `docker -f ./go-workspace/src/github.com/drone/drone/Dockerfile build -t drone/drone .`

My docker-compose.yml: 
```
version: '2'

services: 
    drone-server: 
        image: drone/drone:latest
        ports: 
            - 8000:8000
            - 9000:9000
        volumes: 
            - /var/lib/drone:/var/lib/drone
        restart: always
        env_file: 
            - /etc/drone/server.env

    drone-agent: 
        image: drone/agent:linux-arm
        command: agent
        depends_on: 
            - drone-server
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        restart: always
        env_file: 
            - /etc/drone/agent.env
```

server.env: 

```
DRONE_SECRET=xxx
DRONE_HOST=https://[server-hostname]:8000
DRONE_OPEN=true

DRONE_GOGS=true
DRONE_GOGS_URL=https://[server-hostname]/git
DRONE_GOGS_PRIVATE_MODE=false
```

agent.env

```
DRONE_SECRET=xxx
DRONE_SERVER=drone-server:9000
DOCKER_ARCH=arm
```

Then I started drone: 

    docker-compose -f /etc/drone/docker-compose.yml up

The start seems to be successful, there are no error messages, just one message that tells that it's running in debug mode and lots of other messages that look like so: 

    [GIN-debug] PATCH  /api/repos/:owner/:name   --> github.com/drone/drone/server.PatchRepo (16 handlers)

However, when accessing https://[server-hostname]/drone in my browser, everything I see is a blank (white) page. 
The page returns two 404 errors:
`https://[server-hostname]/static/vendor.fc7f2b27186ea985e44c.js`
`https://[server-hostname]/static/bundle.467f73292ec23d1702cb.js`
