### ISSUE TITLE
Gitea integration using wrong URLs

### ISSUE THREAD

**Issue by AragurDEV** [drone/drone#2470]
I am running a drone ci instance using the following docker-compose.yml
```
version: '2'

networks:
  drone:
    external: false
  proxy:
    external:
      name: proxy

services:
  drone-server:
    image: drone/drone:0.8
    expose:
      - 8000
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
    restart: always
    networks:
      - proxy
      - drone
    environment:
      - DRONE_OPEN=true
      - DRONE_HOST={{REMOVED}}
      - DRONE_SECRET={{REMOVED}}D
      - DRONE_GITEA=true
      - DRONE_GITEA_URL={{REMOVED}}
      - DRONE_GITEA_GIT_USERNAME=Drone
      - DRONE_GITEA_GIT_PASSWORD={{REMOVED}}
      - DRONE_GITEA_PRIVATE_MODE=true


  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    networks:
      - drone
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET={{REMOVED}}
```

After pushing into a activated repository Gitea shows the build status.
![Example image](https://user-images.githubusercontent.com/11004008/44058996-32bb097a-9f50-11e8-9d06-65a1e2cc26cb.png)
If the build succeeded the URL is working as expected (Redirecting to the defined DRONE_HOST)
But if a build is still pending or fails the URL redirects to http://drone-server:8000/

I don't think this is an intended behavior.
If you need any other details or configuration, let me know.
