### ISSUE TITLE
gitlab failed to activited your resposity

### ISSUE THREAD

**Issue by niejian** [drone/drone#2481]
Hi, boss:
 when I using drone and gitlab. after authorization, to active my resposity, it said: failed to activited your resposity. but it didnt encounter by every resposity. How to solve it.
Here is yml
```yaml
version: '2'

services:
  drone-server:
    image: drone/drone:0.8

    ports:
      - 8080:8000
      - 9000
    volumes:
      - /var/lib/drone:/var/lib/drone/
    restart: always
    environment:
      - DRONE_OPEN=true
      - DRONE_ADMIN=niejian
      - DRONE_HOST=${DRONE_HOST}
      - DRONE_GITLAB=true
      - DRONE_GITLAB_URL=http://192.168.242.147:8888
      - DRONE_GITLAB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITLAB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_ADMIN=bysir-zl

  drone-agent:
    image: drone/agent:0.8

    command: agent
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
```
THX
