### ISSUE TITLE
[Feature] Drone jobs for individual subdirectories in a repo

### ISSUE THREAD

**Issue by mellena1** [drone/drone#2490]
Hi all,

I was wondering if a feature to have multiple Drone jobs for a single repository was possible at some point in the future. We have a large repo with multiple infrastructure related Jenkins jobs, and ideally we would like to move them to Drone. Right now with Jenkins we trigger them off of a push to the repo and Jenkins has a plugin to check if a specific subdirectory/specific files had changed at all in that commit.

I could see this working as having one main .drone.yml file in the root of the directory, and in that file having some sort of syntax like:
```yaml
pipeline:
  mydir-job:
    image: plugins/run-another-file
    file-to-run: mydir/.drone.yml
    when:
      changed-files:
      - mydir/*
      - thisdir/myfile
```

I have considered writing a plugin for looking for changed files in a commit, but as far as I have found, drone does not have any sort of call to execute a specific drone file.

I have read that this wasn't included originally because of how drone is triggered based off of repo-level events, but I could see this being a useful addition to the platform.

Interested to hear your thoughts. Thanks.
