### ISSUE TITLE
Add custom command into "when:" property for runtime-decision of stage execution

### ISSUE THREAD

**Issue by vityafx** [drone/drone#2496]
It would be very nice if we had an opportunity to detect whether to execute some stage at the runtime, like, we don't check the code if it was not changed (talking about rust and `cargo clippy`):

```yaml
  cargo-clippy:
    when:
      command: <any custom command here>
```

This would help a lot to not waste CI's time doing useless stuff like checking already checked code or doing anything else which is not needed due to some reason.
