### ISSUE TITLE
Add an opportunity to retry stages several times if it fails

### ISSUE THREAD

**Issue by vityafx** [drone/drone#2497]
It would be nice to have a `retry:` property which could specify a number of attempts after stage failure, for example:

```yaml
  upload-to-github-releases:
    # ...
    retry: 3  # 3 attempts will be made if there are any issues (network, github infra, etc)
```
