### ISSUE TITLE
anchor don't seem good

### ISSUE THREAD

**Issue by shaocongliang** [drone/drone#2507]
here is my yaml
````yaml
  PREFIX: &id
    image: plugins/docker
    group: publish
    username: scliang
    password: scliang 
    registry: xxxx
    email: scliang@xxx.com
    insecure: true  

  dispatch:
    <<: *id
    repo: foo
    tag: 0.9.8
    dockerfile: bar
````
the build output:
![image](https://user-images.githubusercontent.com/30583506/46802307-8a5a6f00-cd8f-11e8-8765-29326f49d676.png)

How can I take out PREFIX section in build step?
