### ISSUE TITLE
Commands truncated

### ISSUE THREAD

**Issue by sloonz** [drone/drone#2509]
(note: `abcdefghijk` and `abcdefghi` are redacted names that preserve the length of the original names)

This .drone.yml job started failing after adding `ormconfig.js` int the rsync command. The weird thing is that it was the last step, unchanged, that started to fail (sudo asking a password, despite this specific command being allowed for this specific user in sudoers)

```
pipeline:
  build:
    image: node:10
    commands:
      - npm install
      - npm run build

  deploy:
    image: instrumentisto/rsync-ssh
    volumes:
      - /opt/drone/ssh:/root/.ssh
    commands:
      - ssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; rm -rf node_modules"
      - rsync -av --delete build/ ormconfig.js package.json sys-abcdefghi-app@prod.abcdefghijk.com:node/
      - ssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; NODE_ENV=production npm install"
      - ssh sys-abcdefghi-app@prod.abcdefghijk.com sudo systemctl restart nodejs@sys-abcdefghi-app.service
    when:
      branch: drone-bug
```

After a bit of research, it looks like the command is truncated. When replacing the command block with this : 

```
    commands:
      - |
	set -xe
        ssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; rm -rf node_modules"
        rsync -av --delete build/ ormconfig.js package.json sys-abcdefghi-app@prod.abcdefghijk.com:node/
        ssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; NODE_ENV=production npm install"
        ssh sys-abcdefghi-app@prod.abcdefghijk.com echo sudo systemctl restart nodejs@sys-abcdefghi-app.service
	printenv
```

1. The first line of the log has the whole command, not truncated : 

```
+ set -xe\nssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; rm -rf node_modules"\nrsync -av --delete build/ ormconfig.js package.json sys-abcdefghi-app@prod.abcdefghijk.com:node/\nssh sys-abcdefghi-app@prod.abcdefghijk.com "cd node; NODE_ENV=production npm install"\nssh sys-abcdefghi-app@prod.abcdefghijk.com echo sudo systemctl restart nodejs@sys-abcdefghi-app.service\nprintenv\n
```

2. The first three commands  (ssh, rsync, ssh npm install) runs correctly

3. The fourth command is truncated : 

```
+ ssh sys-abcdefghi-app@prod.abcdefghijk.com echo sudo systemctl restar
sudo systemctl restar
```

4. The fifth command appears nowhere

5. Without the `echo` (before `sudo systemctl`), `sudo systemctl restart node` is called, which makes the job fail (because the user is not allowed to restart node in sudoers, only nodejs@sys-abcdefghi-app.service). Therefore it’s probably not just a logs issue like #1941.

6. Putting all the commands in a `deploy.sh` script and just calling the script in the commands block works fine, and is my current workaround.

System information : 

* Docker version 18.06.1-ce, build e68fc7a215
* drone/agent                0.8                 ea280fb03b0a
* drone/drone                0.8                 cd7706b4a114

**Comment by bradrydzewski** [comment]
I was unable to reproduce, but would certainly accept a patch if you can identify a problem area in the code.

**Comment by charliebravodev** [comment]
Same problem here. Your YAML parsers is truncating some commands.

.drone.yml
```
steps:
  - name: build
    image: docker
    volumes:
      - name: dockerd
        path: /var/run/docker.sock
```

Which gives us:
![screenshot 2019-03-01 at 11 51 30](https://user-images.githubusercontent.com/37196867/53633682-76b58500-3c18-11e9-85df-febf2cb1513e.png)

Notice the `.soc` which misses the "k".

We had a similar problem with the Docker drone plugin, which tagged our images "lates" instead of "latest". Thought it was a problem with the plugin, but having it happen a second time makes me realise it's an issue with the YAML parser.

Workaround:
```
steps:
  - name: build
    image: docker
    volumes:
      - name: dockerd
        path: "/var/run/docker.sock"
```

Not opening issues at discourse, GitHub issues are made for this.
