### ISSUE TITLE
"Invalid or missing image" when "when:" block is formatted incorrectly

### ISSUE THREAD

**Issue by Maciek416** [drone/drone#2511]
Drone 0.85 will fail a build with the error `invalid or missing image` if a `when:` line is outdented incorrectly away from its block.

The build error should relate to the incorrectly-formatted `when:` line.

Repro yaml:

```yaml
pipeline:

  build_always:
    image: alpine
    commands:
      - echo "hello always"

  build_sometimes:
    image: alpine
    commands:
      - echo "hello sometimes"
  # When incorrectly formatted like this, error message in 0.85 is "Invalid or missing image"
  when:
      status: [ success ]
      event: push
      branch: master
```
