### ISSUE TITLE
Drone agent restarting

### ISSUE THREAD

**Issue by gboddin** [drone/drone#2513]
From [Discourse](https://discourse.drone.io/t/drone-agent-restarting/2641) :

Hello,

I have encountered a bug with the Drone Agent where it restarts when facing a particular .drone.yml pipeline :

I have checked the Agent logs and found this:
```
{"time":"2018-09-19T09:30:23Z","level":"debug","repo":"CaliOpen/Caliopen","build":"90","id":"4557","error":"","exit_code":0,"message":"updating pipeline status"}
{"time":"2018-09-19T09:30:23Z","level":"debug","repo":"CaliOpen/Caliopen","build":"90","id":"4557","message":"stop listening for cancel signal"}
{"time":"2018-09-19T09:30:23Z","level":"debug","repo":"CaliOpen/Caliopen","build":"90","id":"4557","message":"updating pipeline status complete"}
{"time":"2018-09-19T09:30:23Z","level":"debug","message":"request next execution"}
{"time":"2018-09-19T09:30:23Z","level":"debug","repo":"CaliOpen/Caliopen","build":"90","id":"4557","message":"pipeline done"}
panic: runtime error: index out of range

goroutine 24 [running]:
main.(*runner).run(0xc420486280, 0xbf1e40, 0xc420207780, 0x0, 0x0)
	/go/src/github.com/drone/drone/cmd/drone-agent/agent.go:182 +0x170d
main.loop.func2(0xc4202af010, 0xc4202aee9c, 0xbf43a0, 0xc42027cee0, 0xc4201d1a40, 0x0, 0x0, 0xc4202aef70, 0xc4202aefd0)
	/go/src/github.com/drone/drone/cmd/drone-agent/agent.go:132 +0x193
created by main.loop
	/go/src/github.com/drone/drone/cmd/drone-agent/agent.go:137 +0x910
{"time":"2018-09-19T09:30:24Z","level":"debug","message":"request next execution"}
panic: runtime error: index out of range
```

The drone.yml can be found [here](https://github.com/CaliOpen/Caliopen/blob/develop/.drone.yml) .

Another report includes where the error occurs during a deploy hook : 

During deployment :

Works :
```
clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
  git:
    image: fpfis/true
    when:
      event: [ deployment ]
```

fails :
```
clone:
  git:
    image: plugins/git:next
    when:
      event: [ push, pull_request, tag ]
```

Some debugging lead me to https://github.com/drone/drone/blob/master/cmd/drone-agent/agent.go#L478 , where stages seems to be unset.

I thought the source was the usage of a custom clone logic but another user reports he's just using matrices.

Thank you for your help!
