### ISSUE TITLE
1.0.0-rc.1: "npm insta"

### ISSUE THREAD

**Issue by boredland** [drone/drone#2523]
My pipeline looks like this:
```
kind: pipeline
name: default

steps:
- name: build
  image: node:8-alpine
  commands:
  - npm install
```
Drone logs the following:
```
+ npm insta

Usage: npm <command>

where <command> is one of:
...
npm@6.4.1 /usr/local/lib/node_modules/npm

Did you mean one of these?
    init
    install
    unstar
```
So clearly the "ll" went missing somewhere.

**Comment by boredland** [comment]
My first try to work around was to escape the line like that:
```
kind: pipeline
name: default

steps:
- name: build
  image: node:8-alpine
  commands:
  - "npm --verbose install"
```
That leads the project to not even start the "default" pipeline (thus not even showing stages or error output), not relevant debugging info either.
