### ISSUE TITLE
Wrong host path when converting 0.8 .drone.yml to 1.0

### ISSUE THREAD

**Issue by jhasse** [drone/drone#2539]
Converting the following `.drone.yml`

```yml
pipeline:
  build:
    volumes:
      - /host:/foo
```

with `drone convert` results in:

```yml
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: default
  volumes:
  - name: 2f686f7374
    path: /foo

volumes:
- name: 2f686f7374
  host:
    path: /foo
```

But that last path should be `/host` instead. This results in the error message `Error response from daemon: invalid mount config for type "bind": bind source path does not exist` when running the build as the path on the host doesn't exist.
