### ISSUE TITLE
Login Failed. Error 1054: Unknown column 'user_machine' in 'field list'

### ISSUE THREAD

**Issue by newgoo** [drone/drone#2551]
this is my compose file 
```
version: "3"
services:
  mysql:
    image: mysql:5.7
    volumes:
    - /data1/mysql/5.7:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=*****
    ports: 
      - 3306:3306
  drone-server:
    image: drone/drone:1.0.0-rc.1
    container_name: drone_server
    ports:
    - "10080:80"
    - "10081:443"
    environment:
      - DRONE_OPEN=true
      - DRONE_GOGS=true
      - DRONE_DEBUG=false
      - DRONE_PROVIDER=gogs
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_SERVER_HOST=http://0.0.0.0
      - DRONE_GOGS_SERVER=http://172.18.246.3:3000
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_ADMIN=admin
      - DRONE_RPC_SECRET=*****
      - DRONE_LOGS_DEBUG=true
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=********
    restart: always
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data1/drone/data:/data
    depends_on: 
    - mysql
  drone-agent:
    image: drone/agent:1.0.0-rc.1
    container_name: drone_agent
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - drone-server
    - mysql
    restart: always
    environment:
      - DRONE_RPC_SERVER=http://drone-server:9000
      - DRONE_RPC_SECRET=*****
      - DRONE_LOGS_DEBUG=true
      - DOCKER_HOST=tcp://docker-bind:2375
  docker-bind:
    image: docker:dind
    privileged: true
    command: --storage-driver=overlay
    container_name: docker_bind
```
