### ISSUE TITLE
E-mail plugin reports build as succesfull even though other pipelines failed

### ISSUE THREAD

**Issue by jhasse** [drone/drone#2553]
After updating to 1.0 I've converted a matrix build to a multi-machine with a notify step which depends on the previous pipelines, similar to what is suggested here: https://docs.drone.io/user-guide/pipeline/multi-machine/

Instead of Slack, I'm using the e-mail plugin though:

```yaml
---
kind: pipeline
name: notify

clone:
  disable: true

steps:
- name: notify
  image: drillster/drone-email
  settings:
    # ...

depends_on:
- pipeline_a
- pipeline_b

trigger:
  status:
  - failure
```

Even though all pipeline_a and pipeline_b failed, I'm getting an email with the message "Successful build #xy". I guess this is because the plugin gets the status of its own machine / pipeline, not the status of the whole build?

**Comment by bradrydzewski** [comment]
the `status` is local to each pipeline

**Comment by jhasse** [comment]
Any idea how the email (or any notification) plugin can be used to inform about the job status?

**Comment by jhasse** [comment]
Awesome! Thank you :)

I guess this will be part of rc.7, right?

**Comment by bradrydzewski** [comment]
the fix is available in `:latest` and will be available in `1.0.0-final`

**Comment by jhasse** [comment]
I've tested it now with `1.0.0` and unfortunately the notify pipeline gets skipped now, even if one of the other pipelines failed. https://docs.drone.io/user-guide/pipeline/multi-machine/ mentions that `depends_on:` mentions "The pipeline does not execute until the dependent pipelines **successfully** complete.". Maybe that's why?

**Comment by bradrydzewski** [comment]
works for me https://cloud.drone.io/drone/hello-world/37/2/2

**Comment by jhasse** [comment]
Thanks, I will try to narrow down what exactly is going wrong at my end.

Is there a way to see the reason, a pipeline is skipped?

**Comment by lukatera** [comment]
> Thanks, I will try to narrow down what exactly is going wrong at my end.
> 
> Is there a way to see the reason, a pipeline is skipped?

you're likely missing 
```
trigger:
  status: [success, failure]
```
in your notification pipeline

**Comment by jhasse** [comment]
I've found the issue: The `notify` step get's skipped if `pipeline_b` finishes before `pipeline_a` (you'll need multiple agents for that to happen). Here's a `.drone.yml` to reproduce the problem:

```yaml
---
kind: pipeline
name: pipeline_a

steps:
- name: build
  image: alpine
  commands:
  - sleep 10
  - exit 1

---
kind: pipeline
name: pipeline_b

steps:
- name: restore-cache
  image: alpine
  commands:
  - exit 0

---
kind: pipeline
name: notify

steps:
- name: notify
  image: alpine
  commands:
  - exit 0

depends_on:
- pipeline_a
- pipeline_b

trigger:
  status:
  - failure
...
```
