### ISSUE TITLE
Not able to clone in isolated docker

### ISSUE THREAD

**Issue by vitalik** [drone/drone#2559]
See conversation here https://discourse.drone.io/t/could-not-resolve-host-on-clone-step/3311

It seems there is a miss of some configuration variable (or documentation ?)

When I have this docker-compse with Drone+GITEA - my clone step fails with "**Could not resolve host: gitea**"

```
version: '2'
services:
  gitea:
    image: gitea/gitea:latest
    volumes:
      - ./data/gittea:/data
    ports:
      - "3000:3000"
      - "2222:22"
  
  drone-server:
    image: drone/drone:1.0.0-rc.3
    depends_on:
      - gitea
    ports:
      - "8000:80"
    volumes:
      - ./data/drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=drone-server
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
```
