### ISSUE TITLE
Kubernetes temporary volumes use all same hostpath

### ISSUE THREAD

**Issue by everflux** [drone/drone#2581]
I am using the Kubenetes executor for drone.
This is a snipped from the drone.yml

```
services:
- name: foo
  image: bar
  ...
  volumes:
  - name: foo
    path: /var/lib/foo
  - name: bar
    path: /data
  - name: baz
    path: /tmp/cache

volumes:
- name: foo
  temp: {}
- name: bar
  temp: {}
- name: baz
  temp: {}
```

The resulting kubernetes pod spec

```
 "spec": {
    "volumes": [
      {
        "name": "b9t3ruvez9zrvw828y46jyydk90ety93",
        "hostPath": {
          "path": "/tmp/drone/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx",
          "type": "DirectoryOrCreate"
        }
      },
      {
        "name": "odbfsvn0obxbar794eko88hzkljw6k2n",
        "hostPath": {
          "path": "/tmp/drone/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx",
          "type": "DirectoryOrCreate"
        }
      },
      {
        "name": "gr3hctwvm4kjettjsm0evx10mk5vqf5l",
        "hostPath": {
          "path": "/tmp/drone/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx/k4xzoklmyt0rbsrsiw2ec2wluxkyfycx",
          "type": "DirectoryOrCreate"
        }
      }
    ],
...
"volumeMounts": [
          {
            "name": "b9t3ruvez9zrvw828y46jyydk90ety93",
            "mountPath": "/var/lib/foo"
          },
          {
            "name": "odbfsvn0obxbar794eko88hzkljw6k2n",
            "mountPath": "/data"
          },
          {
            "name": "gr3hctwvm4kjettjsm0evx10mk5vqf5l",
            "mountPath": "/tmp/cache"
          }
        ],
```
This leads to the problem that the data is all mixed in the same directory.
