### ISSUE TITLE
Support for Starlark

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2585]
Experiment with support for Starlark as a configuration language. This could be integrated in the CLI like jsonnet or it could be integrated natively into Drone, depending on how useful it is.

* https://docs.bazel.build/versions/master/skylark/language.html
* https://github.com/bazelbuild/examples/blob/master/android/firebase-cloud-messaging/app/BUILD#L9
* https://github.com/stripe/skycfg

```
load("//config/common/pipeline.sky",  "pipeline")

def main(ctx):
  return [
    pipeline(ctx, os = 'linux', arch='amd64', name='amd64'),
    pipeline(ctx, os = 'linux', arch='arm64', name='arm64),
    pipeline(ctx, os = 'linux', arch='arm', name='arm32'),
  ]
```

**Comment by bradrydzewski** [comment]
basic support added to CLI for further testing.

**Comment by bradrydzewski** [comment]
here is a basic example of a starlark script:

```python
def main():
  return {
    'kind': 'pipeline',
    'name': 'default',
    'steps': [
      build('1.11'),
      build('1.12'),
    ]
  }

def build(version='1.11'):
  return {
    'image': 'golang:%s' % version,
    'name': 'build %s' % version,
    'commands': [ 'go build', 'go test -v' ]
  }
```

that will generate the following yaml:

```
---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build 1.11
  image: golang:1.11
  commands:
  - go build
  - go test -v

- name: build 1.12
  image: golang:1.12
  commands:
  - go build
  - go test -v

...
```

I think some remaining items to solve are:

1. what should the file name / extension be?
2. how do we pass information to the script (branch, event, etc) for conditions?

For the latter, I am thinking we pass a context to the main method that is a Go structure, containing the repository and build details:

```
```diff
-def main():
+def main(ctx):
  return {
    'kind': 'pipeline',
    'name': 'default',
    'steps': [
      build('1.11'),
      build('1.12'),
    ]
  }
```
