### ISSUE TITLE
"go test ./..." meet error

### ISSUE THREAD

**Issue by soolaugust** [drone/drone#2614]
When I try to using 'go test ./...' within .drone.yml, it will meet error sometimes:

`.drone.yml`

```yaml
kind: pipeline
name: default

workspace:
  base: /go
  path: src/ai-apiserver

steps:
- name: test
  image: golang:1.11
  commands: 
  - go test ./...
```

and the result of `activity feed` is as following:

![image](https://user-images.githubusercontent.com/10558124/53536449-739b9580-3b41-11e9-9f32-f277ee2e8fd4.png)

Any idea about this?
