### ISSUE TITLE
Feature request: from_file and from_variable in plugins' settings

### ISSUE THREAD

**Issue by smnbbrv** [drone/drone#2625]
Hi guys,

you made an awesome product, I love it!

There are some plugins that require large content to be passed in the settings, e.g. CI success message pattern. That is why the a feature I am missing is something similar to `from_secret` but `from_file` and `from_variable` in the settings of plugins.

Example of what I would like to have:

```
steps:
- name:
  image: plugins/telegram
  settings:
    message:
      from_file: .drone-telegram-message.md
```

I asked this on [discourse](https://discourse.drone.io/t/using-from-file-and-from-variable-in-plugins-settings/4010) but didn't get any answer, so I assume it is not implemented yet.
