### ISSUE TITLE
error for deploy multi drone-agent to one mac-mini

### ISSUE THREAD

**Issue by v7lin** [drone/drone#2629]
deploy multi drone-agent
````
version: "3.7"

services:

  drone-agent:
    container_name: drone-agent
    image: drone/agent:1.0.0
    restart: always
    hostname: drone-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone.${SERVER_DOMAIN}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_CAPACITY=2

  drone-agent-mac:
    container_name: drone-agent-mac
    image: drone/agent:1.0.0
    restart: always
    hostname: drone-agent-mac
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone.${SERVER_DOMAIN}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
      - DRONE_RUNNER_LABELS=os:mac
````

run multi stages build task
````
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: hello-world
  image: hello-world

---
kind: pipeline
name: mac

clone:
  disable: true

steps:
- name: hello-world
  image: hello-world

node:
  os: mac
````

error logs
````
default: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
````
