### ISSUE TITLE
Allow user to run a image with a specific user at a certain step.

### ISSUE THREAD

**Issue by XhstormR** [drone/drone#2651]
I use Drone CI Service to start gradle image to build software. But gradle image run as gradle user insted of root user by default. However, only the root user has write access in the /drone/src directory. I spent an afternoon trying to solve this problem, finally I switched to openjdk:latest image.

Is there a way to run as specific user with a image in some step, like this:
```
steps:
- name: build
  user: root #specific user
  image: gradle:latest
  commands:
- ./gradle assemble
```

[This link](https://github.com/keeganwitt/docker-gradle/issues/93) has more information if you need it.
