### ISSUE TITLE
documentation example  leads to "duplicate step names"

### ISSUE THREAD

**Issue by vitalik** [drone/drone#2665]
I'm following .drone.yml example from here (trying to make my own clone step)

https://docs.drone.io/user-guide/pipeline/cloning/

```
kind: pipeline
name: default

clone:
  disable: true

steps:
- name: clone
  image: docker:git
  commands:
  - git clone https://github.com/octocat/hello-world.git
  - git checkout $DRONE_COMMIT

- name: build
  image: golang
  commands:
  - go build
  - go test
```

but it gives an error : 

> linter: duplicate step names
