### ISSUE TITLE
Yaml command multiline regression

### ISSUE THREAD

**Issue by Tchoupinax** [drone/drone#2688]
Hello,

Multi line is not supported since version 1.1.0.
In my yaml, i have this : 

```yaml
  deploy:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands: |
      docker run -d \
      --name foo \
      foo/foo
```

and in my drone build i had this 
`run -d \\n -name foo \\n foo/foo`

But with the version 1.1.0, i have this 
`run -d \n --name foo \n foo/foo`

`\n` are not correctly escaped so i have this error: `Unable to find image 'n:latest' locally`. Tried to compare branches to see where is the mistake but i did not find.
Could you fix it ? :)

Thank you.
