### ISSUE TITLE
How to add ssh key to drone plugin

### ISSUE THREAD

**Issue by KingzCheung** [drone/drone#2692]
I need to use the ssh key clone library in the drone plugin.For example php project, I need to use the composer command to clone a private warehouse. My current solution is to use a script to parse the parameters passed in the env parameter and generate the ssh_key file.

我需要在插件中添加 ssh key 来下载一些私有类库，比如php项目中，我需要在镜像中添加一个ssh key 才能下载项目中的私有仓库类库代码，我目前的方案是使用通过docker 的env 来把ssh key 传入镜像，并通过脚本来生成ssh key。

```
FROM composer:latest
ENV PHPREDIS_VERSION 4.2.0

#RUN ...

ADD ./drone-php /bin/

ENTRYPOINT ["/bin/drone-php"]
```

drone-php:

```go

```

.drone.yml:

```
- name: add key
    image: bbking/composer:latest
    settings:
      private_key:
        from_secret: ssh_key
      public_key:
        from_secret: pub_ssh_key
    commands:
      - ls -lah  /root/.ssh
```
But I did not see the expected results:
但是这个方案好像在drone中并不起作用。

```
+ ls -lah /root/.ssh
--
2 | total 8
3 | drwxr-xr-x 2 root root 4.0K May 2 14:10 .
4 | drwx------ 1 root root 4.0K May 3 05:20 ..

```
My understanding of docker is not good enough. I want to know how I should safely put the ssh key into the image.

我对docker的了解不够好，我想知道类似于这样的需求我应该怎么样安全的把ssh key 打入镜像?

When I tested it locally, it was the normal generation of ssh key.
 我本地测试的时候，它是正常生成ssh key 的。

**Comment by metalmatze** [comment]
That's because the key is passed into the container as a environment variable: `PRIVATE_KEY` and `PUBLIC_KEY`.
At the beginning of that step, try to run the command `echo $PRIVATE_KEY > /root/.ssh/private` and the same for the public key.

**Comment by KingzCheung** [comment]
> That's because the key is passed into the container as a environment variable: `PRIVATE_KEY` and `PUBLIC_KEY`.
> At the beginning of that step, try to run the command `echo $PRIVATE_KEY > /root/.ssh/private` and the same for the public key.

So this is the issue of the order of execution? Is there a solution?

**Comment by metalmatze** [comment]
No it's not really a issue of the order of execution, but the public key being passed as a string via envvar and not being written to disk, so you need to do that by read from the envvar. 
Then you should be able to move forward by reading from disk.

**Comment by runejuhl** [comment]
I've just done a similar thing for my own pipeline. It turned out that no matter how I copied the SSH private key into the Drone secret variable field it messed up the format. I ended up base64-encoding the private key (`base64 -w0` to avoid line breaks).

An example `.drone.yml` with SSH agent forwarding (so that the private key is only stored in a single place, namely inside Drone) looks like this:

```yamlkind: pipeline
name: default

platform:
  os: linux

steps:
- name: deploy
  image: runejuhl/alpine-deploy
  environment:
    SSH_PRIVATE_KEY_BASE64:
      from_secret: ssh_private_key_base64
  commands:
    - eval $(ssh-agent)
    - ( echo $SSH_PRIVATE_KEY_BASE64 | base64 -d | ssh-add - ) || (echo 'Broken SSH key. Is the branch protected?' && exit 1)
    - ssh -o StrictHostKeyChecking=no -A runejuhl@puppet 'cd ~/git/puppet && git pull'
```

**Comment by bradrydzewski** [comment]
base64 encoding is not required. When you echo a multi-line variable in bash you need to make sure you quote the variable like this:

```diff
-echo $SSH_KEY > ~/.ssh/id_rsa
+echo "$SSH_KEY" > ~/.ssh/id_rsa
```

here is a real world example [1] taken from the discourse forum:

```
kind: pipeline
name: test

steps:
- name: test
  image: docker:git
  commands: 
    # write the ssh key to disk
    - mkdir /root/.ssh
    - echo -n "$SSH_KEY" > /root/.ssh/id_rsa
    - chmod 600 /root/.ssh/id_rsa

    # add github to known hosts
    - touch /root/.ssh/known_hosts
    - chmod 600 /root/.ssh/known_hosts
    - ssh-keyscan -H github.com > /etc/ssh/ssh_known_hosts 2> /dev/null
```

[1] https://discourse.drone.io/t/clone-private-submodule-for-public-project/1453/2?u=bradrydzewski

**Comment by david-l-riley** [comment]
I'd note that doing `echo "$SSH_KEY"` exposes private keys to anyone running `ps` on the host machine and is generally not a great idea; similarly, storing the keys in files, even in ephemeral containers, probably isn't great. The Bourne shell builtin `printenv` is somewhat better because it only pipes the output through stdout without exposing it to the command line, where `ssh-add -` can pick it up. Having keys in the environment means they can still be snooped on via `/proc` on a Linux system, but the surface area is much reduced.

You should probably also not be fetching the host keys directly from the server you're trying to connect to, since that provides no verification of the host's integrity.

Here's an example that takes care of the above, assuming you have the SSH deploy and host keys stored as secrets:

```
steps:
  - name: clone
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_deploy_key
      SSH_HOST_KEYS:
        from_secret: ssh_host_keys
    commands:
      - install -d ~/.ssh -m 0600
      - printenv SSH_HOST_KEYS > ~/.ssh/known_hosts
      - printenv SSH_KEY | ssh-agent sh -c "ssh-add - && git clone <user>@<host>:path/to/repo.git"
```

This avoids dumping anything sensitive to a file (host keys are for verification, not access control), exposing it through the command line, or spawning backgrounded `ssh-agent` processes. We use `sh -c` to execute the `ssh-add` command followed by the clone because there's not much other way of running two sequential commands, but the agent dies when the command finishes instead of hanging around potentially indefinitely like in some of the above suggestions.

All this said, I really wish Drone had better ways of configuring Git access than assuming HTTPS is always going to work; in many on-premises environments, this is decidedly not the case. The only reason it works at all in our environment is because it seems Drone uses the GitHub REST API to explore the repositories, but it can't even do a basic clone of anything out of the box. Some basic SSH options in the `clone` settings would make a HUGE difference. Are PRs for this welcomed?
