### ISSUE TITLE
RFC: don't inject drone env variables to plugins container by default

### ISSUE THREAD

**Issue by mapleeit** [drone/drone#2698]
The plugin system is really great. And undoubtedly, docker image as plugin is a more advanced way because of portability. It could be a revolution in the whole CI ecosystem. People can share these plugins across CIs.

But then I realize one thing, Drone injects its own env variables to the plugins container by default. And all env variable names start with DRONE_ prefix. This design breaks the portability across CIs, which could be better. 

I prefer not to inject all env to the container by default. Instead, people should fully control what variables they want. 

For example, `GitHub Pages` use some default env variables, required or option.  [DRONE_REMOTE_URL](https://github.com/drone-plugins/drone-gh-pages/blob/master/main.go#L64) is a required variable. In my mind, it should be named as `PLUGIN_REMOTE_URL`, and be transferred by user.

```yaml
steps:
- name: publish  
  image: plugins/gh-pages
  settings:
    username:
      from_secret: github_username
    password:
      from_secret: github_password
    pages_directory: public/
    remote_url: $DRONE_REMOTE_URL
```

This can pull out `plugins` from specific `Drone` system, and can make plugins more easy to test and use.
