### ISSUE TITLE
Expose hipchat notification text as a template config

### ISSUE THREAD

**Issue by rgarcia** [drone/drone#272]
I just started experimenting with hipchat notifications, and it'd be great if we could customize the message sent to hipchat (e.g. include a link to the commit in drone, convert emails to hipchat @nicknames, etc.). I think most of this would be solved if we could provide a template in the config.

**Comment by bradrydzewski** [comment]
most notification templates, including hipchat, now support custom message templates in handlebars format, for example:

```
notify:
  hipchat:
    template: |
      {{ build.number }} finished with status {{ build.status }}
```
