### ISSUE TITLE
mapping values are not allowed in this context

### ISSUE THREAD

**Issue by tfzxyinhao** [drone/drone#2724]
Does there everyone know how to treat this error 'yaml: line 42: mapping values are not allowed in this context'

but my yaml just only 18 lines
```
kind: pipeline
name: default

clone:
  disable: true
  
steps:
- name: ssh
  image: appleboy/drone-ssh
  settings:
    host:
      - web1
    username: root
    ssh_key: 
      from_secret: ssh_key
    port: 22
    script:
      - cd /data/home/lu.com && git reset --hard && git clean -df && git pull
```
