### ISSUE TITLE
invalid mount config for type "bind"

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#2725]
Fix issues where bind mount fails if path does not exist on the host machine. This is related to how drone-runtime changed how it configured docker volumes when invoking the Docker API.

**Comment by matthewhartstonge** [comment]
Oh nice! wondered if it was something to do between drone/docker/moby...

For others, this was our quick workaround in the meantime:

```yaml
volumes:
  - name: tmp
    host:
      path: /tmp
  - name: cache
    host:
      path: /tmp/cache_${DRONE_COMMIT_BRANCH}/vendor

steps:
  - name: prime-cache-folder
    image: alpine:latest
    commands:
      - mkdir -p /lib/var/tmp/cache_${DRONE_COMMIT_BRANCH}/vendor
    volumes:
      - name: tmp
        path: /lib/var/tmp

- name: cache-dep-restore
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - /drone/src/github.com/drone/drone/vendor
    volumes:
      - name: cache
        path: /cache
```
