### ISSUE TITLE
Wrong node affinity on EKS cluster

### ISSUE THREAD

**Issue by iron-sam** [drone/drone#2726]
## Problem

When Drone configures affinity of pipelines' pods, it sets this chunk of code:

```yaml
spec:
  affinity:                                                                                                                                                                                                                                                                                                                  
    nodeAffinity:                                                                                                                                                                                                                                                                                                            
      requiredDuringSchedulingIgnoredDuringExecution:                                                                                                                                                                                                                                                                        
        nodeSelectorTerms:                                                                                                                                                                                                                                                                                                   
        - matchExpressions:                                                                                                                                                                                                                                                                                                  
          - key: kubernetes.io/hostname                                                                                                                                                                                                                                                                                      
            operator: In                                                                                                                                                                                                                                                                                                     
            values:                                                                                                                                                                                                                                                                                                          
            - ip-10-100-45-161.eu-west-1.compute.internal
```

Correct me if I'm wrong, but this affinity seems to be set based on pipeline's pod `spec.nodeName`. On AWS EKS, worker nodes names are tagged like `${HOST_DNS}.${AWS_REGION}.compute.internal`, but Kubernetes' label `kubernetes.io/hostname` is set to the actual host name of the EC2 instance, `${HOST_DNS}`, e.g.:

```bash
kubectl get nodes -L kubernetes.io/hostname
NAME                                          STATUS   ROLES    AGE    VERSION   HOSTNAME
ip-10-100-15-22.eu-west-1.compute.internal    Ready    <none>   12d    v1.12.7   ip-10-100-15-22
ip-10-100-45-161.eu-west-1.compute.internal   Ready    <none>   121m   v1.12.7   ip-10-100-45-161
ip-10-100-63-36.eu-west-1.compute.internal    Ready    <none>   11d    v1.12.7   ip-10-100-63-36
```

So, when the pipeline launches a new namespace to run all the steps of the pipeline, child jobs have the upper affinity, and never find a node to schedule the pod.

## Possible solution

You can set your nodes label `kubernetes.io/hostname` to the node name manually, and Drone would launch pods without errors.

But maybe Drone should use another type of affinity, or none affinity at all, but I assume that the affinity setting is there for a reason.

Let me know if you need more information.

Thank you for everything!
