### ISSUE TITLE
Trigger section is missing in jsonnet output if it only contains cron filter

### ISSUE THREAD

**Issue by random-ua** [drone/drone#2730]
Here's my drone.jsonnet
```
[
    {
        kind: "pipeline",
        name: "main",
        steps: [
            { name: "test", image: "alpine", command: ["uname","-a"] }
        ],
        trigger: {
            cron: ["weekly"]
        },
    }
]
```

Output from `drone jsonnet --stream --stdout`:
```
---
kind: pipeline
name: main

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: alpine
  command:
  - uname
  - -a
...
```

The whole `trigger` section is missing. After changing `trigger` to:
```
        trigger: {
            event: ["push"],
            cron: ["weekly"]
        }
```
section shows up with both filters:
```
trigger:
  cron:
  - weekly
  event:
  - push
```

**drone version 1.1.0**
