### ISSUE TITLE
Question - Valid yaml? Some yaml linters seem to think not.

### ISSUE THREAD

**Issue by verbruggenalex** [drone/drone#2740]
Is this valid yaml in Drone? Can I define **git** twice with different events?
```
workspace:
  base: /test
  path: webtools

clone:
  git:
    image: plugins/git
    recursive: true
    submodule_override:
      rest/map/data: https://github.com/ec-europa/euwebtoolsnuts.git
    when:
      event: [ push, pull_request, tag ]
  git:
    image: fpfis/true
    when:
      event: [ deployment ]
```

Some yaml linters like in Symfony trow errors on this because it's a duplicate key. I just want to know if this is valid in Drone, or you can use different keys for the git checkout. If this is only possible with duplicate keys I'll have to use a yaml linter that doesn't fall over this.
