### ISSUE TITLE
Drone installed successfully but will not trigger the build

### ISSUE THREAD

**Issue by weikaiiii** [drone/drone#2743]
docker run   --volume=/var/run/docker.sock:/var/run/docker.sock   --volume=/var/lib/drone:/data   --env=DRONE_GITEA_SERVER=https://xxxxx:3000   --env=DRONE_GIT_ALWAYS_AUTH=false   --env=DRONE_SERVER_HOST=xxx.xxx.xxx.xx:8000 --env=DRONE_RUNNER_CAPACITY=2      --env=DRONE_SERVER_PROTO=http   --env=DRONE_TLS_AUTOCERT=false    --publish=8000:80 --publish=4430:443    --restart=always   --detach=true   --name=drone   drone/drone:1

.drone.yml
```
kind: pipeline
name: chasing-test

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7.1
  commands:
  - ls -al
  - vendor/bin/codecept run
  when:
    branch:
    - dev_unit
    event:
    - push
```
