### ISSUE TITLE
Drone using container proxy settings instead of proxy environment variables

### ISSUE THREAD

**Issue by jonbesga** [drone/drone#2756]
Hi, I have drone running from a Docker image and HTTP_PROXY, HTTPS_PROXY, http_proxy and https_proxy set as environment variables in the image with, let's say: `http://proxy_a.com:80`

I have noticed that in the pipeline if I specify a step like this:
```
[...]
environment:
      http_proxy: http://proxy_b.com:80
      https_proxy: http://proxy_b.com:80
      HTTP_PROXY: http://proxy_b.com:80
      HTTPS_PROXY: http://proxy_b.com:80
commands:
    - echo $http_proxy
    - echo $https_proxy
[...]
```

The values displayed are the proxy settings previously set when running the Drone image (the proxy_a). Drone is not overriding the values

However, if I set the `proxy_b` as a secret, and I write the step this way:

```
[...]
environment:
      http_proxy:
        from_secret: HTTP_PROXY
      https_proxy:
        from_secret: HTTP_PROXY
      HTTP_PROXY:
        from_secret: HTTP_PROXY
      HTTPS_PROXY:
        from_secret: HTTP_PROXY
commands:
    - echo $http_proxy
    - echo $https_proxy
[...]
```

 The values displayed are indeed the proxy_b.

Is this an expected behavior?
