### ISSUE TITLE
Ability to define a fallback image for steps

### ISSUE THREAD

**Issue by allrod5** [drone/drone#2761]
It should be very helpful to be able to define fallback images for steps in case an image is not available.

The use case I'm facing: my drone pipeline uses an image created by itself on the last build. The problem is that in the very first build there is no custom image to use so it would be useful to be able to define another image to use in case the primary one is missing.

Possible syntaxes would be: (i) passing a list as `image`; or (ii) specifying it on a parameter like `fallback-image`:

(i)
```yaml
pipeline:
  backend:
    image: [ my-custom-image, golang ]
    commands:
      - go get
      - go build
      - go test
```

(ii)
```yaml
pipeline:
  backend:
    image: my-custom-image
    fallback-image: golang
    commands:
      - go get
      - go build
      - go test
```
