### ISSUE TITLE
trigger: cannot find yaml

### ISSUE THREAD

**Issue by lixianyang** [drone/drone#2769]
I deployed drone in kubernetes(use helm chart). I configed gitlab and sync project is ok. But when I use drone in project and trigger to do ci, an error appear.

drone server log(no more log in debug mode):
```json
{"commit":"db51b7a2d88aabc8db74d7379d230a0368a24a25","error":"","event":"push","level":"warning","msg":"trigger: cannot find yaml","ref":"refs/heads/master","repo":"xianyang.li/drone-demo","time":"2019-08-01T03:47:31Z"}
```
project file:
```
.drone.yml
.gitattributes
README.md
main.go
```

.drone.yml:
```yaml
---
kind: pipeline
name: default

steps:
- name: test
  image: golang:1.12.6-stretch
  commands:
  - go version
```
