### ISSUE TITLE
drone.yml parsing fails when starting by ---

### ISSUE THREAD

**Issue by benjamin-bergia** [drone/drone#2778]
I am running v1.0.0 and I noticed that when my drone.yml file starts with a `---` before my first pipeline definition, the parsing fails. I tried the CLI linter but it doesn't return any error.

for example a file starting by
```yaml
kind: pipeline
name: unit
steps:
  - name: unit
```
Will work but this will not:
```yaml
---
kind: pipeline
name: unit
steps:
  - name: unit
```
