### ISSUE TITLE
skipping automated docker 

### ISSUE THREAD

**Issue by wudaoren** [drone/drone#2813]
the config is :
```
- name: Docker打包(正式服）
    image: plugins/docker
    settings:
      username:
        from_secret: docker-hub-user
      password:
        from_secret: docker-hub-pswd
      repo: docker.abc.cn/mimihui
      registry: docker.abc.cn
      auto_tag: true
      mirror: http://f1361db2.m.daocloud.io
```
use branch master is ok ,when I use other branch,only plugins/docker can't work
```
time="2019-09-03T11:48:51Z" level=info msg="skipping automated docker build for refs/heads/develop"
```
