### ISSUE TITLE
Drone hides extra characters in a build log

### ISSUE THREAD

**Issue by okgolove** [drone/drone#2878]
Duplicate a [thread](https://discourse.drone.io/t/drone-hide-extra-characters-in-a-build-log/5812) from forum

I use multiple secret credentials in my job. Drone used to hide the secrets in a job log properly.
I’ve just added 3 more secrets to a drone config and now Drone hides too much information (screenshots attached).

Drone version: 1.4.0

Secrets:

```
 environment:
  TF_IN_AUTOMATION: "true"
  DO_TOKEN:
    from_secret: DO_TOKEN
  DO_ACCESS_KEY:
    from_secret: DO_ACCESS_KEY
  DO_SECRET_KEY:
    from_secret: DO_SECRET_KEY
  TF_VAR_tracking_count:
    from_secret: TRACKING
  TF_VAR_torg_count:
    from_secret: TORG
  TF_VAR_lb_t_count:
    from_secret: LB_T
  TF_VAR_lb_b_count:
    from_secret: LB_B
```

![image](https://user-images.githubusercontent.com/36846182/69007025-e99a9380-0940-11ea-9d69-ea354a42cf98.png)
![image](https://user-images.githubusercontent.com/36846182/69007038-22d30380-0941-11ea-80b2-a2c90be18560.png)

If I delete all TF_VAR_* secrets, the problem will gone.
I’ve already tested it.
