### ISSUE TITLE
Improve kubernetes runner documentation

### ISSUE THREAD

**Issue by zetaab** [drone/drone#2881]
current drone documentation contains only how to start drone runner as pod. However, that is not quite good for production use. First in production drone runner should be deployed as deployment. Secondly the instructions is missing rbac rules.

Here you have rbac rules (hopefully this contains everything I went through the engine code):
```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: drone
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
  - create
  - delete
  - list
  - watch
  - update

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: drone
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
roleRef:
  kind: Role
  name: drone
  apiGroup: rbac.authorization.k8s.io
```

And Here the deployment:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone
  labels:
    app.kubernetes.io/name: drone
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: drone
  template:
    metadata:
      labels:
        app.kubernetes.io/name: drone
    spec:
      containers:
      - name: runner
        image: drone/drone-runner-kube:latest
        ports:
        - containerPort: 3000
        env:
        - name: DRONE_RPC_HOST
          value: foobar.com
        - name: DRONE_RPC_PROTO
          value: https
        - name: DRONE_RPC_SECRET
          value: yyy
```

no idea which is correct place to report these?
