### ISSUE TITLE
RFC: Service detach until

### ISSUE THREAD

**Issue by grachevko** [drone/drone#2887]
Graph Execution is awesome!

What about add limit for service execution? 
For example i need database and other infrastructure only for testing, but testing is not end of pipeline. I want to free resource immediately as it no more necessary. 

```yaml
---
kind: pipeline
type: docker
name: default

steps:
- name: database
  image: mariadb
  detach:
    until: 
      - unit
      - e2e

- name: install
  image: node
  commands:
  - npm install

- name: unit
  image: node
  commands:
  - npm test

- name: e2e
  image: node
  commands:
  - npm e2e

- name: build / push / deploy / notify / something else
  ...
```
