### ISSUE TITLE
Support status type "changed"

### ISSUE THREAD

**Issue by corradio** [drone/drone#2895]
Hello,

Is the condition
```yml
steps:
  - name: notify-email
    ...
    when:
      status: [changed]
```
supported? It doesn't seem to work.
Those two threads discussed it but the issue they point to doesn't exist anymore:
- https://discourse.drone.io/t/run-pipeline-step-on-status-change-similar-to-bitbucket-build-fixed-event/5065
- https://discourse.drone.io/t/does-slack-plugin-still-support-status-change/1012

Thank you in advance
