### ISSUE TITLE
Build promote is ignoring environment

### ISSUE THREAD

**Issue by Serrvosky** [drone/drone#2910]
Hello peeps,

I'm trying to use promote in my pipelines, but i'm facing a problem, that I don't know if it is a bug or a miss configuration:

This an excert of my drone file:
```
kind: pipeline
type: docker
name: test-feature

trigger:
  event:
    - promote

....
- name: binary
    image: go/golang:1.13-alpine-react
    commands:
      - cd dist
      - make linux.amd64
    when:
      environment: feature

  - name: publish
    image: plugins/docker
    settings:
      dockerfile: dist/docker/Dockerfile.linux.amd64
      username: nologin
      password:
        from_secret: SCW_REGISTRY_TOKEN
      registry: <refistry_url>
      repo: r<refistry_url>/featurescandidate/${DRONE_REPO_NAME}
      tags:
        - ${DRONE_COMMIT_SHA}
    when:
      environment: feature
    
  - name: deploy-test
    image: nomad/drone-nomad
    settings:
      addr: <nomad_addr>
      template: frontend_feature.hcl
    when:
      environment: feature
....
```

But when I run `drone build promote repo/name <id> feature`, it works perfectly, but when I run this command `drone build promote repo/name <id> something`, it makes the same steps that the previous command....

I think it's not addressing environment flag.

Thanks for your replies :)
