### ISSUE TITLE
Docker Buildx suggestions

### ISSUE THREAD

**Issue by carpenike** [drone/drone#2911]
I'm looking to build cross architecture docker containers (arm64 on amd64) and buildx seems to be perfect. 

https://starkandwayne.com/blog/building-docker-images-for-kubernetes-on-arm/

Also tried this as well and it doesn't appear to work as expected, build hangs on the docker buildx step.

```
kind: pipeline
type: kubernetes
name: build-cephcsi-multi

platform:
  os: linux
  arch: amd64

steps:
- name: cephcsi-on-amd64
  image: docker:19.03.5-dind
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - export DOCKER_CLI_EXPERIMENTAL=enabled
  - mkdir -p ~/.docker/cli-plugins
  - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  - docker buildx build --platform linux/amd64,linux/arm64 --tag carpenike/cephcsi:v2.0-canary .

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
```
My understanding of the multiple platform config in a pipeline is that it requires the destination architecture in order to build (https://discourse.drone.io/t/cloud-drone-io-arm-build/3416/2), which will be much slower than buildx.
