### ISSUE TITLE
Docker Runner: Cannot accept stage (400 Bad Request)

### ISSUE THREAD

**Issue by SuNNjek** [drone/drone#2914]
Hello,

I've set up Drone CI on my Raspberry Pi with Gitea according to the documentation. I have the server configuration and the runner config in an docker-compose.yml:

```yaml
version: '3'

services:
        drone:
                image: "drone/drone:1"
                restart: always
                ports:
                        - "3001:80"

                environment:
                        DRONE_GITEA_CLIENT_ID: <omitted>
                        DRONE_GITEA_CLIENT_SECRET: <omitted>
                        DRONE_GITEA_SERVER: <omitted>
                        DRONE_RPC_SECRET: <omitted>
                        DRONE_SERVER_HOST: <omitted>
                        DRONE_SERVER_PROTO: https
                        DRONE_TLS_AUTOCERT: "false"
                        DRONE_AGENTS_ENABLED: "true"
                        DRONE_DATABASE_DRIVER: postgres
                        DRONE_DATABASE_DATASOURCE:  <omitted>
                        DRONE_LOGS_DEBUG: "true"

                volumes:
                        - /var/lib/drone:/data

        drone-docker-runner:
                image: "drone/drone-runner-docker:1"
                restart: always
                depends_on:
                        - drone
                ports:
                        - "5000:3000"
                links:
                        - drone

                environment:
                        DRONE_RPC_PROTO: http
                        DRONE_RPC_HOST: drone:80 
                        DRONE_RPC_SECRET: <omitted>
                        DRONE_RUNNER_CAPACITY: 1
                        DRONE_RUNNER_NAME: Raspberry Pi
                        DRONE_UI_USERNAME: <omitted>
                        DRONE_UI_PASSWORD: <omitted>
                        DRONE_LOGS_TRACE: "true"

                volumes:
                        - /var/run/docker.sock:/var/run/docker.sock

```

Now I'm trying to execute a build but the runner constantly fails with the following error:
```
time="2020-01-29T21:03:12Z" level=debug msg="poller: request stage from remote server" thread=1
time="2020-01-29T21:03:12Z" level=debug msg="stage received" stage.id=80 stage.name=drone-test stage.number=1 thread=1
time="2020-01-29T21:03:12Z" level=error msg="cannot accept stage" error="400 Bad Request" stage.id=80 stage.name=drone-test stage.number=1 thread=1
time="2020-01-29T21:03:12Z" level=debug msg="poller: request stage from remote server" thread=1
time="2020-01-29T21:03:12Z" level=debug msg="stage received" stage.id=80 stage.name=drone-test stage.number=1 thread=1
time="2020-01-29T21:03:12Z" level=error msg="cannot accept stage" error="400 Bad Request" stage.id=80 stage.name=drone-test stage.number=1 thread=1
...
```

Any way to fix this?
