### ISSUE TITLE
drone restart with parm do not work

### ISSUE THREAD

**Issue by pc10201** [drone/drone#2928]
drone version:1.6.5

.drone.yml content:
```
kind: pipeline
type: docker
name: build
steps:
  - name: build
    image: golang:alpine
    pull: if-not-exists # always never
    environment:
      node: all
      UP: all
    commands:
      - env
      - pwd
      - ls
```

restart command:
```
drone build restart  root/demo 55 -p node=ttt -p UP=123
```
