### ISSUE TITLE
"There was a problem enabling your repository" message

### ISSUE THREAD

**Issue by memochou1993** [drone/drone#2951]
When I clicked the button "ACTIVATE REPOSITORY", it showed "There was a problem enabling your repository." message.

And I found the API endpoint is my domain not GitHub.

![image](https://user-images.githubusercontent.com/38420282/79134389-385d3400-7de0-11ea-8863-6b59d7e9e5ff.png)

this is my `docker-compose`:

```YML
version: "3.5"

services:
  drone-server:
    image: drone/drone:1.2.1
    ports:
      - 9000:80
      - 9443:443
    networks:
      - drone
    volumes:
      - ./drone-data:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    restart: always
    environment:
      - DRONE_GITHUB_SKIP_VERIFY=true
      - DRONE_AGENTS_ENABLED=true
      - DRONE_SERVER_HOST=localhost:8000
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_OPEN=false
      - DRONE_HOST=http://localhost:8000
      - DRONE_GITHUB=true

  drone-agent:
    image: drone/agent:1.2.1
    command: agent
    restart: always
    depends_on:
      - drone-server
    networks:
      - drone
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - ./.env
    environment:
      - DRONE_RPC_SERVER=drone-server:8000

networks:
  drone:
    name: drone_network
```

`.env`:

```BASH
DRONE_GITHUB_CLIENT_ID=xx
DRONE_GITHUB_CLIENT_SECRET=yy
DRONE_RPC_SECRET=zz
DRONE_SERVER_HOST=epoch.tw
DRONE_SERVER_PROTO=https
```

How should I fix this?
