### ISSUE TITLE
plugins bash and secrets

### ISSUE THREAD

**Issue by dmp2tech** [drone/drone#2957]
Hi,

I want to create a plugin for push a branch on dokku. I want create a bash plugin.

```
steps:
- name: essai
  image: name/image
  environment:
    SSH_PUBLIC_KEY:
      from_secret: ssh_public_key
    settings:
      build_args_from_env:
        - SSH_PUBLIC_KEY
```
First i would just like to put the variable ssh_public_key in a file.
```
#!/bin/bash

mkdir -p ~/.ssh
echo "${SSH_PUBLIC_KEY}" | tr -d '\r' > ~/.ssh/id_rsa.pub
chmod 700 ~/.ssh/id_rsa.pub

cat  ~/.ssh/id_rsa.pub
```
I have that result

```
******
```
I searched but I don't know how to do it.
thank you in advance for your help
Best regards
