### ISSUE TITLE
Drone clone stuck

### ISSUE THREAD

**Issue by ethanliuu** [drone/drone#2987]
I have been using the drone in production for two months without any problems.

Today, the developers told me that there was a problem with CI / CD and that it didn’t run as planned.

I went up to check it and found that all the projects had been stuck in the clone step.

Have you ever met this kind of situation? How can I solve this problem?

thank you

Version introduction
drone:1.6.5
Kubernetes:1.14.6

drone log:
```json
{
  "build.id": 525,
  "build.number": 16,
  "error": "Cannot transition status via :enqueue from :pending (Reason(s): Status cannot transition via \"enqueue\")",
  "level": "warning",
  "msg": "manager: cannot publish status",
  "repo.id": 242,
  "stage.id": 519,
  "time": "2020-07-01T09:57:07Z"
}
```
```
drone-pzav4gijxrufkrjbv8hc   0/7     Init:Error   0          2m44s
```
![image](https://user-images.githubusercontent.com/64894334/86232317-57d95100-bbc6-11ea-8315-66ec9eeefb57.png)

**Comment by milewski** [comment]
If it happens that you use Aliyun and Bitbucket.. cloning will be extremely slow (you can try doing a git clone directly from your server) my work around was to cache the repository and override the drone clone step with something like this:

```
clone:
  disable: true

steps:

  - name: clone
    image: alpine/git
    commands:
      - git clone --reference /cached-repository ${DRONE_GIT_HTTP_URL} .
      - git checkout ${DRONE_COMMIT_SHA} -b ${DRONE_COMMIT_SHA}
    volumes:
      - name: git-cache
        path: /cached-repository

volumes:
  - name: git-cache
    host:
      path: /drone-cache/git-cache
```

Assuming you already have a valid git repository at this location: /drone-cache/git-cache
