### ISSUE TITLE
Can't login to Gogs 

### ISSUE THREAD

**Issue by snowdon-dev** [drone/drone#2989]
I have the following composefile

```
version: '3'
services:
  # https://developpaper.com/build-your-own-ci-cd-system-with-drone-and-gogs/
  drone-server:
    container_name: 'drone-server'
    image: drone/drone:latest
    ports:
      - "8080:80"
      - 8843:443
      - 9000
    volumes:
      - ./drone:/var/lib/drone/
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=drone-server
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GOGS=true
      - DRONE_GOGS_SKIP_VERIFY=false
      - DRONE_GOGS_SERVER=http://gogs:3000
      - DRONE_PROVIDER=gogs
      - DRONE_DATABASE_DATASOURCE=/var/lib/drone/drone.sqlite
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEwHww
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEwHww
  gogs:
    container_name: 'gogs'
    image: hypriot/rpi-gogs-raspbian:latest
    ports:
      - "10022:22"
      - "3000:3000"
    volumes:
      - ./data/gogs:/data
    depends_on:
      - mysql
  mysql:
    container_name: 'mysql'
    image: "hypriot/rpi-mysql"
    volumes:
      - ./gogs/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: pass
      TZ: Europe/London
  drone-agent:
    container_name: 'drone-agent'
    image: drone/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_SERVER=http://drone-server
      - DRONE_RPC_SECRET=ALQU2M0KdptXUdTPKcEwHww
      - DRONE_DEBUG=true
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=ALQU2M0KdptXUdTPKcEwHww
      - DRONE_MAX_PROCS=5
```

When trying to login to drone, Gogs will return `gogs            | [Macaron] Completed /api/v1/user 404 Not Found in 7.359052ms
`. From a little reading this seems to be an issue with authentication.

What else can I do to debug?
