### ISSUE TITLE
Cant pull images from bitbucket private repos

### ISSUE THREAD

**Issue by kotyara85** [drone/drone#3022]
Drone version 1.8.1

```
kind: pipeline
type: kubernetes
name: default

steps:
  - name: vault
    image: myrepo.example.com/test:latest
      - "env"

image_pull_secrets:
  - dockerconfig
```

The pipeline just stops without any error output and error notification.
