### ISSUE TITLE
'When: Local: false' not working during local build

### ISSUE THREAD

**Issue by Ashtonian** [drone/drone#3033]
Steps to reproduce: 

drone.yml: 
``` yaml
pipeline:
  not_local:
    when:
      local: false
    image: alpine:3.6
    commands:
      - echo "hello world"
```

Output:
``` sh
drone exec
[not_local:0] + echo "hello world"
[not_local:1] hello world
```

Expected: 
the step not to run when running drone locally. This is very useful for plugins.
