### ISSUE TITLE
Jsonnet cleans "trigger" from steps

### ISSUE THREAD

**Issue by Upgreydd** [drone/drone#3039]
Hi. Jsonnet removes "trigger" while converting to `.drone.yaml`
```
{
        name: "Send slack info",
        depends_on: [ "OTHER_STEP" ],
        image: "plugins/slack",
        settings: {
          channel: "notifications",
          link_names: true,
          template: "{{#success build.status}}Cron build passed. Good job.{{else}}Cron build failed. Fix me please.{{/success}}",
        },
        trigger: { event: ["cron"] },
        when: {status: ['success', 'failure'] }
      }
```
And after running `drone jsonnet --stream --format=false --stdout` I'm receiving this:
```
- name: Send slack info
  image: plugins/slack
  settings:
    channel: notifications
    link_names: true
    template: "{{#success build.status}}Cron build passed. Good job.{{else}}Cron build failed. Fix me please.{{/success}}"
  when:
    status:
    - success
    - failure
  depends_on:
  - OTHER_STEP
```
there's no 
```
trigger:
   event:
   - corn
```
