### ISSUE TITLE
The pipeline steps do not support  'ports' Property

### ISSUE THREAD

**Issue by imsoul** [drone/drone#3061]
I want to publish the port like docker-compose like this.

```
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: golang
    detach: true
    ports:
      - 10080:80
    commands:
      - echo Hello Drone !
      - go run main.go
```

but Property 'ports' is not allowed

How can I publish the port of the service ?
Why didn't support all docker-compose's property ?
