### ISSUE TITLE
Push tag event

### ISSUE THREAD

**Issue by Bugagazavr** [drone/drone#468]
Gitlab and Github supports push tag event, also this can be used to create release https://github.com/drone/drone/issues/439

```yml
publish:
  rubygems:
    tag_only: true
    token: $RUBYGEMS_TOKEN
    scripts:
      - gem build ./supergem.gemspec
    artifacts: 
      - supergem-$DRONE_TAG.gem
  github:
    tag_only: true
    token: $GITHUB_TOKEN
    name: 'supergem'
    artifacts:
      - supergem-$DRONE_TAG.gem
```
