### ISSUE TITLE
Deploy Pipelines

### ISSUE THREAD

**Issue by gregory90** [drone/drone#470]
I'm using github-flow branching model. My ideal CD workflow looks like this :
1. Merge some feature branch to master,
2. Drone picks up change, build starts,
3. If build succeeds Drone is creating artifacts and sends them somewhere (it could be docker image or some .tgz file - that part is pretty much covered by publish plugins),
4. Deploy plugin starts - application is deployed to staging environment,
5. When everything looks good on staging - I'd trigger manually deployment to production.

 So basically what I need in the most simple form is something like this:
```yaml
deploy: 
    ssh: 
        target: user@staging_host:/ 22 
        cmd: /redeploy.sh
    ssh: 
        target: user@production_host:/ 22 
        cmd: /redeploy.sh
        manual: true
```
(Actually I cannot use two ssh plugins in deploy part right now, Drone is picking up only the last one, I'm using latest exp branch).
After successful build and review on staging I'd trigger deployment to production from Drone UI.

I don't have experience with golang, but I'd try to implement this if it's meeting project goals.

**Comment by ianneub** [comment]
@bradrydzewski Is this still "in the pipeline"? I think adding this feature is what I'd need to use Drone as well. At first I thought about writing my own CI system, but maybe I could help with this?

I'm not sure how this fits in though with the changes you are working on for 0.4. Maybe it should wait until 0.4 is stable?

**Comment by bradrydzewski** [comment]
@ianneub yes, I definitely want to tackle pipelines but ideally once 0.4 is more stable. There is just so much changing to support plugins + matrix right now

**Comment by ltackmann** [comment]
+1

**Comment by zakjan** [comment]
Support for Continuous Delivery (GitHub, TBD flow) model is the last missing feature that keeps me from using Drone. Really. I don't want to clutter my git repo with branches for each environment, as seen in Continuous Deployment (Gitflow) model.

Obviously it needs some kind of Deployment Pipelines with manual triggers. As a good example, see Go.CD https://www.go.cd/documentation/user/current/resources/images/PipelineActivity.png

**Comment by tboerger** [comment]
@zakjan if you need a real pipeline or sounds like drone is simply wrong for you. You need different tool like concourse.ci

**Comment by zakjan** [comment]
No, real pipelines with multiple interlinked projects together are probably overkill for me. I posted the Go.CD link as an example only because of the manual trigger and its UI. My usecase are isolated projects, where I can trigger manual deploys of successful builds to different envs. That's all. I believe it is not that far from Drone concept. Anyway, thanks for the hint about Concourse, I'll look into it.

**Comment by bradrydzewski** [comment]
@zakjan drone has initial (slightly weak) support for the GitHub deployment API which allows triggering a deployment event for an existing commit. There is also an open issue to trigger deployment events without having to the use the GitHub deployment API. See https://github.com/drone/drone/issues/1303

@tboerger multi-build steps were a big step toward pipelines. Parallel steps (#1356) and triggering deployments (#1303) will give drone very strong pipeline capabilities. Drone also has existing pipeline capabilities with the GitHub deployment API so we should perhaps understand the use case before sending someone to a different tool. Some people need pipeline, but don't need the complexity of those other tools.

**Comment by bradrydzewski** [comment]
> My usecase are isolated projects, where I can trigger manual deploys of successful builds to different envs.

a while back, as part of #1303, I added the ability to re-trigger a build by passing the fork flag:
https://github.com/drone/drone/commit/0e5ee4470038ac75b3b2bb9b39f460a24cb3b19e

we could pass an additional flag to, optionally, retrigger the build as a deployment event:
https://github.com/drone/drone/blob/master/controller/build.go#L232

```diff
build.Status = model.StatusPending
build.Started = 0
build.Finished = 0
build.Enqueued = time.Now().UTC().Unix()
+build.Event := c.DefaultQuery("event", build.Event)
```

notice that changing the event is helpful because we can configure steps to only execute for certain events. This works really well with the github deployment api, and would work well manually triggered deployments. You would just need to adjust your yaml as follows:

```
build:
  test:
    image: golang
    commands:
      - make test
  package:
    image: golang
    commands:
      - make dist
    when:
      event: deployment

deploy:
  heroku:
    when:
      event: deployment
```

As you mentioned, we probably need a way to specify the environment (staging, production, etc). Similar to above, drone captures a `deploy_to ` field indicating which environment we want to deploy to. So we could do this:

```diff
build.Status = model.StatusPending
build.Started = 0
build.Finished = 0
build.Enqueued = time.Now().UTC().Unix()
+build.Event := c.DefaultQuery("event", build.Event)deploy_to
+build.Deploy := c.DefaultQuery("deploy_to", build.Deploy)
```

Finally, we will want to filter steps based on environment:

```
deploy:
  heroku:
    when:
      event: deployment
      environment: staging
```

We need to add the property to the yaml:
https://github.com/drone/drone-exec/blob/master/yaml/types.go#L69

```diff
type Filter struct {
	Repo    string
	Branch  Stringorslice
	Event   Stringorslice
+	Environment Stringorslice
	Success string
	Failure string
	Change  string
	Matrix  map[string]string
}
```

And then we need to hook up some matching logic ... probably about 10 lines of code:
https://github.com/drone/drone-exec/blob/master/runner/match.go

So in total, this change probably requires about 20 lines of code change to alter the re-build / fork endpoint to launch arbitrary builds and deployments, with stronger pipeline capabilities. I'm currently focused on other tasks and can't devote time to this right now, but @zakjan is this something you're willing to contribute? I can help you through the process if you'd like.

**Comment by bradrydzewski** [comment]
We have recently integrated features that enable deployment pipeline functionality in drone. We have added a `deployment` build event (similar to `pull_request`, `push` and `tag` events) and can trigger builds with this event and the target deployment environment.

You can trigger deployments using the command line utility. The below examples demonstrates how we can promote a build to staging and then to production:

```
drone deploy octocat/hello-world 55 staging
drone deploy octocat/hello-world 55 production
```

You can then limit steps in your drone.yml file to only execute for deployment events for a specific environment:

```yaml
deploy:
   heroku:
      token: f6d7s87f6f8a8s7s
      app: production.app.com
      when:
        event: deployment
        environment: production
   heroku:
      token: f6d7s87f6f8a8s7s
      app: staging.app.com
      when:
        event: deployment
        environment: staging
```

I believe these changes enable the requested functionality to manually trigger a deployment through drone. This is a simple, yet powerful feature, and I look forward to feedback.
