### ISSUE TITLE
Git deployment target not working

### ISSUE THREAD

**Issue by darkpixel** [drone/drone#610]
Using the following git deployment target doesn't work:

```
    git:                                                                                                                
        target: dokku@myserver.mydomain.tld:mysite
        branch: master
        force: false
```

I get the following output from Drone after my tests pass:
```
usage: git config [options]

Config file location
    --global              use global config file
    --system              use system config file
    --local               use repository config file
    -f, --file <file>     use given config file

Action
    --get                 get value: name [value-regex]
    --get-all             get all values: key [value-regex]
    --get-regexp          get values for regexp: name-regex [value-regex]
    --replace-all         replace all matching variables: name value [value_regex]
    --add                 adds a new variable: name value
    --unset               removes a variable: name [value-regex]
    --unset-all           removes all matches: name [value-regex]
    --rename-section      rename section: old-name new-name
    --remove-section      remove a section: name
    -l, --list            list all
    -e, --edit            opens an editor
    --get-color <slot>    find the color configured: [default]
    --get-colorbool <slot>
                          find the color setting: [stdout-is-tty]

Type
    --bool                value is "true" or "false"
    --int                 value is decimal number
    --bool-or-int         value is --bool or --int
    --path                value is a path (file or directory name)

Other
    -z, --null            terminate values with NUL byte
```

If I change it to:
```
    bash:
        script:
            - git remote add production dokku@myserver.mydomain.tld:mysite
            - git push production master
```
it deploys just fine.
