### ISSUE TITLE
HipChat notifications error

### ISSUE THREAD

**Issue by Mooash** [drone/drone#624]
I'm having some troubles since updating to the master branch earlier today, my ```drone.yml``` looks like this:

```
notify:
  hipchat:
    RoomId: {{hipchatRoom}}
    Token: {{hipchatToken}}
    on_started: true
    on_success: true
    on_failure: true
```

I've also tried:
```
notify:
  hipchat:
    RoomId: $$hipchatRoom
    Token: $$hipchatToken
    on_started: true
    on_success: true
    on_failure: true
```

However all I get is this in ```/var/log/upstart/drone.log```:
```
2014/10/25 16:49:23 dial tcp :0: connection refused
2014/10/25 16:49:23 The RoomId, From, and Message fields are all required.
2014/10/25 16:49:23 subscription's close channel received message
```

My params look like this (Token changed obviously):
```
hipchatRoom: Notifications
hipchatToken: 12382468276-246
```

I'm running it on Ubuntu 14.04 with docker version:
```
root@docker-01:/etc# docker version
Client version: 1.3.0
Client API version: 1.15
Go version (client): go1.3.3
Git commit (client): c78088f
OS/Arch (client): linux/amd64
Server version: 1.3.0
Server API version: 1.15
Go version (server): go1.3.3
Git commit (server): c78088f
root@docker-01:/etc#
```

Any other info I can give?
