### ISSUE TITLE
Support for Docker --pull Flag

### ISSUE THREAD

**Issue by vaijab** [drone/drone#697]
Currently, at least I couldn't find in the code how to tell drone to pull base build image before running `script` commands.

We use our own build images and once we update them, drone has no way of knowing if we use the same build image tag, like `image: foo/bar:latest`.

This should default to `false`, but there should be an option in `.drone.yml` to change that.

```yaml
image: foo/bar:latest
image_pull: true
script:
  - exit 0
```
