### ISSUE TITLE
Docker publish won't trigger if script: [] is empty or exits quickly

### ISSUE THREAD

**Issue by vaijab** [drone/drone#734]
I managed to figure out why docker publish does not trigger.

Reproduce:

```yaml
image: <any image with git>
publish:
  docker:
    image_name: foobar
    <...>
```

As a workaround, I added `sleep 5` to `script: []`.
