### ISSUE TITLE
Drone/Slack: Corporate Proxy

### ISSUE THREAD

**Issue by MitchK** [drone/drone#741]
Hi!

We currently use Drone in our company and it works just awesome. We also use Slack in our team and would like to notify a slack channel of the build status.

Currently, nothing happens with slack.
We have set it up this way:
```
notify:
  slack:
    username: $$SLACK_USER
    token: $$SLACK_TOKEN
    team: $$SLACK_TEAM
    channel: $$SLACK_CHANNEL
    on_started: true
    on_success: true
    on_failure: true
```

And the environment variables are set in the repository settings on Drone.

There is no output of the slack plugin. How can we have a more verbose logging output of Drone or the Plugin? 

Does Drone/The Plugin System/The Slack plugin support a corporate proxy?
Our proxy is set via ```HTTP_PROXY/HTTPS_PROXY```on the machine.
