### ISSUE TITLE
Limit the number of concurrent builds per-repository or per-branch

### ISSUE THREAD

**Issue by paulczar** [drone/drone#758]
I would love to have a per repo setting for build concurrency.

We have a very heavy testing regime for one of our repos that takes anywhere up to two hours and spins up a significant number of VMs in our openstack cluster for integration testing.

I would love to be able to set it to run just the one build at a time, but only on that specific repo.  other repos should have free reign to go nuts.

**Comment by amtrack** [comment]
:+1:

**Comment by bradrydzewski** [comment]
We do something similar to this in the original, legacy [drone.io](https://drone.io) codebase. It complicates the queue a bit, however, I do have some options in mind.

I recently posted this on twitter:
https://twitter.com/bradrydzewski/status/543889201918267393
https://twitter.com/bradrydzewski/status/543892622922637314

It is a new project I've been kicking around that focuses on queuing and managing Docker containers across pools of server resources. It has much, much more flexibility than Drone in this department. Ideally we could include this as an optional plugin in order to replace the stock Drone queue.

Stay tuned.

**Comment by bradrydzewski** [comment]
We are getting a lot of different requests to customize the queue behavior. I'm not sure we can satisfy every single use case, so I think the best approach is to make this pluggable / scriptable. For example, maybe we could use [otto](https://github.com/robertkrimen/otto) to allow custom scripts. Or maybe we could allow integration with more powerful / flexible queuing systems (like rabbitmq)

I'm going to rename this thread accordingly

**Comment by Jean85** [comment]
:+1:

**Comment by sheerun** [comment]
@bradrydzewski With autoscaling available, is there a simple way to limit concurrency on single host?

**Comment by bradrydzewski** [comment]
@sheerun the autoscaler provides this parameter https://autoscale.drone.io/reference/drone-agent-concurrency/

**Comment by bradrydzewski** [comment]
I wonder if this is something we could configure in the yaml. I think there are three primary use cases that I've seen, documented below. Note that I'm just brain-dumping syntax and hoping that maybe others will help bikeshed :)

__Syntax Example 1__

Prevent multiple concurrent builds by repository:

```
limit:
  concurrency: 2
```

Prevent multiple concurrent builds per-branch:

```
limit:
  - concurrency: 1
    branch: master
   - concurrency: 2
    branch: develop
```

Prevent multiple concurrent deployments per-environment:

```
limit:
  - event: deployment
    environment: production
    concurrency: 1
  - event: deployment
    environment: staging
    concurrency: 1
```

__Syntax Example 2__

Prevent multiple concurrent builds per-repository:

```
limit:
  concurrency: 1
```

Prevent multiple concurrent builds per-branch:

```
limit:
  concurrency: 1
  per_branch: true
```

Prevent multiple concurrent deployments per-environment:

```
limit:
  concurrency: 1
  per_deployment: true
```

**Comment by bradrydzewski** [comment]
concurrency parameter is available in latest release candidate

```
---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: webhook
  image: alpine
  commands:
  - curl -x POST http://abc.com:80/~smith/home.html

...
```

**Comment by Skaronator** [comment]
@bradrydzewski This only limits the concurrency of the whole pipeline and not just a single step?

For example I've a deployment step but only for the master branch, I'd like to limit the concurrency only of that particular step.

**Comment by bradrydzewski** [comment]
@Skaronator you can achieve this by defining two pipelines.  One pipeline executes if the branch is master, has a deployment step, and has concurrency 1.  The other pipeline executes on non-master and has no deployment step.

```
---
kind: pipeline
name: build

steps:
- name: build
  image: golang
  - go test
  - go build

trigger:
  branch:
    exclude: [ master ]

---
kind: pipeline
name: deploy

concurrency:
  limit: 1

steps:
- name: build
  image: golang
  - go test
  - go build

- name: deploy
  image: alpine
  commands:
  - # some commands to deploy

trigger:
  branch: [ master ]

...
```
