### ISSUE TITLE
Docker publish assumes sudo is installed

### ISSUE THREAD

**Issue by exocom** [drone/drone#817]
First off thanks for adding the docker publish plugin. I think it will be really useful for many people.

However the docker publish plugin doesn't seem to be compatible with all base images. When using the default node image the following error is produced:

```
$ type -p docker || wget -qO- https://get.docker.io/builds/Linux/x86_64/docker-1.3.tgz |sudo tar zxf - -C /
/usr/local/bin/drone: line 86: sudo: command not found
```

Here is my .drone.yml

```
image: node:latest
script:
  - echo $DRONE_COMMIT
  - npm install gulp -g
  - npm install
  - gulp test
publish:
   docker:
    dockerfile: Dockerfile
    docker_host: 0.0.0.0
    docker_port: 2375
    docker_version: 1.3
    registry_host: mysite.com
    registry_protocol: https
    registry_login: true
    registry_login_uri: /registry/v1/
    username: $$registry_user
    password: $$registry_pass
    image_name: myImage
    push_latest: true
    keep_builds: false
    tag: $$DRONE_COMMIT
```
