### ISSUE TITLE
RFC - Embed Docker/Machine

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#852]
I would like to create a new type of plugin for automatically adding servers (workers) to Drone via the user interface. We should use the [docker/machine](https://github.com/docker/machine) project as much as possible, since it already integrates with a bunch of providers, and handles installing and configuring Docker and generating SSL keys for secure communication over TCP.

I'm not 100% what this would look like, but here are some thoughts:

```toml
[amazon]
access_key = ""
secret_key = ""
session_token = ""
ami = ""
region = ""
vpc_id = ""
subnet_id = ""
zone = ""
security_group = ""
instance_type = ""
root_size = ""
```

The above toml description pretty much mirrors the flags defined for the amazon module in Docker machine. See the following:
https://github.com/docker/machine/blob/master/drivers/amazonec2/amazonec2.go#L75

We could then create a plugin in Drone at `/plugin/hosting/amazon`, initialize the plugin similar to GitHub and others, and this plugin could import the `docker/machine/amazon` package directly to create, start and stop servers.

The interface for a `Host` could look like this:

```
func Create() (Server, error)
func Destroy(Server) error
```

We should register each server with the worker pool on creation, and unregister when destroyed. We should persist the list of servers in the Drone database. We should register all servers with the worker pool when Drone first starts (by fetching the list from the database).

It would be great if we could start with a Digital Ocean implementation as a proof of concept to get things started.
