### ISSUE TITLE
Extend YAML to allow Docker Parameters for Services

### ISSUE THREAD

**Issue by dave-tucker** [drone/drone#865]
Let's say you want persistence for your `postgres` service

```yaml
services:
  - postgres
    docker:
      name: project_awesome_redis
      volume: {{awesome_volume}}:/var/lib/pgsql/data
```

Or maybe you want to your services and build container to share the same network namespace (no linking)

```yaml
services:
  - davetucker/drone-ovs
    docker:
      name: project_awesome_ovs

docker: 
   - net: container:project_awesome_ovs
```

There are potentially a lot more use cases, but these are the two that I can think of right now.

**Comment by bradrydzewski** [comment]
Yes, agreed.

The biggest hurdle will be coming up with a more flexible method for unmarshaling the yaml file to Go structures. This can be difficult given Go's static nature. For example, the yaml parser expects to unmarshal the below code into a `[]string`:

```
services:
  - postgres
  - redis
```

While the yaml parser will expect to unmarshal the below code into `map[string]*Docker`:

```
services:
  - postgres:
    docker:
      name: project_awesome_redis
      volume: foo:/var/lib/pgsql/data
```

Ideally we could accept both formats of the `service` section. The more simple format (`[]string`) will be suitable for most use cases, while the more complex format will be useful for more advanced use cases.

I'm not sure exactly how we'll work around Go's type system here, but my initial thought is to unmarshal the yaml to an intermediary, generic type (ie `map[string]interface{}`). We can then go back through, inspect and use something like [mapstructure](https://github.com/mitchellh/mapstructure) to unmarshal to a more specific type.

This would also be helpful for #696

This could even apply to a more broader issue that I'm trying to solve -- custom plugins (using the otto JavaScript engine) installed on the host machine and loaded when Drone starts. We need the ability to parse a yaml that could include user-defined types that are not defined in Go.

So I definitely agree. I think the solution intersects with a few other features I've been wanting to add for quite some time, so I need to think this through a bit more.
