### ISSUE TITLE
Allow multiple targets in notify plugins

### ISSUE THREAD

**Issue by donny-dont** [drone/drone#874]
Currently we have the slack plugin up and running on our internal drone server. Because of the amount of chatter from drone some teams have decided to relegate the build notifications to a separate channel from the main dev channel. An issue becomes that they can miss a failed build from a release branches because they're not paying attention.

For normal workflow they'd want something like

```yaml
notify:
  slack:
    webhook_url: 'https://hooks.slack.com/services/...'
    username: 'drone'
    channel: '#project-builds'
    on_started: false
    on_success: false
    on_failure: true
```

But on release or master they'd want something like

```yaml
  slack:
    webhook_url: 'https://hooks.slack.com/services/...'
    username: 'drone'
    channel: '#project'
    on_started: false
    on_success: true
    on_failure: true
    when:
      branch:
        - master
        - release*
```

So maybe having something like

```yaml
notify: 
  slack: 
    - 
      channel: "#project-builds"
      on_failure: true
      on_started: false
      on_success: true
      username: drone
      webhook_url: "https://hooks.slack.com/services/..."
    - 
      channel: "#project"
      on_failure: true
      on_started: false
      on_success: true
      username: drone
      webhook_url: "https://hooks.slack.com/services/..."
      when: 
        branch: 
          - master
          - release*
```

This could probably be applied to other sorts of plugins. For example on a release branch you might want to run run a full suite of tests for a release branch but not on develop as the full suite takes a significant amount of time.
