### ISSUE TITLE
secret variables evaluated in bash deploy script

### ISSUE THREAD

**Issue by JeanMertz** [drone/drone#904]
this:

```yaml
deploy:
  bash:
    command: curl --data "build=true" -X POST https://registry.hub.docker.com/u/my/image/trigger/$$DOCKER_BUILD_TOKEN
```

gets evaluated and `$$DOCKER_BUILD_TOKEN` is replaced by the actual value set through the GUI. Even when the GUI states those are "secret" variables.

Even when logged out, I can see the real value in the public log output.
