### ISSUE TITLE
Import docker-compose.yml for service container orchestration

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone#906]
see https://github.com/drone/drone/issues/902 for more context.

Some projects may include a `docker-compose.yml` file that defines advanced orchestration of supporting containers (ie mysql, redis, etc). This information gets duplicated in the `.drone.yml` file. The ability to import a `docker-compose.yml` file would eliminate duplication configuration and potentially allow more complex orchestration not exposed in the `.drone.yml`

So instead of this:

```
compose:
  redis:
    image: redis

  mysql:
    image: mysql
    environment:
      - mysql_password=foo
```

We could optionally do this:

```yaml
compose:
  from-file: docker-compose.yml
```
