### ISSUE TITLE
Build in Ramdisk

### ISSUE THREAD

**Issue by davidak** [drone/drone#925]
add an option to clone repository into a ramdisk.

i had experienced performance improvements by using a ramdisk inside a docker container.

maybe add an option for the drone admin to disable it since the hosted version has not unlimited RAM and maybe everybody uses it.

**Comment by MerlinDMC** [comment]
What stops you from creating a build image that mounts tmpfs to /var/drone? ... or even make it flagable via a ENV variable

**Comment by davidak** [comment]
in my actual builds with docker, where i run a bash script inside the container, i mount a ramdisk before i download the software to it i want to compile. i don't have to use special images.

with drone, i can't do that before the repo is cloned. i think it would be easy to add such an option.

```
image: ubuntu:14.04
ramdisk: 256M
script:
```

which does that before cloning the repo:
```
mkdir /var/drone
chmod 777 /var/drone
mount -t tmpfs -o size=256M tmpfs /var/drone
```

**Comment by bradrydzewski** [comment]
while I agree this is an interesting suggestion, we now mount the build volume as a shared container volume. The mounting itself is performed by Docker, so we don't have the ability to specify the mount type.

**Comment by emq** [comment]
Hey @davidak, did you maybe managed to solve this in a more elegant way using docker 1.1x and drone 0.7+? It seems now tmpfs support is more advanced https://docs.docker.com/engine/admin/volumes/tmpfs/ and I'm really interested in running whole builds within memory as I have pretty big (ram-wise) dedicated CI server, atm I'm looking for some ideas/resources :)

**Comment by alexislefebvre** [comment]
@emq Did you tested since you asked this question?

You can mount directories as `tmpfs`:

```yaml
services:
  mongo:
    image: mongo
    tmpfs: /data/db
```

Source: https://discourse.drone.io/t/is-it-possible-to-use-tmpfs-for-services-volumes/700/3

**Comment by emq** [comment]
@alexislefebvre I'm not longer using Drone for quite some time now, but yeah - since 0.8 it was a build-in feature if I remember correctly and worked great with database containers (we used self hosted drone + trusted repos)

**Comment by jarthod** [comment]
I was looking for how to this in drone `0.8.9` and this helped but the syntax is not exactly the same so in case anybody is looking for how to do this in drone `0.8.9`, here's an example:

```yaml
services:
  mongo:
    image: mongo:3.6.13
    tmpfs:
      - /data/db
  mariadb:
    image: mariadb:10.1
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    tmpfs:
      - /var/lib/mysql
```
